# Finetuning - QLoRA

https://huggingface.co/docs/peft/en/developer_guides/quantization


## Quantization
4비트 양자화(4-bit Quantization)는 모델의 가중치를 정밀도가 낮은 4비트 데이터 형식으로 변환하여 메모리 사용량을 획기적으로 줄이는 기술이다. 지적한 대로 모든 파라미터가 양자화 대상이 되는 것은 아니며, 성능 유지를 위해 전략적으로 적용된다.
4비트 양자화는 **"대세인 가중치는 작게 줄이고, 민감한 레이어와 통계 정보는 원본을 유지"**하는 전략이다. 이를 통해 일반 소비자용 GPU(예: RTX 3090/4090 24GB)에서도 30B급 대형 모델을 구동할 수 있게 된다.


**1. 4비트 양자화 시 메모리 변화**

30B 파라미터 모델을 기준으로 계산하면 다음과 같은 변화가 발생한다.

- **BF16 (기본):** 파라미터당 2바이트 $\rightarrow$ 약 **60GB** 필요
- **4-bit (양자화):** 파라미터당 0.5바이트 $\rightarrow$ 약 **15GB** 필요 (이론상 1/4 수준)

실제로는 양자화 과정에서 발생하는 스케일링 계수(Scaling Factor)와 메타데이터 때문에 약 **17~18GB** 정도의 VRAM을 사용하게 된다.

**2. 왜 모든 파라미터를 양자화하지 않는가?**

모델의 성능(Perplexity) 저하를 최소화하기 위해 **혼합 정밀도(Mixed Precision)** 방식을 사용한다.

- **양자화 대상 (Linear Layers):** 모델의 대부분을 차지하는 행렬 연산 가중치(Attention, MLP 레이어 등)는 4비트로 변환하여 용량을 줄인다.
- **양자화 제외 (Sensitive Layers):**
    - **Normalization 레이어:** LayerNorm 등은 수치 민감도가 매우 높아 원본 정밀도(FP32/BF16)를 유지한다.
    - **Embedding 레이어:** 텍스트를 벡터로 변환하는 첫 단계이므로 정밀도가 중요하다.
    - **LM Head:** 최종 출력층은 예측 정확도를 위해 보통 양자화하지 않는다.

**3. 주요 양자화 기법 (NF4)**

단순히 소수점을 자르는 것이 아니라, 데이터의 분포를 고려한 알고리즘을 사용한다. 가장 대표적인 것이 **NF4(NormalFloat 4)**이다.

- **특징:** 가중치가 정규분포를 따른다는 가정하에, 값이 몰려 있는 구간에는 촘촘하게, 값이 적은 구간에는 넓게 비트를 할당한다.
- **장점:** 일반적인 4비트 정수형(Int4)보다 정보 손실이 훨씬 적어 모델의 추론 능력을 잘 보존한다.

In [1]:
%pip install -Uq transformers datasets accelerate trl peft bitsandbytes hf_transfer wandb

Note: you may need to restart the kernel to use updated packages.

In [2]:
!nvidia-smi # GPU 확인 (모델명 / GPU ID / 메모리 사용량)

Wed Sep  9 06:28:00 2026
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.159.04             Driver Version: 580.159.04     CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA RTX PRO 6000 Blac...    On  |   00000000:C1:00.0 Off |                    0 |
| N/A   24C    P8             36W /  600W |       0MiB /  97887MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+

In [3]:
# 로컬 기준 환경변수 설정
# from dotenv import load_dotenv
# import os

# load_dotenv()
# os.environ['OPENAI_API_KEY'] = os.getenv('OPENAI_API_KEY')
# os.environ['HF_TOKEN'] = os.getenv('HF_TOKEN')

In [4]:
# Runpod 기준 환경변수 설정(Pod 에 환경 변수가 있어야 함)
import os

HF_TOKEN = os.environ['HF_TOKEN']

## 데이터셋 로드
https://huggingface.co/datasets/capybaraOh/naver-economy-news2stock

In [5]:
from datasets import load_dataset # HuggingFace 데이터셋 로더

# HuggingFace Hub train split 로드
dataset = load_dataset('capybaraOh/naver-economy-news2stock', split='train')
print(len(dataset))
dataset # Dataset 객체 정보

README.md:   0%|          | 0.00/347 [00:00<?, ?B/s]

data/train-00000-of-00001.parquet: reconstructing file:   0%|          |  0.00B / 2.27MB

data/train-00000-of-00001.parquet: downloading bytes:           |  0.00B

Generating train split:   0%|          | 0/1000 [00:00<?, ? examples/s]

1000

Dataset({
    features: ['system', 'user', 'assistant'],
    num_rows: 1000
})

In [6]:
dataset[0] # {'system' : ... , 'user' : ... , 'assistatnt':...}

{'system': "\n당신은 금융/경제 뉴스의 핵심내용을 요약해 설명하고,\n특정 상장 종목에 미치는 긍정/부정 영향여부, 이유, 근거를 분석하는 금융/경제 분석 전문가입니다.\n\n다음 출력지시사항을 지켜주세요.\n1. 뉴스와 종목간의 연관성을 발견할 수 없다면:\n    - stock_related를 False로 작성하세요.\n    - summary에 뉴스의 요약을 작성하세요.\n2. 뉴스와 종목간의 연관성을 발견했다면:\n    - stock_related를 True로 작성하세요.\n    - summary에 뉴스의 요약을 작성하세요.\n    - 긍정영향이 예상되는 종목이 있다면, positive_stocks, positive_keywords, positive_reasons를 작성하세요.\n    - 부정영향이 예상되는 종목이 있다면, negative_stocks, negative_keywords, negative_reasons를 작성하세요.\n    - 값이 없는 경우 빈 문자열(''), 빈 리스트([])로 작성하세요.\n",
 'user': '추경호 중기 수출지원 총력 무역금융 40조 확대\n앵커 정부가 올해 하반기 우리 경제의 버팀목인 수출 확대를 위해 총력을 기울이기로 했습니다. 특히 수출 중소기업의 물류난 해소를 위해 무역금융 규모를 40조 원 이상 확대하고 물류비 지원과 임시선박 투입 등을 추진하기로 했습니다. 류환홍 기자가 보도합니다. 기자 수출은 최고의 실적을 보였지만 수입액이 급증하면서 올해 상반기 우리나라 무역수지는 역대 최악인 103억 달러 적자를 기록했습니다. 정부가 수출확대에 총력을 기울이기로 한 것은 원자재 가격 상승 등 대외 리스크가 가중되는 상황에서 수출 증가세 지속이야말로 한국경제의 회복을 위한 열쇠라고 본 것입니다. 추경호 경제부총리 겸 기획재정부 장관 정부는 우리 경제의 성장엔진인 수출이 높은 증가세를 지속할 수 있도록 총력을 다하겠습니다. 우선 물류 부담 증가 원자재 가격 상승 등 가중되고 있는 대외 리스크에 대해 적극 대응하겠습니다. 특히 중소기업과 중견기업 수출 지원을 위해 무역금융 규모를 연초 목표보다 40조 원 늘린 301조 원까지 확대하고 물류비 부담을 줄이기 위한 대책도 마련했습니다. 이창양 산업통상자원부 장관 국제 해상운임이 안정될 때까지 월 4척 이상의 임시선박을 지속 투입하는 한편 중소기업 전용 선복 적재 용량 도 현재보다 주당 50TEU 늘려 공급하겠습니다. 하반기에 우리 기업들의 수출 기회를 늘리기 위해 2 500여 개 수출기업을 대상으로 해외 전시회 참가를 지원하는 등 마케팅 지원도 벌이기로 했습니다. 정부는 또 이달 중으로 반도체를 비롯한 첨단 산업 육성 전략을 마련해 수출 증가세를 뒷받침하고 에너지 소비를 줄이기 위한 효율화 방안을 마련해 무역수지 개선에 나서기로 했습니다. YTN 류환홍입니다.',
 'assistant': '{"stock_related":true,"summary":"정부는 원자재 가격 상승과 물류난 등 대외 리스크에 대응하고 수출 증가세를 유지하기 위해 하반기 수출지원 대책을 추진한다. 수출 중소·중견기업 지원을 위해 무역금융을 당초 계획보다 40조원 늘려 총 301조원 규모로 확대하고, 물류비 지원과 월 4척 이상의 임시선박 투입, 중소기업 전용 선복 확대를 시행한다. 또한 약 2,500개 수출기업의 해외 전시회 참가를 지원하고, 반도체 등 첨단산업 육성 전략과 에너지 효율화 방안을 마련해 수출 경쟁력과 무역수지 개선을 도모할 계획이다. 정책의 직접 수혜는 수출 중소기업과 첨단산업에 집중될 가능성이 높지만, 무역금융 확대만으로 수입 원자재 가격 상승에 따른 무역수지 적자가 해소된다고 보기는 어렵다.","positive_stocks":["삼성전자","SK하이닉스","현대차","기아","LG전자"],"positive_keywords":["무역금융 40조원 확대","수출 중소·중견기업 지원","반도체 등 첨단산업 육성","물류비 지원","해외 전시회 및 수출 마케팅 지원"],"positive_reasons":"무역금융 확대는 자금 조달 여력이 제한적인 수출기업의 생산·수주·운전자금 부담을 완화해 수출 물량 확대에 도움을 줄 수 있다. 삼성전자와 SK하이닉스는 정부의 반도체 중심 첨단산업 육성 전략의 직접적인 정책 수혜 가능성이 있으며, 현대차·기아·LG전자 등 글로벌 판매 비중이 높은 기업도 금융·물류 지원에 따른 수출 비용 절감과 해외 마케팅 확대의 간접 수혜가 예상된다. 다만 대형 기업은 중소기업보다 정책 지원의 직접 효과가 제한적이고, 실제 주가 영향은 반도체 수요와 원자재·환율·운임 등 시장 변수에 더 크게 좌우될 수 있다.","negative_stocks":["HMM","대한해운"],"negative_keywords":["임시선박 월 4척 이상 투입","중소기업 전용 선복 확대","해상운임 안정화","선복 공급 증가"],"negative_reasons":"정부가 임시선박을 지속 투입하고 중소기업 전용 선복을 확대하면 수출기업의 물류난은 완화되지만, 해상운송 공급이 늘어 운임이 하락할 경우 HMM·대한해운과 같은 해운사의 운임 및 수익성에는 부담이 될 수 있다. 다만 수출 물동량 증가가 운임 하락 효과를 상쇄할 가능성이 있어 부정적 영향은 해상운임과 글로벌 물동량의 방향에 따라 달라진다."}'}

In [7]:
# HuggingFace Dataset을 학습 / 평가 분리 후 Chat 메시지 포맷으로 변환
test_ratio = 0.2 # 평가셋 비율

train_data = [] # 학습 데이터 리스트
test_data = []  # 평가 데이터 리스트

data_indices = list(range(len(dataset))) # 전체 인덱스
test_size = int(len(dataset) * test_ratio) # 평가셋 크기

test_data_indices = data_indices[:test_size] # 앞부분은 평가셋 (인덱스)
train_data_indices = data_indices[test_size:] # 나머지는 학습셋 (인덱스)

# OpenAI / Chat 학습용 messages 포맷 : {'messages' : [{system},{user},{assistant}]}
def format_data(data):
    return {
        'messages' : [
            {
                'role' : 'system',
                'content' : data['system']
            },
            {
                'role' : 'user',
                'content' : data['user']
            },
            {
                'role' : 'assistant',
                'content' : data['assistant']
            },
        ]
    }

train_data = [format_data(dataset[i]) for i in train_data_indices] # 학습 인덱스 -> 학습 dict
test_data = [format_data(dataset[i]) for i in test_data_indices] # 평가 인덱스 -> 평가 dict

print(len(train_data))
print(len(test_data))

800
200

In [8]:
train_data[256] # message 포맷 dict 확인

{'messages': [{'role': 'system',
   'content': "\n당신은 금융/경제 뉴스의 핵심내용을 요약해 설명하고,\n특정 상장 종목에 미치는 긍정/부정 영향여부, 이유, 근거를 분석하는 금융/경제 분석 전문가입니다.\n\n다음 출력지시사항을 지켜주세요.\n1. 뉴스와 종목간의 연관성을 발견할 수 없다면:\n    - stock_related를 False로 작성하세요.\n    - summary에 뉴스의 요약을 작성하세요.\n2. 뉴스와 종목간의 연관성을 발견했다면:\n    - stock_related를 True로 작성하세요.\n    - summary에 뉴스의 요약을 작성하세요.\n    - 긍정영향이 예상되는 종목이 있다면, positive_stocks, positive_keywords, positive_reasons를 작성하세요.\n    - 부정영향이 예상되는 종목이 있다면, negative_stocks, negative_keywords, negative_reasons를 작성하세요.\n    - 값이 없는 경우 빈 문자열(''), 빈 리스트([])로 작성하세요.\n"},
  {'role': 'user',
   'content': '국토부 세종시 부적격 당첨자 철저히 조사해 엄중 조치\n원희룡 계약취소 및 주택환수 형사고발까지 필요 조치 취할 것 원희룡 국토교통부 장관. 2022.7.6 뉴스1 © News1 김명섭 기자 서울 뉴스1 박승희 기자 국토교통부는 감사원 감사에서 세종시 무자격 특공 당첨자가 무더기로 적발된 것과 관련해 위법행위 여부를 철저히 조사해 위법성이 밝혀지는 경우 엄중히 조치할 것 이라고 6일 밝혔다. 감사원은 세종시 이전기관 종사자 주택 특별공급에 대한 감사를 진행한 결과 총 45건 76명 에 대한 감사 결과를 확정했다. Δ대상관리 부실 Δ확인서 부당 발급 Δ확인서 위조 Δ중복 당첨 Δ지도·감독 소홀 등 사유로 무자격자가 대거 당첨된 것으로 드러났다. 국토부는 감사원으로부터 결과를 통보 받았으며 이에 따른 후속 조치를 강도 높게 추진하겠다는 입장이다. 원희룡 국토부 장관은 젊은 세대에게 상대적 박탈감을 준 부적격 특별공급에 대해 철저히 조사하고 계약취소 및 주택환수 형사고발까지 필요한 모든 조치를 취할 것 이라고 강조했다. 국토부는 위법하게 청약에 당첨된 76명에 대해 세종시에 관련 사실 관계를 파악하고 계약을 취소하거나 주택을 환수하도록 조치할 계획이다. 지자체 조치와 별도로 국토부에서 법령 위반 여부를 판단하고 위법성이 확인되면 고발 등 조치한다. 이에 따라 3년 이하의 징역 또는 3000만원 이하의 벌금 500만원 이하의 과태료를 부과할 수 있다. 사업자가 법령을 위반해 부적격 당첨자에게 주택을 공급한 경우에도 국토부에서 직접 사실관계를 조사한 뒤 위법 여부를 검토해 고발 등 조치할 방침이다. 이 경우 3년 이하의 징역 또는 3000만원 이하의 벌금 영업정지가 가능하다. 국토부 관계자는 주택공급을 총괄·감독하는 부처로서 책임감을 갖고 앞으로 공급시장 교란행위 등이 발생하지 않도록 불법행위 점검을 강화하는 한편 관련 제도 운영에 만전을 기할 것 이라고 말했다.'},
  {'role': 'assistant',
   'content': '{"stock_related":false,"summary":"국토교통부가 감사원 감사에서 적발된 세종시 이전기관 종사자 특별공급 부적격 당첨자 76명에 대해 사실관계를 철저히 조사하고, 위법성이 확인되면 계약 취소·주택 환수·형사고발 등 강력한 조치를 취하겠다고 밝혔습니다. 감사 결과에는 무자격 당첨, 특별공급 확인서 부당 발급 및 위조, 중복 당첨, 관계기관의 관리·감독 소홀 등이 포함됐습니다. 또한 부적격 당첨자에게 주택을 공급한 사업자에 대해서도 법령 위반 여부를 조사해 고발이나 영업정지 등의 조치를 검토할 방침입니다. 이번 조치는 주택공급 시장의 불법·교란행위를 차단하고 특별공급 제도의 공정성과 관리·감독을 강화하려는 데 목적이 있습니다.","positive_stocks":[],"positive_keywords":[],"positive_reasons":"","negative_stocks":[],"negative_keywords":[],"negative_reasons":""}'}]}

In [9]:
# List -> HuggingFace Dataset (내용은 그대로, 컨테이너만 변경)
from datasets import Dataset

train_dataset = Dataset.from_list(train_data)
test_dataset = Dataset.from_list(test_data)

train_dataset[256]

{'messages': [{'role': 'system',
   'content': "\n당신은 금융/경제 뉴스의 핵심내용을 요약해 설명하고,\n특정 상장 종목에 미치는 긍정/부정 영향여부, 이유, 근거를 분석하는 금융/경제 분석 전문가입니다.\n\n다음 출력지시사항을 지켜주세요.\n1. 뉴스와 종목간의 연관성을 발견할 수 없다면:\n    - stock_related를 False로 작성하세요.\n    - summary에 뉴스의 요약을 작성하세요.\n2. 뉴스와 종목간의 연관성을 발견했다면:\n    - stock_related를 True로 작성하세요.\n    - summary에 뉴스의 요약을 작성하세요.\n    - 긍정영향이 예상되는 종목이 있다면, positive_stocks, positive_keywords, positive_reasons를 작성하세요.\n    - 부정영향이 예상되는 종목이 있다면, negative_stocks, negative_keywords, negative_reasons를 작성하세요.\n    - 값이 없는 경우 빈 문자열(''), 빈 리스트([])로 작성하세요.\n"},
  {'role': 'user',
   'content': '국토부 세종시 부적격 당첨자 철저히 조사해 엄중 조치\n원희룡 계약취소 및 주택환수 형사고발까지 필요 조치 취할 것 원희룡 국토교통부 장관. 2022.7.6 뉴스1 © News1 김명섭 기자 서울 뉴스1 박승희 기자 국토교통부는 감사원 감사에서 세종시 무자격 특공 당첨자가 무더기로 적발된 것과 관련해 위법행위 여부를 철저히 조사해 위법성이 밝혀지는 경우 엄중히 조치할 것 이라고 6일 밝혔다. 감사원은 세종시 이전기관 종사자 주택 특별공급에 대한 감사를 진행한 결과 총 45건 76명 에 대한 감사 결과를 확정했다. Δ대상관리 부실 Δ확인서 부당 발급 Δ확인서 위조 Δ중복 당첨 Δ지도·감독 소홀 등 사유로 무자격자가 대거 당첨된 것으로 드러났다. 국토부는 감사원으로부터 결과를 통보 받았으며 이에 따른 후속 조치를 강도 높게 추진하겠다는 입장이다. 원희룡 국토부 장관은 젊은 세대에게 상대적 박탈감을 준 부적격 특별공급에 대해 철저히 조사하고 계약취소 및 주택환수 형사고발까지 필요한 모든 조치를 취할 것 이라고 강조했다. 국토부는 위법하게 청약에 당첨된 76명에 대해 세종시에 관련 사실 관계를 파악하고 계약을 취소하거나 주택을 환수하도록 조치할 계획이다. 지자체 조치와 별도로 국토부에서 법령 위반 여부를 판단하고 위법성이 확인되면 고발 등 조치한다. 이에 따라 3년 이하의 징역 또는 3000만원 이하의 벌금 500만원 이하의 과태료를 부과할 수 있다. 사업자가 법령을 위반해 부적격 당첨자에게 주택을 공급한 경우에도 국토부에서 직접 사실관계를 조사한 뒤 위법 여부를 검토해 고발 등 조치할 방침이다. 이 경우 3년 이하의 징역 또는 3000만원 이하의 벌금 영업정지가 가능하다. 국토부 관계자는 주택공급을 총괄·감독하는 부처로서 책임감을 갖고 앞으로 공급시장 교란행위 등이 발생하지 않도록 불법행위 점검을 강화하는 한편 관련 제도 운영에 만전을 기할 것 이라고 말했다.'},
  {'role': 'assistant',
   'content': '{"stock_related":false,"summary":"국토교통부가 감사원 감사에서 적발된 세종시 이전기관 종사자 특별공급 부적격 당첨자 76명에 대해 사실관계를 철저히 조사하고, 위법성이 확인되면 계약 취소·주택 환수·형사고발 등 강력한 조치를 취하겠다고 밝혔습니다. 감사 결과에는 무자격 당첨, 특별공급 확인서 부당 발급 및 위조, 중복 당첨, 관계기관의 관리·감독 소홀 등이 포함됐습니다. 또한 부적격 당첨자에게 주택을 공급한 사업자에 대해서도 법령 위반 여부를 조사해 고발이나 영업정지 등의 조치를 검토할 방침입니다. 이번 조치는 주택공급 시장의 불법·교란행위를 차단하고 특별공급 제도의 공정성과 관리·감독을 강화하려는 데 목적이 있습니다.","positive_stocks":[],"positive_keywords":[],"positive_reasons":"","negative_stocks":[],"negative_keywords":[],"negative_reasons":""}'}]}

## BaseModel + Quantizaton-Config

`BitsAndBytesConfig`는 Hugging Face Transformers에서 대형 모델을 8비트 또는 4비트로 양자화(quantization)하여 메모리 사용량을 줄이고, 저사양 환경에서도 대형 모델을 사용할 수 있게 도와주는 설정 클래스이다.

**주요 파라미터 목록**

| 파라미터명                  | 설명                                                                                          | 예시 값            |
|-----------------------------|----------------------------------------------------------------------------------------------|-------------------|
| `load_in_8bit`              | 8비트 양자화 활성화 여부. True로 설정 시 8비트로 모델 로드.                                    | True, False       |
| `load_in_4bit`              | 4비트 양자화 활성화 여부. True로 설정 시 4비트로 모델 로드.                                    | True, False       |
| `bnb_4bit_quant_type`       | 4비트 양자화 타입. `nf4`(NormalFloat4, 기본값), `fp4` 중 선택.                                 | "nf4", "fp4"      |
| `bnb_4bit_compute_dtype`    | 연산에 사용할 데이터 타입. 보통 `torch.float16`, `torch.bfloat16`, `torch.float32` 중 선택.     | torch.bfloat16    |
| `bnb_4bit_use_double_quant` | 이중 양자화 사용 여부. True로 설정 시 추가 양자화로 메모리 절감 가능.                           | True, False       |
| `llm_int8_threshold`        | 8비트 양자화 시 threshold 지정. 값이 낮을수록 더 많은 파라미터가 8비트로 변환됨.                | 0.0 ~ 6.0         |
| `llm_int8_skip_modules`     | 양자화에서 제외할 모듈 리스트.                                                                | ["lm_head"]       |
| `bnb_4bit_quant_storage`    | 4비트 파라미터 저장에 사용할 타입. 기본값은 `torch.uint8`.                                    | torch.uint8       |


- **load_in_8bit**  
  8비트 양자화를 활성화하는 플래그이다. True로 설정 시 모델 파라미터를 8비트 정수로 변환하여 메모리 사용량을 약 75%까지 줄일 수 있다.

- **load_in_4bit**  
  4비트 양자화를 활성화하는 플래그이다. True로 설정 시 더욱 극적인 메모리 절감 효과를 볼 수 있다. 4비트 양자화는 QLoRA 등 최신 연구에서 자주 사용된다.

- **bnb_4bit_quant_type**  
  4비트 양자화 시 사용할 데이터 타입을 지정한다.  
  - `nf4`: NormalFloat4 (기본값, QLoRA에서 주로 사용)  
  - `fp4`: FP4 타입.

- **bnb_4bit_compute_dtype**  
  연산(Forward/Backward) 시 사용할 데이터 타입을 지정한다.  
  - `torch.float16`, `torch.bfloat16`, `torch.float32` 등이 있다.  
  - 16비트 타입을 사용하면 연산 속도가 빨라지고, 메모리 사용량도 줄일 수 있다.

- **bnb_4bit_use_double_quant**  
  이중 양자화(nested quantization)를 활성화하는 옵션이다. True로 설정 시 한 번 더 양자화를 적용하여 메모리 사용량을 추가로 절감할 수 있다. 메모리 부족 시 유용하다.

- **llm_int8_threshold**  
  8비트 양자화 시 threshold 값을 조정하여, threshold 이하의 weight만 8비트로 변환한다. 값이 낮을수록 더 많은 파라미터가 8비트로 변환된다.

- **llm_int8_skip_modules**  
  양자화에서 제외할 모듈(레이어) 리스트를 지정한다. 예를 들어, 출력 레이어(`lm_head`) 등은 양자화에서 제외할 수 있다.

- **bnb_4bit_quant_storage**  
  4비트 파라미터 저장에 사용할 데이터 타입을 지정한다. 기본값은 `torch.uint8`이다.


**활용 팁**

- **메모리가 부족하다면**: `bnb_4bit_use_double_quant=True`로 설정.
- **정밀도가 중요하다면**: `bnb_4bit_quant_type="nf4"`로 설정.
- **학습 속도가 중요하다면**: `bnb_4bit_compute_dtype`를 16비트(float16, bfloat16)로 설정.

- `BitsAndBytesConfig`는 4비트/8비트 양자화 옵션을 통합 관리하며, 파라미터 조합을 통해 다양한 하드웨어 환경에 맞는 최적화가 가능하다.

In [10]:
# 4bit 양자화 설정(BitsAndBytesConfig)
from transformers import BitsAndBytesConfig
import torch

quant_config = BitsAndBytesConfig(
    load_in_4bit=True,                      # 4bit 양자화(모델 가중치를 4bit)
    bnb_4bit_quant_type = 'nf4',            # 4bit 양자화 방식
    bnb_4bit_use_double_quant=True,         # 이중 양자화 : 메모리 / 정확도 균형 개선
    bnb_4bit_compute_dtype=torch.bfloat16   # 연산 방식 bfloat16
)

In [11]:
from transformers import AutoTokenizer, AutoModelForCausalLM  # 토크나이저 / 생성형 모델 자동 로더
import torch

pretrained_model_name = 'NCSOFT/Llama-VARCO-8B-Instruct'  # 사전학습 모델명

model = AutoModelForCausalLM.from_pretrained(
    pretrained_model_name,
    dtype = torch.bfloat16,  # 가중치 로딩 dtype(bf16)
    device_map = 'auto',      # 환경에 맞춰 CPU / GPU 자동 배치
    quantization_config = quant_config   # 4bit 양자화 설정 적용
)

tokenizer = AutoTokenizer.from_pretrained(pretrained_model_name)  # 해당 모델의 토크나이저 로드

config.json:   0%|          | 0.00/777 [00:00<?, ?B/s]

model.safetensors.index.json:   0%|          | 0.00/23.9k [00:00<?, ?B/s]

Downloading bytes:           |  0.00B

Reconstructing (incomplete total...): |          |  0.00B /  0.00B

Fetching 4 files:   0%|          | 0/4 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/291 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/51.2k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/9.08M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/430 [00:00<?, ?B/s]

## BaseModel + Quantizaton-Config

`BitsAndBytesConfig`는 Hugging Face Transformers에서 대형 모델을 8비트 또는 4비트로 양자화(quantization)하여 메모리 사용량을 줄이고, 저사양 환경에서도 대형 모델을 사용할 수 있게 도와주는 설정 클래스이다.

**주요 파라미터 목록**

| 파라미터명                  | 설명                                                                                          | 예시 값            |
|-----------------------------|----------------------------------------------------------------------------------------------|-------------------|
| `load_in_8bit`              | 8비트 양자화 활성화 여부. True로 설정 시 8비트로 모델 로드.                                    | True, False       |
| `load_in_4bit`              | 4비트 양자화 활성화 여부. True로 설정 시 4비트로 모델 로드.                                    | True, False       |
| `bnb_4bit_quant_type`       | 4비트 양자화 타입. `nf4`(NormalFloat4, 기본값), `fp4` 중 선택.                                 | "nf4", "fp4"      |
| `bnb_4bit_compute_dtype`    | 연산에 사용할 데이터 타입. 보통 `torch.float16`, `torch.bfloat16`, `torch.float32` 중 선택.     | torch.bfloat16    |
| `bnb_4bit_use_double_quant` | 이중 양자화 사용 여부. True로 설정 시 추가 양자화로 메모리 절감 가능.                           | True, False       |
| `llm_int8_threshold`        | 8비트 양자화 시 threshold 지정. 값이 낮을수록 더 많은 파라미터가 8비트로 변환됨.                | 0.0 ~ 6.0         |
| `llm_int8_skip_modules`     | 양자화에서 제외할 모듈 리스트.                                                                | ["lm_head"]       |
| `bnb_4bit_quant_storage`    | 4비트 파라미터 저장에 사용할 타입. 기본값은 `torch.uint8`.                                    | torch.uint8       |


- **load_in_8bit**  
  8비트 양자화를 활성화하는 플래그이다. True로 설정 시 모델 파라미터를 8비트 정수로 변환하여 메모리 사용량을 약 75%까지 줄일 수 있다.

- **load_in_4bit**  
  4비트 양자화를 활성화하는 플래그이다. True로 설정 시 더욱 극적인 메모리 절감 효과를 볼 수 있다. 4비트 양자화는 QLoRA 등 최신 연구에서 자주 사용된다.

- **bnb_4bit_quant_type**  
  4비트 양자화 시 사용할 데이터 타입을 지정한다.  
  - `nf4`: NormalFloat4 (기본값, QLoRA에서 주로 사용)  
  - `fp4`: FP4 타입.

- **bnb_4bit_compute_dtype**  
  연산(Forward/Backward) 시 사용할 데이터 타입을 지정한다.  
  - `torch.float16`, `torch.bfloat16`, `torch.float32` 등이 있다.  
  - 16비트 타입을 사용하면 연산 속도가 빨라지고, 메모리 사용량도 줄일 수 있다.

- **bnb_4bit_use_double_quant**  
  이중 양자화(nested quantization)를 활성화하는 옵션이다. True로 설정 시 한 번 더 양자화를 적용하여 메모리 사용량을 추가로 절감할 수 있다. 메모리 부족 시 유용하다.

- **llm_int8_threshold**  
  8비트 양자화 시 threshold 값을 조정하여, threshold 이하의 weight만 8비트로 변환한다. 값이 낮을수록 더 많은 파라미터가 8비트로 변환된다.

- **llm_int8_skip_modules**  
  양자화에서 제외할 모듈(레이어) 리스트를 지정한다. 예를 들어, 출력 레이어(`lm_head`) 등은 양자화에서 제외할 수 있다.

- **bnb_4bit_quant_storage**  
  4비트 파라미터 저장에 사용할 데이터 타입을 지정한다. 기본값은 `torch.uint8`이다.


**활용 팁**

- **메모리가 부족하다면**: `bnb_4bit_use_double_quant=True`로 설정.
- **정밀도가 중요하다면**: `bnb_4bit_quant_type="nf4"`로 설정.
- **학습 속도가 중요하다면**: `bnb_4bit_compute_dtype`를 16비트(float16, bfloat16)로 설정.

- `BitsAndBytesConfig`는 4비트/8비트 양자화 옵션을 통합 관리하며, 파라미터 조합을 통해 다양한 하드웨어 환경에 맞는 최적화가 가능하다.

In [12]:
# 하나의 샘플만 openai 방식 메시지 -> llama3 방식 메시지로 변환
text = tokenizer.apply_chat_template(train_dataset[128]['messages'], tokenize=False)
print(text)

<|begin_of_text|><|start_header_id|>system<|end_header_id|>

당신은 금융/경제 뉴스의 핵심내용을 요약해 설명하고,
특정 상장 종목에 미치는 긍정/부정 영향여부, 이유, 근거를 분석하는 금융/경제 분석 전문가입니다.

다음 출력지시사항을 지켜주세요.
1. 뉴스와 종목간의 연관성을 발견할 수 없다면:
    - stock_related를 False로 작성하세요.
    - summary에 뉴스의 요약을 작성하세요.
2. 뉴스와 종목간의 연관성을 발견했다면:
    - stock_related를 True로 작성하세요.
    - summary에 뉴스의 요약을 작성하세요.
    - 긍정영향이 예상되는 종목이 있다면, positive_stocks, positive_keywords, positive_reasons를 작성하세요.
    - 부정영향이 예상되는 종목이 있다면, negative_stocks, negative_keywords, negative_reasons를 작성하세요.
    - 값이 없는 경우 빈 문자열(''), 빈 리스트([])로 작성하세요.<|eot_id|><|start_header_id|>user<|end_header_id|>

에어부산 울란바토르·오사카 노선 재개
에어부산이 김해국제공항에서 출발하는 몽골 울란바토르와 일본 오사카 노선 운항을 각각 주 2회 일정으로 코로나19 팬데믹 사태 이후 28개월 만에 재개한다고 1일 밝혔다. 부산 울란바토르 노선은 김해국제공항에서 오전 8시 25분에 출발해 현지 공항에 오전 11시 40분 도착하고 귀국편은 오후 1시에 출발해 김해공항에 오후 5시 30분 도착하는 일정으로 주 2회 운항한다. 몽골은 입국 시 코로나19 검사와 백신 접종 여부를 확인하지 않아 자유롭게 여행이 가능한 국가다. 부산 오사카 노선은 김해공항에서 오전 8시 35분에 출발해 간사이공항에 오전 10시 도착 귀국편은 간사이공항에서 낮 12시에 출발해 김해공항에 오후 1시 30분 도착하는 일정으로 주 2회 운항한다. 에어부산 관계자는 이번 증편은 무비자 입국이 복원됐을 때 폭발하는 여행 수요를 선점하기 위한 선제적 조치 라고 밝혔다. 이밖에도 에어부산은 이달 중 부산에서 출발하는 코타키나발루 나트랑 세부 노선 등을 운항할 예정이다. 인천국제공항에서는 이달 14일부터 순차적으로 다낭 방콕 후쿠오카 등 노선을 신규 취항한다.<|eot_id|><|start_header_id|>assistant<|end_header_id|>

{"stock_related":true,"summary":"에어부산이 코로나19 이후 28개월 만에 김해공항발 울란바토르·오사카 노선을 각각 주 2회 재개한다. 몽골은 코로나19 관련 입국 제한이 없고, 일본은 무비자 입국 재개 시 여행 수요가 크게 회복될 가능성이 있어 에어부산은 수요 선점을 위해 선제적으로 운항을 확대한다. 이와 함께 코타키나발루·나트랑·세부 노선 재개 및 인천발 다낭·방콕·후쿠오카 신규 취항도 추진한다. 국제선 운항 확대는 여객 수요 회복, 항공기 가동률 상승, 매출 개선에 긍정적이지만, 초기에는 운항 재개 비용과 유류비·환율·경쟁 심화가 수익성의 변수로 작용할 수 있다.","positive_stocks":["에어부산"],"positive_keywords":["국제선 운항 재개","울란바토르·오사카 노선","무비자 입국","여행 수요 회복","노선 확대","항공기 가동률 상승"],"positive_reasons":"에어부산의 국제선 운항 노선과 공급 좌석이 늘어나면서 여객 매출 및 항공기 가동률 개선이 기대된다. 특히 일본 오사카와 동남아 노선은 단거리·관광 수요가 높은 지역이며, 몽골은 입국 제한이 없어 여행 수요를 빠르게 확보할 가능성이 있다. 향후 무비자 입국과 방역 규제 완화가 확대되면 예약률과 탑승률 상승으로 실적 회복이 가속화될 수 있다. 다만 실제 주가 및 실적 영향은 탑승률, 운임 수준, 유류비와 환율에 따라 달라질 수 있다.","negative_stocks":[],"negative_keywords":[],"negative_reasons":""}<|eot_id|><|start_header_id|>assistant<|end_header_id|>

In [13]:
# Lllam3 계열 Chat 학습용 데이터 콜레이터 : 프롬프트 생성 -> 토크나이즈/패딩 -> assistant 구간만 라벨링
# - 배치(messages)를 입력받아, 모델 학습 텐서로 변환
def data_collator(batch, tokenizer=tokenizer, max_length=8192):
    # 1. 프롬프트 생성
    prompts = []  # 배치 프롬프트 문자열을 담을 리스트
    for example in batch:
        prompt = '<|begin_of_text|>'  # 프롬프트 시작 토큰
        for msg in example['messages']:  # 샘플 내에서 (system/user/assistant) 순회
            role = msg['role']
            content = msg['content'].strip()
            # role + content로 템플릿을 완성
            prompt += f"<|start_header_id|>{role}<|end_header_id|>\n{content}<|eot_id|>"
        prompts.append(prompt)
    # print(prompts)

    # 2. 토큰처리 / 패딩 / 텐서 변환
    
    # 프롬프트를 토큰화해서 텐서로 변환
    tokenized = tokenizer(
        prompt,
        truncation = True,         # 최대 길이 초과시 자름
        max_length = max_length,   # 최대 길이 설정
        padding = True,            # 최대 길이 미만시 패딩 처리
        return_tensors = "pt"      # Pytorch Tensor 반환
    )
    input_ids = tokenized['input_ids']  # 토큰 id 텐서
    attention_mask = tokenized['attention_mask']  # 패딩 마스크 텐서
    # print(tokenized)
    # print(len(tokenized['input_ids'][0]))
    # print(len(tokenized['input_ids'][1]))
    # print(len(tokenized['attention_mask'][0]), len(tokenized['attention_mask'][0].sum().item()))
    # print(len(tokenized['attention_mask'][0]), len(tokenized['attention_mask'][0].sum().item()))

    # 3. 라벨 생성
    labels = torch.full_like(input_ids, fill_value=-100)  # input_ids shape으로 -100 기본값. (손실 계산 제외)
    print(labels.shape)

    assistant_header = '<|start_header_id|>assistant<|end_header_id|>\n'
    assistant_token_id = tokenizer.encode(assistant_header, add_special_tokens=False)  # 헤더의 토큰 패턴
    eot_token = '<|eot_id|>'
    eot_token_id = tokenizer.encode(eot_token, add_special_tokens=False)  # 종료 토큰의 토큰 패턴
    print(assistant_token_id)
    print(eot_token_id)

    for i, ids in enumerate(input_ids):  # 각 샘플별로 순회
        ids_list = ids.tolist()  # 슬라이싱 사용하기 위해 list로 변경
        
        # assistant 답변 시작위치 찾음
        # - <|start_header_id|>assistant<|end_header_id|>\n 다음 인덱스부터 답변으로 수집
        start = None  # 답변 시작 인덱스 초기화
        for idx in range(len(ids_list) - len(assistant_token_id) + 1):  # 헤더 길이만큼 탐색
            # assistant header 패턴과 매칭시
            if ids_list[idx: idx + len(assistant_token_id)] == assistant_token_id:
                start = idx + len(assistant_token_id)  # 헤더 다음 토큰부터 라벨링 시작
                break  # 첫 번째 assistant 구간 후 해당 for문 탈출
        
        # 답변 끝 위치 찾음 : <|eot_id|> 전까지
        if start is not None:  # assistant 헤더를 찾은 경우
            end = None  # 답변 종료 인덱스 초기화
            for idx in range(start, len(ids_list) - len(eot_token_id) + 1):  # start ~ 종료 토큰 전
                # start부터 종료 패턴과 매칭시
                if ids_list[idx: idx + len(eot_token_id)] == eot_token_id:
                    end = idx + len(eot_token_id)  # eot까지 포함한 구간 설정
                    break  # 첫 번째 eot 구간 후 해당 for문 탈출
        print(f"{i}: {start} ~ {end}")
        labels[i, start:end] = input_ids[i, start:end]  # assistant 답변 부분만 정답 라벨로 복사

    return {
        'input_ids': input_ids,  # 모델 입력
        'attention_mask': attention_mask,  # 패딩 마스크
        'labels': labels  # 손실 계산용 라벨(assistant 답변 부분만 labels 활용)
    }

data_collator([train_dataset[0], train_dataset[1]])

torch.Size([1, 1112])
[128006, 78191, 128007, 198]
[128009]
0: 623 ~ 1112

{'input_ids': tensor([[128000, 128006,   9125,  ...,  63466,     92, 128009]]),
 'attention_mask': tensor([[1, 1, 1,  ..., 1, 1, 1]]),
 'labels': tensor([[  -100,   -100,   -100,  ...,  63466,     92, 128009]])}

### Causal Language Model 파인튜닝: input_ids와 labels 구조 이해

**데이터 구조**
```
input_ids:  [system_tokens..., user_tokens..., assistant_tokens...]  # 전체 시퀀스
labels:     [-100, -100, ..., -100, assistant_tokens...]          # assistant만 학습 대상
```

| 항목 | 내용 |
| --- | --- |
| **Input IDs** | 프롬프트 + 정답 (전체 시퀀스) |
| **Labels** | `-100` (프롬프트 구간) + 정답 토큰 (답변 구간) |
| **결과** | 모델은 입력을 다 보지만, 오직 답변을 맞히는 과정에서만 학습이 일어남 |




> **질문에 해당하는 input_ids에 이미 답이 포함되어 있다!**
>
> **"답이 이미 있는데 어떻게 학습하는가?"**
>
> 모델은 정답을 "보면서" 각 위치에서 올바른 다음 토큰을 예측하는 법을 배운다. 마치 학생이 모범답안을 보며 "이 상황에서는 이렇게 답해야 한다"를 학습하는 것과 같다. 이것이 현대 LLM 파인튜닝의 핵심 메커니즘이다!


**_1. 인과적 언어 모델링 (Causal Language Modeling):_**

LLM(Llama, GPT 등)은 **이전 토큰들을 보고 다음 토큰을 예측**하는 방식으로 학습한다. 따라서 학습 데이터에는 프롬프트와 정답이 모두 포함된 전체 문장이 들어가야 한다.

* **학습 원리:** 모델은 번째 토큰까지를 입력으로 받아 번째 토큰을 예측한다.
* **구조:** `input_ids`가 `[A, B, C, D]`라면, 모델은 내부적으로 `A`를 보고 `B`를, `A, B`를 보고 `C`를 예측하는 과정을 동시에 수행한다.

**_2. Teacher Forcing 기법:_**
```
Position:   [0, 1, 2, 3, 4, 5, 6, 7, 8]
input_ids:  [A, B, C, D, E, F, G, H, I]
labels:     [-100, -100, -100, -100, E, F, G, H, I]
```

학습 과정:
- Position 4: A,B,C,D를 보고 → E 예측
- Position 5: A,B,C,D,E를 보고 → F 예측  
- Position 6: A,B,C,D,E,F를 보고 → G 예측

**_3. Labels와 Loss 계산의 역할:_**

`input_ids`에 정답이 포함되어 있더라도, 모델이 모든 구간에 대해 학습(손실 계산)을 수행하는 것은 아니다. 이때 중요한 역할을 하는 것이 바로 코드에 작성된 **`labels`**이다.

* **-100의 의미:** PyTorch의 `CrossEntropyLoss`는 기본적으로 레이블 값이 `-100`인 위치를 무시(ignore)한다.
* **학습 차단:** 코드에서 프롬프트(User 질문 등) 구간의 레이블을 `-100`으로 설정했기 때문에, 모델이 프롬프트 내용을 예측하며 발생하는 오차는 학습에 반영되지 않는다.
* **학습 집중:** 오직 `assistant`의 답변 구간에 해당하는 `labels`만 실제 `input_ids` 값을 가지므로, 모델은 **"프롬프트가 주어졌을 때 정답을 생성하는 방법"**에 대해서만 가중치를 업데이트한다.


**학습 vs 추론의 차이**

**_학습 시:_**
```
input_ids: <system>당신은 금융분석가</system><user>뉴스내용</user><assistant>분석결과</assistant>
labels:    [-100, -100, ..., -100, 분석결과_토큰들]
```

**_추론 시:_**
```
input:  <system>당신은 금융분석가</system><user>뉴스내용</user><assistant>
output: 분석결과 (모델이 한 토큰씩 생성)
```

In [14]:
# 테스트 데이터로 변환된 결과 확인
example = train_dataset[256]
batch = data_collator([example]) # 배치 1개로 콜레이터 적용

print(f"{batch['input_ids'].shape}")    # input_ids 텐서 shape
print(f"{batch['attention_mask'].shape}") # attention_mask 텐서 shape
print(f"{batch['labels'].shape}") # labels 텐서 shape

torch.Size([1, 1093])
[128006, 78191, 128007, 198]
[128009]
0: 844 ~ 1093
torch.Size([1, 1093])
torch.Size([1, 1093])
torch.Size([1, 1093])

In [15]:
print(batch['input_ids'][0].tolist()) # 0번째 샘플 input_ids 리스트
print(batch['attention_mask'][0].tolist()) # 0번째 샘플 attention_mask 리스트
print(batch['labels'][0].tolist()) # 0번째 샘플 labels 리스트 (답변 제외 -100)

[128000, 128006, 9125, 128007, 198, 65895, 83628, 34804, 104193, 123061, 14, 127463, 111068, 120226, 125959, 102612, 96318, 27797, 18359, 87097, 103168, 34983, 114942, 101360, 345, 108159, 30381, 59134, 41953, 99458, 88708, 19954, 101412, 116129, 41871, 235, 30381, 14, 64189, 30381, 115754, 58126, 64189, 11, 111436, 11, 106589, 93292, 18918, 109862, 44005, 104193, 123061, 14, 127463, 109862, 116425, 20565, 80052, 382, 13447, 49531, 62226, 22035, 30426, 115790, 18359, 67890, 115061, 92769, 627, 16, 13, 111068, 25941, 81673, 99458, 88708, 63375, 21028, 78453, 101106, 111490, 121712, 48936, 29833, 47782, 115300, 512, 262, 482, 5708, 54356, 18918, 3641, 17835, 114839, 92245, 627, 262, 482, 12399, 19954, 111068, 120226, 87097, 103168, 18359, 114839, 92245, 627, 17, 13, 111068, 25941, 81673, 99458, 88708, 63375, 21028, 78453, 101106, 111490, 121712, 101528, 33390, 512, 262, 482, 5708, 54356, 18918, 3082, 17835, 114839, 92245, 627, 262, 482, 12399, 19954, 111068, 120226, 87097, 103168, 18359, 114839, 92245, 627, 262, 482, 41871, 235, 30381, 101090, 104762, 13094, 96717, 57002, 107205, 99458, 88708, 13094, 91786, 33390, 11, 6928, 1284, 26246, 11, 6928, 52454, 11, 6928, 39329, 82, 18918, 114839, 92245, 627, 262, 482, 86503, 30381, 101090, 104762, 13094, 96717, 57002, 107205, 99458, 88708, 13094, 91786, 33390, 11, 8389, 1284, 26246, 11, 8389, 52454, 11, 8389, 39329, 82, 18918, 114839, 92245, 627, 262, 482, 46663, 13094, 108838, 50152, 122292, 81021, 55055, 493, 4670, 122292, 84734, 10779, 8, 17835, 114839, 92245, 13, 128009, 128006, 882, 128007, 198, 100654, 101665, 64189, 101852, 102757, 30426, 86503, 82068, 102079, 103153, 36155, 101, 26799, 112521, 101464, 101709, 127614, 34983, 112190, 101711, 66610, 60798, 198, 55421, 105204, 126963, 120287, 114039, 44690, 101824, 56773, 104727, 66338, 24140, 106612, 56154, 35495, 102133, 102704, 108289, 66610, 60798, 107545, 48936, 72208, 102467, 105204, 126963, 102160, 101665, 100848, 102233, 64189, 102027, 101106, 13, 220, 2366, 17, 13, 22, 13, 21, 111068, 25941, 16, 7388, 5513, 16, 102155, 80732, 123894, 126887, 106010, 111068, 25941, 16, 104293, 104303, 105204, 126887, 102160, 101665, 100848, 102233, 64189, 16969, 117078, 55421, 117078, 57575, 101852, 102757, 30426, 101480, 26799, 102079, 103966, 79225, 103153, 36155, 101, 108181, 101480, 102913, 122211, 103607, 102133, 53400, 72208, 54780, 106434, 34983, 46810, 101661, 101066, 82001, 84618, 64189, 18918, 112521, 101464, 101709, 127614, 34983, 46810, 101661, 115602, 116283, 113048, 107054, 50152, 112190, 101711, 101709, 66610, 60798, 48936, 72208, 23955, 105771, 220, 21, 33177, 116283, 35859, 104828, 13, 117078, 55421, 34804, 101852, 102757, 30426, 119444, 120072, 99458, 56154, 26799, 56773, 104727, 120295, 79225, 102662, 19954, 102597, 103185, 111636, 111809, 24486, 99901, 107152, 220, 1774, 101868, 220, 4767, 80732, 91586, 102597, 117078, 99901, 18918, 103686, 30381, 101528, 13, 82263, 67945, 57002, 106974, 86503, 101272, 82263, 34693, 67361, 27796, 86503, 65895, 97096, 102662, 82263, 34693, 67361, 27796, 46810, 93917, 82263, 101711, 98934, 103153, 36155, 101, 82263, 113037, 14260, 103655, 104841, 101228, 124800, 78102, 33229, 101314, 17835, 101480, 26799, 102079, 108181, 62060, 93292, 103153, 36155, 101, 53400, 111590, 103745, 61394, 118436, 13, 102160, 101665, 64189, 16969, 117078, 55421, 43139, 103551, 99901, 18918, 102681, 42771, 84696, 101760, 104429, 23955, 19954, 122453, 95415, 102130, 66610, 125155, 102258, 49085, 108499, 58901, 58935, 86351, 16582, 103373, 105453, 39250, 41953, 101568, 13, 102467, 105204, 126963, 102160, 101665, 64189, 102027, 101106, 34804, 19097, 123143, 101852, 67945, 102244, 126761, 82068, 104293, 110517, 103655, 18359, 108683, 86503, 82068, 102079, 120295, 79225, 102662, 19954, 112107, 112521, 101464, 101709, 127614, 101360, 120287, 114039, 44690, 101824, 56773, 104727, 66338, 24140, 106612, 56154, 35495, 102133, 102704, 126168, 107036, 66610, 125155, 107545, 48936, 72208, 23955, 105771, 102258, 93917, 101528, 13, 102160, 101665, 64189, 16969, 46810, 101661, 102893, 105519, 103168, 19954, 103153, 36155, 101, 53400, 220, 4767, 80732, 19954, 112107, 101852, 102757, 118472, 106434, 112024, 116680, 18918, 56069, 106356, 101360, 120287, 18359, 107545, 44690, 16582, 109745, 56773, 104727, 18359, 104613, 24140, 16582, 108438, 66610, 60798, 48936, 119623, 101568, 13, 67890, 26799, 50643, 66610, 60798, 81673, 110192, 116353, 102160, 101665, 64189, 57575, 107849, 104366, 46810, 101738, 84618, 64189, 18918, 106478, 101353, 101360, 46810, 101661, 115602, 74959, 65219, 33390, 101254, 102133, 78102, 66610, 60798, 52976, 13, 23955, 19954, 106725, 220, 18, 100392, 23955, 16582, 21028, 49011, 243, 101577, 108520, 220, 3101, 15, 106115, 23955, 16582, 21028, 112734, 101136, 220, 2636, 106115, 23955, 16582, 21028, 104219, 87472, 64356, 18918, 86503, 54780, 48936, 29833, 91786, 13, 115888, 108181, 107849, 104366, 18359, 46810, 101738, 34983, 86503, 82068, 102079, 103153, 36155, 101, 26799, 102244, 56773, 104727, 18359, 100994, 102662, 24486, 50152, 109018, 102160, 101665, 64189, 57575, 120307, 112024, 126951, 18918, 127614, 24486, 107333, 46810, 101661, 84618, 64189, 18918, 86422, 101665, 34983, 101254, 102133, 78102, 66610, 60798, 48936, 75908, 108308, 101568, 13, 23955, 50152, 220, 18, 100392, 23955, 16582, 21028, 49011, 243, 101577, 108520, 220, 3101, 15, 106115, 23955, 16582, 21028, 112734, 101136, 101603, 101096, 30381, 122877, 96451, 108907, 13, 102160, 101665, 64189, 116680, 112953, 56773, 104727, 79225, 102662, 18359, 107152, 117484, 226, 14260, 103655, 104841, 44005, 86503, 102657, 121803, 110080, 94801, 103655, 18359, 116253, 35495, 107758, 43139, 100994, 102662, 30426, 41953, 101999, 103272, 101066, 82001, 78102, 13094, 113610, 88525, 51796, 108438, 102786, 101661, 101066, 82001, 106313, 109070, 18359, 102258, 57390, 44005, 62398, 104790, 106434, 63171, 49085, 107065, 19954, 63207, 66965, 18359, 55216, 48936, 72208, 23955, 105771, 108537, 13, 128009, 128006, 78191, 128007, 198, 5018, 13787, 54356, 794, 3934, 1359, 1743, 3332, 100654, 101665, 100848, 102233, 64189, 20565, 117078, 55421, 117078, 57575, 103607, 102133, 53400, 101852, 102757, 30426, 119444, 120072, 99458, 56154, 26799, 120295, 79225, 102662, 86503, 82068, 102079, 103153, 36155, 101, 26799, 220, 4767, 80732, 19954, 112107, 112024, 126951, 18918, 112521, 101464, 101709, 127614, 101360, 11, 46810, 101661, 115602, 74959, 65219, 33390, 120287, 107545, 44690, 14260, 55430, 104727, 104613, 24140, 14260, 102193, 56154, 35495, 102133, 78102, 102258, 29854, 24486, 66610, 125155, 107545, 16582, 103373, 105954, 116283, 35859, 242, 39331, 13, 117078, 99901, 102772, 101480, 26799, 102079, 103153, 36155, 101, 11, 120295, 79225, 102662, 74959, 27796, 86503, 65895, 97096, 102662, 101824, 46810, 93917, 11, 72043, 98934, 103153, 36155, 101, 11, 116680, 120072, 21028, 104019, 14260, 103655, 104841, 101228, 124800, 78102, 13094, 110097, 33943, 238, 39331, 13, 112887, 86503, 82068, 102079, 103153, 36155, 101, 26799, 102244, 56773, 104727, 18359, 100994, 102662, 24486, 115888, 26799, 19954, 122115, 49085, 107849, 104366, 46810, 101738, 84618, 64189, 18918, 127614, 34983, 101254, 102133, 106593, 101603, 101096, 30381, 22035, 122733, 66610, 125155, 86422, 101665, 48936, 75908, 108308, 80052, 13, 117717, 66610, 116129, 56773, 104727, 79225, 102662, 119262, 21028, 102786, 101661, 14260, 100848, 103272, 101066, 121255, 103213, 101353, 101360, 120295, 79225, 102662, 63171, 120498, 100994, 30381, 33931, 54780, 104019, 14260, 103655, 104841, 18359, 102258, 57390, 122910, 16969, 103659, 103504, 82068, 13094, 103924, 48991, 31587, 1284, 26246, 9075, 29603, 31587, 52454, 9075, 29603, 31587, 39329, 82, 61867, 43324, 1284, 26246, 9075, 29603, 43324, 52454, 9075, 29603, 43324, 39329, 82, 63466, 92, 128009]
[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
[-100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, 5018, 13787, 54356, 794, 3934, 1359, 1743, 3332, 100654, 101665, 100848, 102233, 64189, 20565, 117078, 55421, 117078, 57575, 103607, 102133, 53400, 101852, 102757, 30426, 119444, 120072, 99458, 56154, 26799, 120295, 79225, 102662, 86503, 82068, 102079, 103153, 36155, 101, 26799, 220, 4767, 80732, 19954, 112107, 112024, 126951, 18918, 112521, 101464, 101709, 127614, 101360, 11, 46810, 101661, 115602, 74959, 65219, 33390, 120287, 107545, 44690, 14260, 55430, 104727, 104613, 24140, 14260, 102193, 56154, 35495, 102133, 78102, 102258, 29854, 24486, 66610, 125155, 107545, 16582, 103373, 105954, 116283, 35859, 242, 39331, 13, 117078, 99901, 102772, 101480, 26799, 102079, 103153, 36155, 101, 11, 120295, 79225, 102662, 74959, 27796, 86503, 65895, 97096, 102662, 101824, 46810, 93917, 11, 72043, 98934, 103153, 36155, 101, 11, 116680, 120072, 21028, 104019, 14260, 103655, 104841, 101228, 124800, 78102, 13094, 110097, 33943, 238, 39331, 13, 112887, 86503, 82068, 102079, 103153, 36155, 101, 26799, 102244, 56773, 104727, 18359, 100994, 102662, 24486, 115888, 26799, 19954, 122115, 49085, 107849, 104366, 46810, 101738, 84618, 64189, 18918, 127614, 34983, 101254, 102133, 106593, 101603, 101096, 30381, 22035, 122733, 66610, 125155, 86422, 101665, 48936, 75908, 108308, 80052, 13, 117717, 66610, 116129, 56773, 104727, 79225, 102662, 119262, 21028, 102786, 101661, 14260, 100848, 103272, 101066, 121255, 103213, 101353, 101360, 120295, 79225, 102662, 63171, 120498, 100994, 30381, 33931, 54780, 104019, 14260, 103655, 104841, 18359, 102258, 57390, 122910, 16969, 103659, 103504, 82068, 13094, 103924, 48991, 31587, 1284, 26246, 9075, 29603, 31587, 52454, 9075, 29603, 31587, 39329, 82, 61867, 43324, 1284, 26246, 9075, 29603, 43324, 52454, 9075, 29603, 43324, 39329, 82, 63466, 92, 128009]

In [16]:
# labels 에서 -100 제거한 후, assistant 정답 구간만 디코딩
label_ids = [token_id for token_id in batch['labels'][0].tolist() if token_id != -100]
text = tokenizer.decode(label_ids)
text

[transformers] Ignoring clean_up_tokenization_spaces=True for BPE tokenizer TokenizersBackend. The clean_up_tokenization post-processing step is designed for WordPiece tokenizers and is destructive for BPE (it strips spaces before punctuation). Set clean_up_tokenization_spaces=False to suppress this warning, or set clean_up_tokenization_spaces_for_bpe_even_though_it_will_corrupt_output=True to force cleanup anyway.

'{"stock_related":false,"summary":"국토교통부가 감사원 감사에서 적발된 세종시 이전기관 종사자 특별공급 부적격 당첨자 76명에 대해 사실관계를 철저히 조사하고, 위법성이 확인되면 계약 취소·주택 환수·형사고발 등 강력한 조치를 취하겠다고 밝혔습니다. 감사 결과에는 무자격 당첨, 특별공급 확인서 부당 발급 및 위조, 중복 당첨, 관계기관의 관리·감독 소홀 등이 포함됐습니다. 또한 부적격 당첨자에게 주택을 공급한 사업자에 대해서도 법령 위반 여부를 조사해 고발이나 영업정지 등의 조치를 검토할 방침입니다. 이번 조치는 주택공급 시장의 불법·교란행위를 차단하고 특별공급 제도의 공정성과 관리·감독을 강화하려는 데 목적이 있습니다.","positive_stocks":[],"positive_keywords":[],"positive_reasons":"","negative_stocks":[],"negative_keywords":[],"negative_reasons":""}<|eot_id|>'

In [17]:
# input_ids 를 토큰/문자 단위로 디코딩해서 확인
text_tokens = [] # 토큰 id를 디코딩한 문자열을 담을 리스트
for i, token_id in enumerate(batch['input_ids'][0].tolist()): # 토큰 ID 순회
    decoded_str = tokenizer.decode([token_id]) # 토큰 1개를 문자열로 디코딩
    text_tokens.append(decoded_str) # 디코딩 결과 누적
text_tokens

['<|begin_of_text|>',
 '<|start_header_id|>',
 'system',
 '<|end_header_id|>',
 '\n',
 '당',
 '신',
 '은',
 ' 금',
 '융',
 '/',
 '경제',
 ' 뉴',
 '스의',
 ' 핵',
 '심',
 '내',
 '용',
 '을',
 ' 요',
 '약',
 '해',
 ' 설명',
 '하고',
 ',\n',
 '특',
 '정',
 ' 상',
 '장',
 ' 종',
 '목',
 '에',
 ' 미',
 '치는',
 ' �',
 '�',
 '정',
 '/',
 '부',
 '정',
 ' 영향',
 '여',
 '부',
 ',',
 ' 이유',
 ',',
 ' 근',
 '거',
 '를',
 ' 분석',
 '하는',
 ' 금',
 '융',
 '/',
 '경제',
 ' 분석',
 ' 전문',
 '가',
 '입니다',
 '.\n\n',
 '다',
 '음',
 ' 출력',
 '지',
 '시',
 '사항',
 '을',
 ' 지',
 '켜',
 '주세요',
 '.\n',
 '1',
 '.',
 ' 뉴',
 '스',
 '와',
 ' 종',
 '목',
 '간',
 '의',
 ' 연',
 '관',
 '성을',
 ' 발견',
 '할',
 ' 수',
 ' 없',
 '다면',
 ':\n',
 '   ',
 ' -',
 ' stock',
 '_related',
 '를',
 ' False',
 '로',
 ' 작성',
 '하세요',
 '.\n',
 '   ',
 ' -',
 ' summary',
 '에',
 ' 뉴',
 '스의',
 ' 요',
 '약',
 '을',
 ' 작성',
 '하세요',
 '.\n',
 '2',
 '.',
 ' 뉴',
 '스',
 '와',
 ' 종',
 '목',
 '간',
 '의',
 ' 연',
 '관',
 '성을',
 ' 발견',
 '했다',
 '면',
 ':\n',
 '   ',
 ' -',
 ' stock',
 '_related',
 '를',
 ' True',
 '로',
 ' 작성',
 '하세요',
 '.\n',
 '   ',
 ' -',
 ' summary',
 '에',
 ' 뉴',
 '스의',
 ' 요',
 '약',
 '을',
 ' 작성',
 '하세요',
 '.\n',
 '   ',
 ' -',
 ' �',
 '�',
 '정',
 '영',
 '향',
 '이',
 ' 예',
 '상',
 '되는',
 ' 종',
 '목',
 '이',
 ' 있다',
 '면',
 ',',
 ' positive',
 '_st',
 'ocks',
 ',',
 ' positive',
 '_keywords',
 ',',
 ' positive',
 '_reason',
 's',
 '를',
 ' 작성',
 '하세요',
 '.\n',
 '   ',
 ' -',
 ' 부',
 '정',
 '영',
 '향',
 '이',
 ' 예',
 '상',
 '되는',
 ' 종',
 '목',
 '이',
 ' 있다',
 '면',
 ',',
 ' negative',
 '_st',
 'ocks',
 ',',
 ' negative',
 '_keywords',
 ',',
 ' negative',
 '_reason',
 's',
 '를',
 ' 작성',
 '하세요',
 '.\n',
 '   ',
 ' -',
 ' 값',
 '이',
 ' 없는',
 ' 경우',
 ' 빈',
 ' 문자',
 '열',
 "('",
 "'),",
 ' 빈',
 ' 리스트',
 '([]',
 ')',
 '로',
 ' 작성',
 '하세요',
 '.',
 '<|eot_id|>',
 '<|start_header_id|>',
 'user',
 '<|end_header_id|>',
 '\n',
 '국',
 '토',
 '부',
 ' 세',
 '종',
 '시',
 ' 부',
 '적',
 '격',
 ' 당',
 '�',
 '�',
 '자',
 ' 철',
 '저',
 '히',
 ' 조사',
 '해',
 ' 엄',
 '중',
 ' 조',
 '치',
 '\n',
 '원',
 '희',
 '룡',
 ' 계약',
 '취',
 '소',
 ' 및',
 ' 주',
 '택',
 '환',
 '수',
 ' 형',
 '사',
 '고',
 '발',
 '까지',
 ' 필요',
 ' 조',
 '치',
 ' 취',
 '할',
 ' 것',
 ' 원',
 '희',
 '룡',
 ' 국',
 '토',
 '교',
 '통',
 '부',
 ' 장',
 '관',
 '.',
 ' ',
 '202',
 '2',
 '.',
 '7',
 '.',
 '6',
 ' 뉴',
 '스',
 '1',
 ' ©',
 ' News',
 '1',
 ' 김',
 '명',
 '섭',
 ' 기자',
 ' 서울',
 ' 뉴',
 '스',
 '1',
 ' 박',
 '승',
 '희',
 ' 기자',
 ' 국',
 '토',
 '교',
 '통',
 '부',
 '는',
 ' 감사',
 '원',
 ' 감사',
 '에서',
 ' 세',
 '종',
 '시',
 ' 무',
 '자',
 '격',
 ' 특',
 '공',
 ' 당',
 '�',
 '�',
 '자가',
 ' 무',
 '더',
 '기로',
 ' 적',
 '발',
 '된',
 ' 것',
 '과',
 ' 관련',
 '해',
 ' 위',
 '법',
 '행',
 '위',
 ' 여',
 '부',
 '를',
 ' 철',
 '저',
 '히',
 ' 조사',
 '해',
 ' 위',
 '법',
 '성이',
 ' 밝',
 '혀',
 '지는',
 ' 경우',
 ' 엄',
 '중',
 '히',
 ' 조',
 '치',
 '할',
 ' 것',
 ' 이',
 '라고',
 ' ',
 '6',
 '일',
 ' 밝',
 '�',
 '�다',
 '.',
 ' 감사',
 '원',
 '은',
 ' 세',
 '종',
 '시',
 ' 이전',
 '기관',
 ' 종',
 '사',
 '자',
 ' 주',
 '택',
 ' 특별',
 '공',
 '급',
 '에',
 ' 대한',
 ' 감',
 '사를',
 ' 진행',
 '한',
 ' 결과',
 ' 총',
 ' ',
 '45',
 '건',
 ' ',
 '76',
 '명',
 ' 에',
 ' 대한',
 ' 감사',
 ' 결과',
 '를',
 ' 확',
 '정',
 '했다',
 '.',
 ' Δ',
 '대',
 '상',
 '관리',
 ' 부',
 '실',
 ' Δ',
 '�',
 '�인',
 '서',
 ' 부',
 '당',
 ' 발',
 '급',
 ' Δ',
 '�',
 '�인',
 '서',
 ' 위',
 '조',
 ' Δ',
 '중',
 '복',
 ' 당',
 '�',
 '�',
 ' Δ',
 '지도',
 '·',
 '감',
 '독',
 ' 소',
 '홀',
 ' 등',
 ' 사',
 '유',
 '로',
 ' 무',
 '자',
 '격',
 '자가',
 ' 대',
 '거',
 ' 당',
 '�',
 '�',
 '된',
 ' 것으로',
 ' 드',
 '러',
 '났다',
 '.',
 ' 국',
 '토',
 '부',
 '는',
 ' 감사',
 '원',
 '으로',
 '부터',
 ' 결과',
 '를',
 ' 통',
 '보',
 ' 받',
 '았',
 '으며',
 ' 이',
 '에',
 ' 따른',
 ' 후',
 '속',
 ' 조',
 '치를',
 ' 강',
 '도',
 ' 높',
 '게',
 ' 추',
 '진',
 '하',
 '겠',
 '다는',
 ' 입',
 '장',
 '이다',
 '.',
 ' 원',
 '희',
 '룡',
 ' 국',
 '토',
 '부',
 ' 장',
 '관',
 '은',
 ' �',
 '�은',
 ' 세',
 '대',
 '에게',
 ' 상대',
 '적',
 ' 박',
 '탈',
 '감',
 '을',
 ' 준',
 ' 부',
 '적',
 '격',
 ' 특별',
 '공',
 '급',
 '에',
 ' 대해',
 ' 철',
 '저',
 '히',
 ' 조사',
 '하고',
 ' 계약',
 '취',
 '소',
 ' 및',
 ' 주',
 '택',
 '환',
 '수',
 ' 형',
 '사',
 '고',
 '발',
 '까지',
 ' 필요한',
 ' 모든',
 ' 조',
 '치를',
 ' 취',
 '할',
 ' 것',
 ' 이',
 '라고',
 ' 강',
 '조',
 '했다',
 '.',
 ' 국',
 '토',
 '부',
 '는',
 ' 위',
 '법',
 '하게',
 ' 청',
 '약',
 '에',
 ' 당',
 '�',
 '�',
 '된',
 ' ',
 '76',
 '명',
 '에',
 ' 대해',
 ' 세',
 '종',
 '시에',
 ' 관련',
 ' 사실',
 ' 관계',
 '를',
 ' 파',
 '악',
 '하고',
 ' 계약',
 '을',
 ' 취',
 '소',
 '하',
 '거나',
 ' 주',
 '택',
 '을',
 ' 환',
 '수',
 '하',
 '도록',
 ' 조',
 '치',
 '할',
 ' 계획',
 '이다',
 '.',
 ' 지',
 '자',
 '체',
 ' 조',
 '치',
 '와',
 ' 별',
 '도로',
 ' 국',
 '토',
 '부',
 '에서',
 ' 법',
 '령',
 ' 위',
 '반',
 ' 여',
 '부',
 '를',
 ' 판',
 '단',
 '하고',
 ' 위',
 '법',
 '성이',
 ' 확인',
 '되',
 '면',
 ' 고',
 '발',
 ' 등',
 ' 조',
 '치',
 '한다',
 '.',
 ' 이',
 '에',
 ' 따라',
 ' ',
 '3',
 '년',
 ' 이',
 '하',
 '의',
 ' �',
 '�',
 '역',
 ' 또는',
 ' ',
 '300',
 '0',
 '만원',
 ' 이',
 '하',
 '의',
 ' 벌',
 '금',
 ' ',
 '500',
 '만원',
 ' 이',
 '하',
 '의',
 ' 과',
 '태',
 '료',
 '를',
 ' 부',
 '과',
 '할',
 ' 수',
 ' 있다',
 '.',
 ' 사업',
 '자가',
 ' 법',
 '령',
 '을',
 ' 위',
 '반',
 '해',
 ' 부',
 '적',
 '격',
 ' 당',
 '�',
 '�',
 '자',
 '에게',
 ' 주',
 '택',
 '을',
 ' 공',
 '급',
 '한',
 ' 경우',
 '에도',
 ' 국',
 '토',
 '부',
 '에서',
 ' 직접',
 ' 사실',
 '관계',
 '를',
 ' 조사',
 '한',
 ' 뒤',
 ' 위',
 '법',
 ' 여',
 '부',
 '를',
 ' 검',
 '토',
 '해',
 ' 고',
 '발',
 ' 등',
 ' 조',
 '치',
 '할',
 ' 방',
 '침',
 '이다',
 '.',
 ' 이',
 ' 경우',
 ' ',
 '3',
 '년',
 ' 이',
 '하',
 '의',
 ' �',
 '�',
 '역',
 ' 또는',
 ' ',
 '300',
 '0',
 '만원',
 ' 이',
 '하',
 '의',
 ' 벌',
 '금',
 ' 영',
 '업',
 '정',
 '지가',
 ' 가능',
 '하다',
 '.',
 ' 국',
 '토',
 '부',
 ' 관계',
 '자는',
 ' 주',
 '택',
 '공',
 '급',
 '을',
 ' 총',
 '�',
 '�',
 '·',
 '감',
 '독',
 '하는',
 ' 부',
 '처',
 '로서',
 ' 책',
 '임',
 '감',
 '을',
 ' 갖',
 '고',
 ' 앞',
 '으로',
 ' 공',
 '급',
 '시',
 '장',
 ' 교',
 '란',
 '행',
 '위',
 ' 등',
 '이',
 ' 발생',
 '하지',
 ' 않',
 '도록',
 ' 불',
 '법',
 '행',
 '위',
 ' 점',
 '검',
 '을',
 ' 강',
 '화',
 '하는',
 ' 한',
 '편',
 ' 관련',
 ' 제',
 '도',
 ' 운영',
 '에',
 ' 만',
 '전',
 '을',
 ' 기',
 '할',
 ' 것',
 ' 이',
 '라고',
 ' 말했다',
 '.',
 '<|eot_id|>',
 '<|start_header_id|>',
 'assistant',
 '<|end_header_id|>',
 '\n',
 '{"',
 'stock',
 '_related',
 '":',
 'false',
 ',"',
 'summary',
 '":"',
 '국',
 '토',
 '교',
 '통',
 '부',
 '가',
 ' 감사',
 '원',
 ' 감사',
 '에서',
 ' 적',
 '발',
 '된',
 ' 세',
 '종',
 '시',
 ' 이전',
 '기관',
 ' 종',
 '사',
 '자',
 ' 특별',
 '공',
 '급',
 ' 부',
 '적',
 '격',
 ' 당',
 '�',
 '�',
 '자',
 ' ',
 '76',
 '명',
 '에',
 ' 대해',
 ' 사실',
 '관계',
 '를',
 ' 철',
 '저',
 '히',
 ' 조사',
 '하고',
 ',',
 ' 위',
 '법',
 '성이',
 ' 확인',
 '되',
 '면',
 ' 계약',
 ' 취',
 '소',
 '·',
 '주',
 '택',
 ' 환',
 '수',
 '·',
 '형',
 '사',
 '고',
 '발',
 ' 등',
 ' 강',
 '력',
 '한',
 ' 조',
 '치를',
 ' 취',
 '하',
 '겠',
 '다고',
 ' 밝',
 '�',
 '�',
 '습니다',
 '.',
 ' 감사',
 ' 결과',
 '에는',
 ' 무',
 '자',
 '격',
 ' 당',
 '�',
 '�',
 ',',
 ' 특별',
 '공',
 '급',
 ' 확인',
 '서',
 ' 부',
 '당',
 ' 발',
 '급',
 ' 및',
 ' 위',
 '조',
 ',',
 ' 중',
 '복',
 ' 당',
 '�',
 '�',
 ',',
 ' 관계',
 '기관',
 '의',
 ' 관리',
 '·',
 '감',
 '독',
 ' 소',
 '홀',
 ' 등',
 '이',
 ' 포함',
 '�',
 '�',
 '습니다',
 '.',
 ' 또한',
 ' 부',
 '적',
 '격',
 ' 당',
 '�',
 '�',
 '자',
 '에게',
 ' 주',
 '택',
 '을',
 ' 공',
 '급',
 '한',
 ' 사업',
 '자',
 '에',
 ' 대해서',
 '도',
 ' 법',
 '령',
 ' 위',
 '반',
 ...]

In [18]:
# 데이터프레임 시각화

import pandas as pd

df = pd.DataFrame({
    'token':text_tokens, # 토큰 (디코딩된 문자열)
    'input_ids' : batch['input_ids'][0].tolist(), # 입력 토큰 ID
    'attention_mask' : batch['attention_mask'][0].tolist(), # 패딩 여부(1/0)
    'labels':batch['labels'][0].tolist() # 정답 라벨 (마스킹: -100)
}).transpose()

pd.set_option('display.max_columns', None) # 컬럼 생략 없음
df

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,241,242,243,244,245,246,247,248,249,250,251,252,253,254,255,256,257,258,259,260,261,262,263,264,265,266,267,268,269,270,271,272,273,274,275,276,277,278,279,280,281,282,283,284,285,286,287,288,289,290,291,292,293,294,295,296,297,298,299,300,301,302,303,304,305,306,307,308,309,310,311,312,313,314,315,316,317,318,319,320,321,322,323,324,325,326,327,328,329,330,331,332,333,334,335,336,337,338,339,340,341,342,343,344,345,346,347,348,349,350,351,352,353,354,355,356,357,358,359,360,361,362,363,364,365,366,367,368,369,370,371,372,373,374,375,376,377,378,379,380,381,382,383,384,385,386,387,388,389,390,391,392,393,394,395,396,397,398,399,400,401,402,403,404,405,406,407,408,409,410,411,412,413,414,415,416,417,418,419,420,421,422,423,424,425,426,427,428,429,430,431,432,433,434,435,436,437,438,439,440,441,442,443,444,445,446,447,448,449,450,451,452,453,454,455,456,457,458,459,460,461,462,463,464,465,466,467,468,469,470,471,472,473,474,475,476,477,478,479,480,481,482,483,484,485,486,487,488,489,490,491,492,493,494,495,496,497,498,499,500,501,502,503,504,505,506,507,508,509,510,511,512,513,514,515,516,517,518,519,520,521,522,523,524,525,526,527,528,529,530,531,532,533,534,535,536,537,538,539,540,541,542,543,544,545,546,547,548,549,550,551,552,553,554,555,556,557,558,559,560,561,562,563,564,565,566,567,568,569,570,571,572,573,574,575,576,577,578,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,597,598,599,600,601,602,603,604,605,606,607,608,609,610,611,612,613,614,615,616,617,618,619,620,621,622,623,624,625,626,627,628,629,630,631,632,633,634,635,636,637,638,639,640,641,642,643,644,645,646,647,648,649,650,651,652,653,654,655,656,657,658,659,660,661,662,663,664,665,666,667,668,669,670,671,672,673,674,675,676,677,678,679,680,681,682,683,684,685,686,687,688,689,690,691,692,693,694,695,696,697,698,699,700,701,702,703,704,705,706,707,708,709,710,711,712,713,714,715,716,717,718,719,720,721,722,723,724,725,726,727,728,729,730,731,732,733,734,735,736,737,738,739,740,741,742,743,744,745,746,747,748,749,750,751,752,753,754,755,756,757,758,759,760,761,762,763,764,765,766,767,768,769,770,771,772,773,774,775,776,777,778,779,780,781,782,783,784,785,786,787,788,789,790,791,792,793,794,795,796,797,798,799,800,801,802,803,804,805,806,807,808,809,810,811,812,813,814,815,816,817,818,819,820,821,822,823,824,825,826,827,828,829,830,831,832,833,834,835,836,837,838,839,840,841,842,843,844,845,846,847,848,849,850,851,852,853,854,855,856,857,858,859,860,861,862,863,864,865,866,867,868,869,870,871,872,873,874,875,876,877,878,879,880,881,882,883,884,885,886,887,888,889,890,891,892,893,894,895,896,897,898,899,900,901,902,903,904,905,906,907,908,909,910,911,912,913,914,915,916,917,918,919,920,921,922,923,924,925,926,927,928,929,930,931,932,933,934,935,936,937,938,939,940,941,942,943,944,945,946,947,948,949,950,951,952,953,954,955,956,957,958,959,960,961,962,963,964,965,966,967,968,969,970,971,972,973,974,975,976,977,978,979,980,981,982,983,984,985,986,987,988,989,990,991,992,993,994,995,996,997,998,999,1000,1001,1002,1003,1004,1005,1006,1007,1008,1009,1010,1011,1012,1013,1014,1015,1016,1017,1018,1019,1020,1021,1022,1023,1024,1025,1026,1027,1028,1029,1030,1031,1032,1033,1034,1035,1036,1037,1038,1039,1040,1041,1042,1043,1044,1045,1046,1047,1048,1049,1050,1051,1052,1053,1054,1055,1056,1057,1058,1059,1060,1061,1062,1063,1064,1065,1066,1067,1068,1069,1070,1071,1072,1073,1074,1075,1076,1077,1078,1079,1080,1081,1082,1083,1084,1085,1086,1087,1088,1089,1090,1091,1092
token,<|begin_of_text|>,<|start_header_id|>,system,<|end_header_id|>,\n,당,신,은,금,융,/,경제,뉴,스의,핵,심,내,용,을,요,약,해,설명,하고,",\n",특,정,상,장,종,목,에,미,치는,�,�,정,/,부,정,영향,여,부,",",이유,",",근,거,를,분석,하는,금,융,/,경제,분석,전문,가,입니다,.\n\n,다,음,출력,지,시,사항,을,지,켜,주세요,.\n,1,.,뉴,스,와,종,목,간,의,연,관,성을,발견,할,수,없,다면,:\n,,-,stock,_related,를,False,로,작성,하세요,.\n,,-,summary,에,뉴,스의,요,약,을,작성,하세요,.\n,2,.,뉴,스,와,종,목,간,의,연,관,성을,발견,했다,면,:\n,,-,stock,_related,를,True,로,작성,하세요,.\n,,-,summary,에,뉴,스의,요,약,을,작성,하세요,.\n,,-,�,�,정,영,향,이,예,상,되는,종,목,이,있다,면,",",positive,_st,ocks,",",positive,_keywords,",",positive,_reason,s,를,작성,하세요,.\n,,-,부,정,영,향,이,예,상,되는,종,목,이,있다,면,",",negative,_st,ocks,",",negative,_keywords,",",negative,_reason,s,를,작성,하세요,.\n,,-,값,이,없는,경우,빈,문자,열,(',"'),",빈,리스트,([],),로,작성,하세요,.,<|eot_id|>,<|start_header_id|>,user,<|end_header_id|>,\n,국,토,부,세,종,시,부,적,격,당,�,�,자,철,저,히,조사,해,엄,중,조,치,\n,원,희,룡,계약,취,소,및,주,택,환,수,형,사,고,발,까지,필요,조,치,취,할,것,원,희,룡,국,토,교,통,부,장,관,.,,202,2,.,7,.,6,뉴,스,1,©,News,1,김,명,섭,기자,서울,뉴,스,1,박,승,희,기자,국,토,교,통,부,는,감사,원,감사,에서,세,종,시,무,자,격,특,공,당,�,�,자가,무,더,기로,적,발,된,것,과,관련,해,위,법,행,위,여,부,를,철,저,히,조사,해,위,법,성이,밝,혀,지는,경우,엄,중,히,조,치,할,것,이,라고,,6,일,밝,�,�다,.,감사,원,은,세,종,시,이전,기관,종,사,자,주,택,특별,공,급,에,대한,감,사를,진행,한,결과,총,,45,건,,76,명,에,대한,감사,결과,를,확,정,했다,.,Δ,대,상,관리,부,실,Δ,�,�인,서,부,당,발,급,Δ,�,�인,서,위,조,Δ,중,복,당,�,�,Δ,지도,·,감,독,소,홀,등,사,유,로,무,자,격,자가,대,거,당,�,�,된,것으로,드,러,났다,.,국,토,부,는,감사,원,으로,부터,결과,를,통,보,받,았,으며,이,에,따른,후,속,조,치를,강,도,높,게,추,진,하,겠,다는,입,장,이다,.,원,희,룡,국,토,부,장,관,은,�,�은,세,대,에게,상대,적,박,탈,감,을,준,부,적,격,특별,공,급,에,대해,철,저,히,조사,하고,계약,취,소,및,주,택,환,수,형,사,고,발,까지,필요한,모든,조,치를,취,할,것,이,라고,강,조,했다,.,국,토,부,는,위,법,하게,청,약,에,당,�,�,된,,76,명,에,대해,세,종,시에,관련,사실,관계,를,파,악,하고,계약,을,취,소,하,거나,주,택,을,환,수,하,도록,조,치,할,계획,이다,.,지,자,체,조,치,와,별,도로,국,토,부,에서,법,령,위,반,여,부,를,판,단,하고,위,법,성이,확인,되,면,고,발,등,조,치,한다,.,이,에,따라,,3,년,이,하,의,�,�,역,또는,,300,0,만원,이,하,의,벌,금,,500,만원,이,하,의,과,태,료,를,부,과,할,수,있다,.,사업,자가,법,령,을,위,반,해,부,적,격,당,�,�,자,에게,주,택,을,공,급,한,경우,에도,국,토,부,에서,직접,사실,관계,를,조사,한,뒤,위,법,여,부,를,검,토,해,고,발,등,조,치,할,방,침,이다,.,이,경우,,3,년,이,하,의,�,�,역,또는,,300,0,만원,이,하,의,벌,금,영,업,정,지가,가능,하다,.,국,토,부,관계,자는,주,택,공,급,을,총,�,�,·,감,독,하는,부,처,로서,책,임,감,을,갖,고,앞,으로,공,급,시,장,교,란,행,위,등,이,발생,하지,않,도록,불,법,행,위,점,검,을,강,화,하는,한,편,관련,제,도,운영,에,만,전,을,기,할,것,이,라고,말했다,.,<|eot_id|>,<|start_header_id|>,assistant,<|end_header_id|>,\n,"{""",stock,_related,""":",false,",""",summary,""":""",국,토,교,통,부,가,감사,원,감사,에서,적,발,된,세,종,시,이전,기관,종,사,자,특별,공,급,부,적,격,당,�,�,자,,76,명,에,대해,사실,관계,를,철,저,히,조사,하고,",",위,법,성이,확인,되,면,계약,취,소,·,주,택,환,수,·,형,사,고,발,등,강,력,한,조,치를,취,하,겠,다고,밝,�,�,습니다,.,감사,결과,에는,무,자,격,당,�,�,",",특별,공,급,확인,서,부,당,발,급,및,위,조,",",중,복,당,�,�,",",관계,기관,의,관리,·,감,독,소,홀,등,이,포함,�,�,습니다,.,또한,부,적,격,당,�,�,자,에게,주,택,을,공,급,한,사업,자,에,대해서,도,법,령,위,반,여,부,를,조사,해,고,발,이나,영,업,정,지,등의,조,치를,검,토,할,방,침,입니다,.,이번,조,치는,주,택,공,급,시장,의,불,법,·,교,란,행,위를,차,단,하고,특별,공,급,제,도의,공,정,성,과,관리,·,감,독,을,강,화,하려,는,데,목,적,이,있습니다,"."",""",positive,_st,ocks,""":[","],""",positive,_keywords,""":[","],""",positive,_reason,s,""":"""",""",negative,_st,ocks,""":[","],""",negative,_keywords,""":[","],""",negative,_reason,s,""":""""",},<|eot_id|>
input_ids,128000,128006,9125,128007,198,65895,83628,34804,104193,123061,14,127463,111068,120226,125959,102612,96318,27797,18359,87097,103168,34983,114942,101360,345,108159,30381,59134,41953,99458,88708,19954,101412,116129,41871,235,30381,14,64189,30381,115754,58126,64189,11,111436,11,106589,93292,18918,109862,44005,104193,123061,14,127463,109862,116425,20565,80052,382,13447,49531,62226,22035,30426,115790,18359,67890,115061,92769,627,16,13,111068,25941,81673,99458,88708,63375,21028,78453,101106,111490,121712,48936,29833,47782,115300,512,262,482,5708,54356,18918,3641,17835,114839,92245,627,262,482,12399,19954,111068,120226,87097,103168,18359,114839,92245,627,17,13,111068,25941,81673,99458,88708,63375,21028,78453,101106,111490,121712,101528,33390,512,262,482,5708,54356,18918,3082,17835,114839,92245,627,262,482,12399,19954,111068,120226,87097,103168,18359,114839,92245,627,262,482,41871,235,30381,101090,104762,13094,96717,57002,107205,99458,88708,13094,91786,33390,11,6928,1284,26246,11,6928,52454,11,6928,39329,82,18918,114839,92245,627,262,482,86503,30381,101090,104762,13094,96717,57002,107205,99458,88708,13094,91786,33390,11,8389,1284,26246,11,8389,52454,11,8389,39329,82,18918,114839,92245,627,262,482,46663,13094,108838,50152,122292,81021,55055,493,4670,122292,84734,10779,8,17835,114839,92245,13,128009,128006,882,128007,198,100654,101665,64189,101852,102757,30426,86503,82068,102079,103153,36155,101,26799,112521,101464,101709,127614,34983,112190,101711,66610,60798,198,55421,105204,126963,120287,114039,44690,101824,56773,104727,66338,24140,106612,56154,35495,102133,102704,108289,66610,60798,107545,48936,72208,102467,105204,126963,102160,101665,100848,102233,64189,102027,101106,13,220,2366,17,13,22,13,21,111068,25941,16,7388,5513,16,102155,80732,123894,126887,106010,111068,25941,16,104293,104303,105204,126887,102160,101665,100848,102233,64189,16969,117078,55421,117078,57575,101852,102757,30426,101480,26799,102079,103966,79225,103153,36155,101,108181,101480,102913,122211,103607,102133,53400,72208,54780,106434,34983,46810,101661,101066,82001,84618,64189,18918,112521,101464,101709,127614,34983,46810,101661,115602,116283,113048,107054,50152,112190,101711,101709,66610,60798,48936,72208,23955,105771,220,21,33177,116283,35859,104828,13,117078,55421,34804,101852,102757,30426,119444,120072,99458,56154,26799,56773,104727,120295,79225,102662,19954,102597,103185,111636,111809,24486,99901,107152,220,1774,101868,220,4767,80732,91586,102597,117078,99901,18918,103686,30381,101528,13,82263,67945,57002,106974,86503,101272,82263,34693,67361,27796,86503,65895,97096,102662,82263,34693,67361,27796,46810,93917,82263,101711,98934,103153,36155,101,82263,113037,14260,103655,104841,101228,124800,78102,33229,101314,17835,101480,26799,102079,108181,62060,93292,103153,36155,101,53400,111590,103745,61394,118436,13,102160,101665,64189,16969,117078,55421,43139,103551,99901,18918,102681,42771,84696,101760,104429,23955,19954,122453,95415,102130,66610,125155,102258,49085,108499,58901,58935,86351,16582,103373,105453,39250,41953,101568,13,102467,105204,126963,102160,101665,64189,102027,101106,34804,19097,123143,101852,67945,102244,126761,82068,104293,110517,103655,18359,108683,86503,82068,102079,120295,79225,102662,19954,112107,112521,101464,101709,127614,101360,120287,114039,44690,101824,56773,104727,66338,24140,106612,56154,35495,102133,102704,126168,107036,66610,125155,107545,48936,72208,23955,105771,102258,93917,101528,13,102160,101665,64189,16969,46810,101661,102893,105519,103168,19954,103153,36155,101,53400,220,4767,80732,19954,112107,101852,102757,118472,106434,112024,116680,18918,56069,106356,101360,120287,18359,107545,44690,16582,109745,56773,104727,18359,104613,24140,16582,108438,66610,60798,48936,119623,101568,13,67890,26799,50643,66610,60798,81673,110192,116353,102160,101665,64189,57575,107849,104366,46810,101738,84618,64189,18918,106478,101353,101360,46810,101661,115602,74959,65219,33390,101254,102133,78102,66610,60798,52976,13,23955,19954,106725,220,18,100392,23955,16582,21028,49011,243,101577,108520,220,3101,15,106115,23955,16582,21028,112734,101136,220,2636,106115,23955,16582,21028,104219,87472,64356,18918,86503,54780,48936,29833,91786,13,115888,108181,107849,104366,18359,46810,101738,34983,86503,82068,102079,103153,36155,101,26799,102244,56773,104727,18359,100994,102662,24486,50152,109018,102160,101665,64189,57575,120307,112024,126951,18918,127614,24486,107333,46810,101661,84618,64189,18918,86422,101665,34983,101254,102133,78102,66610,60798,48936,75908,108308,101568,13,23955,50152,220,18,100392,23955,16582,21028,49011,243,101577,108520,220,3101,15,106115,23955,16582,21028,112734,101136,101603,101096,30381,122877,96451,108907,13,102160,101665,64189,116680,112953,56773,104727,79225,102662,18359,107152,117484,226,14260,103655,104841,44005,86503,102657,121803,110080,94801,103655,18359,116253,35495,107758,43139,100994,102662,30426,41953,101999,103272,101066,82001,78102,13094,113610,88525,51796,108438,102786,101661,101066,82001,106313,109070,18359,102258,57390,44005,62398,104790,106434,63171,49085,107065,19954,63207,66965,18359,55216,48936,72208,23955,105771,108537,13,128009,128006,78191,128007,198,5018,13787,54356,794,3934,1359,1743,3332,100654,101665,100848,102233,64189,20565,117078,55421,117078,57575,103607,102133,53400,101852,102757,30426,119444,120072,99458,56154,26799,120295,79225,102662,86503,82068,102079,103153,36155,101,26799,220,4767,80732,19954,112107,112024,126951,18918,112521,101464,101709,127614,101360,11,46810,101661,115602,74959,65219,33390,120287,107545,44690,14260,55430,104727,104613,24140,14260,102193,56154,35495,102133,78102,102258,29854,24486,66610,125155,107545,16582,103373,105954,116283,35859,242,39331,13,117078,99901,102772,101480,26799,102079,103153,36155,101,11,120295,79225,102662,74959,27796,86503,65895,97096,102662,101824,46810,93917,11,72043,98934,103153,36155,101,11,116680,120072,21028,104019,14260,103655,104841,101228,124800,78102,13094,110097,33943,238,39331,13,112887,86503,82068,102079,103153,36155,101,26799,102244,56773,104727,18359,100994,102662,24486,115888,26799,19954,122115,49085,107849,104366,46810,101738,84618,64189,18918,127614,34983,101254,102133,106593,101603,101096,30381,22035,122733,66610,125155,86422,101665,48936,75908,108308,80052,13,117717,66610,116129,56773,104727,79225,102662,119262,21028,102786,101661,14260,100848,103272,101066,121255,103213,101353,101360,120295,79225,102662,63171,120498,100994,30381,33931,54780,104019,14260,103655,104841,18359,102258,57390,122910,16969,103659,103504,82068,13094,103924,48991,31587,1284,26246,9075,29603,31587,52454,9075,29603,31587,39329,82,61867,43324,1284,26246,9075,29603,43324,52454,9075,29603,43324,39329,82,63466,92,128009
attention_mask,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1

## PEFT Finetuning - LoRA

* LoRA는 **"Low-Rank Adapter(저랭크 어댑터)"**
* 거대한 대형언어모델(LLM)의 **전체 파라미터를 일일이 미세조정(파인튜닝)하지 않고**,
  **딱 필요한 핵심 부분만 저렴하게 빠르게 학습**하는 최신 파인튜닝.
* **"LLM의 성능은 그대로, 비용/시간/메모리/유지보수는 최소로"** 파인튜닝을 할 수 있게 해주는 AI 실무에서 가장 중요한 기법 중 하나이다.

**왜 LoRA가 등장했을까?**

* GPT, Llama, DeepSeek 같은 대형언어모델은 **파라미터(매개변수) 수가 수십억\~수조 개**나 된다.
* 이런 모델을 파인튜닝하려면 **막대한 GPU 메모리와 시간, 저장 공간**이 필요.
* 하지만, 실제로 특정 태스크에 맞게 모델을 조정할 때 **전체를 다 바꿀 필요가 없다.**
* 대부분의 정보는 기존 모델에 이미 들어있고,
  **특정 입력(질문)과 특정 출력(답변)의 관계만 살짝 조정**해주면 충분하다.

**LoRA의 원리**

* 기존 대형 모델의 핵심 연산(주로 "곱셈" 부분)에
  **작고 얇은 "보조 네트워크(어댑터 레이어)"**를 덧붙인다.
* 전체 모델은 거의 건드리지 않고,
  **이 어댑터 레이어의 파라미터만 새로 추가해서 학습**
* 학습이 끝나면,

  * 원본 모델은 그대로
  * 어댑터(작은 추가 파라미터)만 별도로 저장하면 끝!
* 추론할 땐 **원본 모델 + LoRA 어댑터**를 합쳐서 쓸 수 있다.

**LoRA의 장점**

* **파인튜닝 비용(시간, 메모리, 저장 용량)이 압도적으로 절약**된다.
* 7B, 13B, 70B 등 대형 모델도
  **일반 GPU(24GB/48GB)로도 쉽게 파인튜닝**이 가능하다.
* **동일한 원본 모델에 다양한 LoRA 어댑터만 바꿔 끼우며
  다양한 분야별 파인튜닝 결과를 쉽게 쓸 수 있다.**

**LoRA와 기존 방식의 비교**

* **기존 파인튜닝:**
  전체 파라미터(수십\~수백 GB)를 새로 저장/관리/학습 → 비효율적
* **LoRA:**
  원본은 그대로 두고,
  변화가 필요한 부분(수 MB\~수십 MB)만 별도로 학습/저장


**실전에서의 활용 예시**

* 번역 LoRA, 요약 LoRA, 감정분석 LoRA 등
  **하나의 원본 모델에 여러 용도별 어댑터를 저장/관리**할 수 있다.
* **A100 80GB, 3090, T4 등 다양한 GPU 환경에서도
  고성능 LLM 튜닝이 매우 쉽게 가능하다.**

In [19]:
# LoRA 설정 적용 후 학습 가능한 파라미터(Trainable) 확인
from peft import LoraConfig, get_peft_model # LoRA 설정 / 적용 함수

lora_config = LoraConfig(
    r = 8,              # 저랭크 행렬 rank
    lora_alpha=32,      # LoRA 스케일 계수 (alpha/r)
    lora_dropout=0.1,
    bias = "none",      # bias 학습 제외
    target_modules=['q_proj', 'v_proj'], # LoRA 를 주입할 모듈 (Q/V Projection)
    task_type = "CAUSAL_LM" # 작업 유형: 생성형
)

model = get_peft_model(model, lora_config) # 기존 모델에 LoRA 어댑터 적용
model.print_trainable_parameters() # 학습 가능한 파라미터 수 (비율)

trainable params: 3,407,872 || all params: 8,033,669,120 || trainable%: 0.0424

In [20]:
from trl import SFTConfig  # TRL SFT 학습 설정 클래스

hub_model_id = 'kkkfu/Llama-VARCO-8b-news2stock-analyzer'  # 학습 완료 후 업로드할 Hub 모델 ID

sft_config = SFTConfig(  # SFT 학습 하이퍼파라미터/저장/로그 설정
    output_dir="Llama-VARCO-8b-news2stock-analyzer", # 학습 완료된 모델과 체크포인트가 저장될 경로이다.
    num_train_epochs=3,                              # 전체 데이터셋을 반복 학습할 횟수(Epoch)이다.
    per_device_train_batch_size=2,                   # 각 GPU(장치)당 한 번에 처리할 데이터 샘플의 개수이다.
    gradient_accumulation_steps=2,                   # 그래디언트를 2번 누적한 후 가중치를 업데이트한다. (실제 배치 크기 = 2 * 2 = 4 효과를 낸다.)
    gradient_checkpointing=True,                     # VRAM 절약을 위해 중간 활성화 값을 저장하지 않고 역전파 시 재계산하는 설정이다.
    optim="adamw_torch_fused",                       # 최적화 알고리즘 설정이다. fused 버전은 CUDA에서 더 빠르다.
    logging_steps=10,                                # 10 스텝마다 학습 로그(Loss 등)를 출력한다.
    save_strategy="steps",                           # 체크포인트 저장 기준을 'steps'(스텝 수)로 설정한다. (옵션: 'epoch')
    save_steps=50,                                   # 50 스텝마다 모델 체크포인트를 저장한다.
    bf16=True,                                       # BF16(Brain Float 16) 정밀도를 사용하여 메모리를 아끼고 연산 속도를 높인다. (Ampere GPU 이상 권장)
    learning_rate=1e-4,                              # 학습률(Learning Rate)이다. 가중치 업데이트의 크기를 결정한다.
    max_grad_norm=0.3,                               # 그래디언트 클리핑 임계값이다. 그래디언트 폭주를 막아 학습 안정성을 높인다.
    warmup_steps=0.03,                               # 전체 학습 단계의 3% 동안 학습률을 서서히 올리는 웜업(Warmup)을 수행한다.
    lr_scheduler_type="constant_with_warmup",        # 학습률 스케줄러 타입이다. 여기서는 학습률을 변동 없이 상수로 유지한다.
    push_to_hub=True,                                # 학습이 끝나면 Hugging Face Hub에 모델을 자동으로 업로드한다.
    hub_model_id=hub_model_id,                       # Hub에 업로드될 때 사용될 저장소(Repository) ID이다.
    hub_token=True,                                  # Hub 업로드를 위해 인증 토큰을 사용한다.
    remove_unused_columns=False,                     # 데이터셋에서 모델의 forward 메서드 시그니처에 없는 컬럼을 자동으로 삭제하지 않도록 한다.
    dataset_kwargs={"skip_prepare_dataset": True},   # 데이터셋 처리 과정(packing 등)을 건너뛰도록 하는 설정이다.
    report_to=['wandb'],                               # 학습 기록을 전송할 툴(WandB, Tensorboard 등)을 지정한다. 빈 리스트는 기록하지 않음을 의미한다.
    label_names=["labels"],                          # 손실(Loss) 계산 시 정답(Target)으로 사용할 데이터셋의 컬럼 이름이다.
    loss_type="nll"                                  # chunked_nll 비활성화 한다
)

In [21]:
from trl import SFTTrainer # SFT 학습용 Trainer

trainer = SFTTrainer(
    model = model,                   # LoRA 적용된 학습 모델
    args = sft_config,               # SFT 학습 설정
    train_dataset = train_dataset,   # 학습 데이터 셋
    data_collator = data_collator    # 배치 텐서 생성 함수 
)

trainer.train() # 학습 실행

[transformers] The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'eos_token_id': 128009, 'pad_token_id': 0}.
wandb: (1) Create a W&B account
wandb: (2) Use an existing W&B account
wandb: (3) Don't visualize my results

wandb: Enter your choice:  1

wandb: You chose 'Create a W&B account'
wandb: Create an account here: https://wandb.ai/authorize?signup=true&ref=models
wandb: After creating your account, create a new API key and store it securely.

wandb: Paste your API key and hit enter:  ········

wandb: No netrc file found, creating one.
wandb: Appending key for api.wandb.ai to your netrc file: /root/.netrc
wandb: Currently logged in as: free-rjs103 (free-rjs103-palydata) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin

torch.Size([1, 2112])
[128006, 78191, 128007, 198]
[128009]
0: 1614 ~ 2112
torch.Size([1, 1898])
[128006, 78191, 128007, 198]
[128009]
0: 1106 ~ 1898
torch.Size([1, 1017])
[128006, 78191, 128007, 198]
[128009]
0: 562 ~ 1017

torch.Size([1, 1075])
[128006, 78191, 128007, 198]
[128009]
0: 738 ~ 1075
torch.Size([1, 853])
[128006, 78191, 128007, 198]
[128009]
0: 633 ~ 853
torch.Size([1, 2243])
[128006, 78191, 128007, 198]
[128009]
0: 1612 ~ 2243
torch.Size([1, 1576])
[128006, 78191, 128007, 198]
[128009]
0: 1288 ~ 1576
torch.Size([1, 2121])
[128006, 78191, 128007, 198]
[128009]
0: 1398 ~ 2121
torch.Size([1, 649])
[128006, 78191, 128007, 198]
[128009]
0: 328 ~ 649
torch.Size([1, 645])
[128006, 78191, 128007, 198]
[128009]
0: 333 ~ 645
torch.Size([1, 1519])
[128006, 78191, 128007, 198]
[128009]
0: 963 ~ 1519
torch.Size([1, 1281])
[128006, 78191, 128007, 198]
[128009]
0: 862 ~ 1281
torch.Size([1, 1318])
[128006, 78191, 128007, 198]
[128009]
0: 825 ~ 1318
torch.Size([1, 4821])
[128006, 78191, 128007, 198]
[128009]
0: 4047 ~ 4821
torch.Size([1, 1786])
[128006, 78191, 128007, 198]
[128009]
0: 1224 ~ 1786
torch.Size([1, 1194])
[128006, 78191, 128007, 198]
[128009]
0: 967 ~ 1194
torch.Size([1, 1065])
[128006, 78191, 128007, 198]
[128009]
0: 509 ~ 1065
torch.Size([1, 1289])
[128006, 78191, 128007, 198]
[128009]
0: 857 ~ 1289
torch.Size([1, 1071])
[128006, 78191, 128007, 198]
[128009]
0: 639 ~ 1071
torch.Size([1, 1669])
[128006, 78191, 128007, 198]
[128009]
0: 1216 ~ 1669
torch.Size([1, 751])
[128006, 78191, 128007, 198]
[128009]
0: 386 ~ 751
torch.Size([1, 695])
[128006, 78191, 128007, 198]
[128009]
0: 428 ~ 695
torch.Size([1, 1638])
[128006, 78191, 128007, 198]
[128009]
0: 1044 ~ 1638
torch.Size([1, 1198])
[128006, 78191, 128007, 198]
[128009]
0: 723 ~ 1198
torch.Size([1, 1405])
[128006, 78191, 128007, 198]
[128009]
0: 714 ~ 1405
torch.Size([1, 1485])
[128006, 78191, 128007, 198]
[128009]
0: 820 ~ 1485
torch.Size([1, 1167])
[128006, 78191, 128007, 198]
[128009]
0: 757 ~ 1167
torch.Size([1, 1710])
[128006, 78191, 128007, 198]
[128009]
0: 1209 ~ 1710
torch.Size([1, 1288])
[128006, 78191, 128007, 198]
[128009]
0: 776 ~ 1288
torch.Size([1, 946])
[128006, 78191, 128007, 198]
[128009]
0: 703 ~ 946
torch.Size([1, 1108])
[128006, 78191, 128007, 198]
[128009]
0: 663 ~ 1108
torch.Size([1, 804])
[128006, 78191, 128007, 198]
[128009]
0: 396 ~ 804
torch.Size([1, 1085])
[128006, 78191, 128007, 198]
[128009]
0: 624 ~ 1085
torch.Size([1, 1857])
[128006, 78191, 128007, 198]
[128009]
0: 1242 ~ 1857
torch.Size([1, 810])
[128006, 78191, 128007, 198]
[128009]
0: 343 ~ 810
torch.Size([1, 1221])
[128006, 78191, 128007, 198]
[128009]
0: 815 ~ 1221
torch.Size([1, 582])
[128006, 78191, 128007, 198]
[128009]
0: 298 ~ 582
torch.Size([1, 1418])
[128006, 78191, 128007, 198]
[128009]
0: 790 ~ 1418
torch.Size([1, 1138])
[128006, 78191, 128007, 198]
[128009]
0: 674 ~ 1138
torch.Size([1, 1445])
[128006, 78191, 128007, 198]
[128009]
0: 1113 ~ 1445
torch.Size([1, 2025])
[128006, 78191, 128007, 198]
[128009]
0: 1385 ~ 2025
torch.Size([1, 1428])
[128006, 78191, 128007, 198]
[128009]
0: 849 ~ 1428
torch.Size([1, 1241])
[128006, 78191, 128007, 198]
[128009]
0: 701 ~ 1241
torch.Size([1, 1495])
[128006, 78191, 128007, 198]
[128009]
0: 928 ~ 1495
torch.Size([1, 1432])
[128006, 78191, 128007, 198]
[128009]
0: 1177 ~ 1432
torch.Size([1, 1355])
[128006, 78191, 128007, 198]
[128009]
0: 749 ~ 1355
torch.Size([1, 1419])
[128006, 78191, 128007, 198]
[128009]
0: 876 ~ 1419
torch.Size([1, 1439])
[128006, 78191, 128007, 198]
[128009]
0: 1035 ~ 1439
torch.Size([1, 2144])
[128006, 78191, 128007, 198]
[128009]
0: 1528 ~ 2144
torch.Size([1, 918])
[128006, 78191, 128007, 198]
[128009]
0: 647 ~ 918
torch.Size([1, 930])
[128006, 78191, 128007, 198]
[128009]
0: 395 ~ 930
torch.Size([1, 1305])
[128006, 78191, 128007, 198]
[128009]
0: 680 ~ 1305
torch.Size([1, 615])
[128006, 78191, 128007, 198]
[128009]
0: 418 ~ 615
torch.Size([1, 1385])
[128006, 78191, 128007, 198]
[128009]
0: 902 ~ 1385
torch.Size([1, 1946])
[128006, 78191, 128007, 198]
[128009]
0: 1546 ~ 1946
torch.Size([1, 1151])
[128006, 78191, 128007, 198]
[128009]
0: 709 ~ 1151
torch.Size([1, 1235])
[128006, 78191, 128007, 198]
[128009]
0: 571 ~ 1235
torch.Size([1, 1203])
[128006, 78191, 128007, 198]
[128009]
0: 650 ~ 1203
torch.Size([1, 2200])
[128006, 78191, 128007, 198]
[128009]
0: 1600 ~ 2200
torch.Size([1, 437])
[128006, 78191, 128007, 198]
[128009]
0: 319 ~ 437
torch.Size([1, 1626])
[128006, 78191, 128007, 198]
[128009]
0: 1034 ~ 1626
torch.Size([1, 689])
[128006, 78191, 128007, 198]
[128009]
0: 331 ~ 689
torch.Size([1, 814])
[128006, 78191, 128007, 198]
[128009]
0: 429 ~ 814
torch.Size([1, 2153])
[128006, 78191, 128007, 198]
[128009]
0: 1280 ~ 2153
torch.Size([1, 1185])
[128006, 78191, 128007, 198]
[128009]
0: 728 ~ 1185
torch.Size([1, 1528])
[128006, 78191, 128007, 198]
[128009]
0: 1040 ~ 1528
torch.Size([1, 2001])
[128006, 78191, 128007, 198]
[128009]
0: 1489 ~ 2001
torch.Size([1, 2041])
[128006, 78191, 128007, 198]
[128009]
0: 1295 ~ 2041
torch.Size([1, 1358])
[128006, 78191, 128007, 198]
[128009]
0: 1021 ~ 1358
torch.Size([1, 1814])
[128006, 78191, 128007, 198]
[128009]
0: 1078 ~ 1814
torch.Size([1, 903])
[128006, 78191, 128007, 198]
[128009]
0: 421 ~ 903
torch.Size([1, 578])
[128006, 78191, 128007, 198]
[128009]
0: 332 ~ 578
torch.Size([1, 2414])
[128006, 78191, 128007, 198]
[128009]
0: 1814 ~ 2414
torch.Size([1, 1091])
[128006, 78191, 128007, 198]
[128009]
0: 632 ~ 1091
torch.Size([1, 1222])
[128006, 78191, 128007, 198]
[128009]
0: 709 ~ 1222
torch.Size([1, 2639])
[128006, 78191, 128007, 198]
[128009]
0: 2033 ~ 2639
torch.Size([1, 1403])
[128006, 78191, 128007, 198]
[128009]
0: 1138 ~ 1403
torch.Size([1, 1508])
[128006, 78191, 128007, 198]
[128009]
0: 806 ~ 1508
torch.Size([1, 1679])
[128006, 78191, 128007, 198]
[128009]
0: 1196 ~ 1679
torch.Size([1, 1332])
[128006, 78191, 128007, 198]
[128009]
0: 810 ~ 1332
torch.Size([1, 1811])
[128006, 78191, 128007, 198]
[128009]
0: 1098 ~ 1811
torch.Size([1, 2676])
[128006, 78191, 128007, 198]
[128009]
0: 1920 ~ 2676
torch.Size([1, 1327])
[128006, 78191, 128007, 198]
[128009]
0: 688 ~ 1327
torch.Size([1, 702])
[128006, 78191, 128007, 198]
[128009]
0: 361 ~ 702
torch.Size([1, 1275])
[128006, 78191, 128007, 198]
[128009]
0: 824 ~ 1275
torch.Size([1, 1023])
[128006, 78191, 128007, 198]
[128009]
0: 631 ~ 1023
torch.Size([1, 1848])
[128006, 78191, 128007, 198]
[128009]
0: 1341 ~ 1848
torch.Size([1, 1438])
[128006, 78191, 128007, 198]
[128009]
0: 781 ~ 1438
torch.Size([1, 1462])
[128006, 78191, 128007, 198]
[128009]
0: 879 ~ 1462
torch.Size([1, 1438])
[128006, 78191, 128007, 198]
[128009]
0: 873 ~ 1438
torch.Size([1, 1951])
[128006, 78191, 128007, 198]
[128009]
0: 1247 ~ 1951
torch.Size([1, 1544])
[128006, 78191, 128007, 198]
[128009]
0: 1198 ~ 1544
torch.Size([1, 1078])
[128006, 78191, 128007, 198]
[128009]
0: 683 ~ 1078
torch.Size([1, 1650])
[128006, 78191, 128007, 198]
[128009]
0: 1285 ~ 1650
torch.Size([1, 1985])
[128006, 78191, 128007, 198]
[128009]
0: 1278 ~ 1985
torch.Size([1, 1386])
[128006, 78191, 128007, 198]
[128009]
0: 769 ~ 1386
torch.Size([1, 1871])
[128006, 78191, 128007, 198]
[128009]
0: 1336 ~ 1871
torch.Size([1, 958])
[128006, 78191, 128007, 198]
[128009]
0: 692 ~ 958
torch.Size([1, 2006])
[128006, 78191, 128007, 198]
[128009]
0: 1290 ~ 2006
torch.Size([1, 842])
[128006, 78191, 128007, 198]
[128009]
0: 403 ~ 842
torch.Size([1, 2364])
[128006, 78191, 128007, 198]
[128009]
0: 1617 ~ 2364
torch.Size([1, 820])
[128006, 78191, 128007, 198]
[128009]
0: 608 ~ 820
torch.Size([1, 1472])
[128006, 78191, 128007, 198]
[128009]
0: 1013 ~ 1472
torch.Size([1, 1981])
[128006, 78191, 128007, 198]
[128009]
0: 1280 ~ 1981
torch.Size([1, 1545])
[128006, 78191, 128007, 198]
[128009]
0: 1013 ~ 1545
torch.Size([1, 1726])
[128006, 78191, 128007, 198]
[128009]
0: 1068 ~ 1726
torch.Size([1, 914])
[128006, 78191, 128007, 198]
[128009]
0: 621 ~ 914
torch.Size([1, 1568])
[128006, 78191, 128007, 198]
[128009]
0: 858 ~ 1568
torch.Size([1, 1903])
[128006, 78191, 128007, 198]
[128009]
0: 1229 ~ 1903
torch.Size([1, 1478])
[128006, 78191, 128007, 198]
[128009]
0: 951 ~ 1478
torch.Size([1, 1488])
[128006, 78191, 128007, 198]
[128009]
0: 901 ~ 1488
torch.Size([1, 1074])
[128006, 78191, 128007, 198]
[128009]
0: 678 ~ 1074
torch.Size([1, 754])
[128006, 78191, 128007, 198]
[128009]
0: 590 ~ 754
torch.Size([1, 2492])
[128006, 78191, 128007, 198]
[128009]
0: 1796 ~ 2492
torch.Size([1, 1420])
[128006, 78191, 128007, 198]
[128009]
0: 859 ~ 1420
torch.Size([1, 497])
[128006, 78191, 128007, 198]
[128009]
0: 341 ~ 497
torch.Size([1, 1289])
[128006, 78191, 128007, 198]
[128009]
0: 1053 ~ 1289
torch.Size([1, 1936])
[128006, 78191, 128007, 198]
[128009]
0: 1244 ~ 1936
torch.Size([1, 2083])
[128006, 78191, 128007, 198]
[128009]
0: 1454 ~ 2083
torch.Size([1, 1098])
[128006, 78191, 128007, 198]
[128009]
0: 395 ~ 1098
torch.Size([1, 2233])
[128006, 78191, 128007, 198]
[128009]
0: 1680 ~ 2233
torch.Size([1, 1766])
[128006, 78191, 128007, 198]
[128009]
0: 1006 ~ 1766
torch.Size([1, 855])
[128006, 78191, 128007, 198]
[128009]
0: 621 ~ 855
torch.Size([1, 1412])
[128006, 78191, 128007, 198]
[128009]
0: 913 ~ 1412
torch.Size([1, 1400])
[128006, 78191, 128007, 198]
[128009]
0: 934 ~ 1400
torch.Size([1, 1789])
[128006, 78191, 128007, 198]
[128009]
0: 1204 ~ 1789
torch.Size([1, 1810])
[128006, 78191, 128007, 198]
[128009]
0: 1332 ~ 1810
torch.Size([1, 1817])
[128006, 78191, 128007, 198]
[128009]
0: 983 ~ 1817
torch.Size([1, 1294])
[128006, 78191, 128007, 198]
[128009]
0: 745 ~ 1294
torch.Size([1, 4035])
[128006, 78191, 128007, 198]
[128009]
0: 3081 ~ 4035
torch.Size([1, 582])
[128006, 78191, 128007, 198]
[128009]
0: 445 ~ 582
torch.Size([1, 1441])
[128006, 78191, 128007, 198]
[128009]
0: 963 ~ 1441
torch.Size([1, 1615])
[128006, 78191, 128007, 198]
[128009]
0: 964 ~ 1615
torch.Size([1, 1133])
[128006, 78191, 128007, 198]
[128009]
0: 493 ~ 1133
torch.Size([1, 2196])
[128006, 78191, 128007, 198]
[128009]
0: 1712 ~ 2196
torch.Size([1, 686])
[128006, 78191, 128007, 198]
[128009]
0: 391 ~ 686
torch.Size([1, 1315])
[128006, 78191, 128007, 198]
[128009]
0: 736 ~ 1315
torch.Size([1, 1038])
[128006, 78191, 128007, 198]
[128009]
0: 641 ~ 1038
torch.Size([1, 1144])
[128006, 78191, 128007, 198]
[128009]
0: 837 ~ 1144
torch.Size([1, 1958])
[128006, 78191, 128007, 198]
[128009]
0: 1156 ~ 1958
torch.Size([1, 480])
[128006, 78191, 128007, 198]
[128009]
0: 333 ~ 480
torch.Size([1, 1357])
[128006, 78191, 128007, 198]
[128009]
0: 847 ~ 1357
torch.Size([1, 818])
[128006, 78191, 128007, 198]
[128009]
0: 376 ~ 818
torch.Size([1, 896])
[128006, 78191, 128007, 198]
[128009]
0: 396 ~ 896
torch.Size([1, 1426])
[128006, 78191, 128007, 198]
[128009]
0: 860 ~ 1426
torch.Size([1, 1443])
[128006, 78191, 128007, 198]
[128009]
0: 873 ~ 1443
torch.Size([1, 1075])
[128006, 78191, 128007, 198]
[128009]
0: 623 ~ 1075
torch.Size([1, 1074])
[128006, 78191, 128007, 198]
[128009]
0: 869 ~ 1074
torch.Size([1, 1060])
[128006, 78191, 128007, 198]
[128009]
0: 603 ~ 1060
torch.Size([1, 459])
[128006, 78191, 128007, 198]
[128009]
0: 325 ~ 459
torch.Size([1, 1344])
[128006, 78191, 128007, 198]
[128009]
0: 709 ~ 1344
torch.Size([1, 2327])
[128006, 78191, 128007, 198]
[128009]
0: 1873 ~ 2327
torch.Size([1, 2098])
[128006, 78191, 128007, 198]
[128009]
0: 1367 ~ 2098
torch.Size([1, 2330])
[128006, 78191, 128007, 198]
[128009]
0: 1899 ~ 2330
torch.Size([1, 792])
[128006, 78191, 128007, 198]
[128009]
0: 407 ~ 792
torch.Size([1, 787])
[128006, 78191, 128007, 198]
[128009]
0: 601 ~ 787
torch.Size([1, 3006])
[128006, 78191, 128007, 198]
[128009]
0: 2414 ~ 3006
torch.Size([1, 1147])
[128006, 78191, 128007, 198]
[128009]
0: 683 ~ 1147
torch.Size([1, 646])
[128006, 78191, 128007, 198]
[128009]
0: 473 ~ 646
torch.Size([1, 1456])
[128006, 78191, 128007, 198]
[128009]
0: 885 ~ 1456
torch.Size([1, 893])
[128006, 78191, 128007, 198]
[128009]
0: 429 ~ 893
torch.Size([1, 1216])
[128006, 78191, 128007, 198]
[128009]
0: 622 ~ 1216
torch.Size([1, 611])
[128006, 78191, 128007, 198]
[128009]
0: 444 ~ 611
torch.Size([1, 1018])
[128006, 78191, 128007, 198]
[128009]
0: 793 ~ 1018
torch.Size([1, 1685])
[128006, 78191, 128007, 198]
[128009]
0: 912 ~ 1685
torch.Size([1, 1505])
[128006, 78191, 128007, 198]
[128009]
0: 1183 ~ 1505
torch.Size([1, 1013])
[128006, 78191, 128007, 198]
[128009]
0: 819 ~ 1013
torch.Size([1, 1945])
[128006, 78191, 128007, 198]
[128009]
0: 1270 ~ 1945
torch.Size([1, 1024])
[128006, 78191, 128007, 198]
[128009]
0: 593 ~ 1024
torch.Size([1, 844])
[128006, 78191, 128007, 198]
[128009]
0: 375 ~ 844
torch.Size([1, 1004])
[128006, 78191, 128007, 198]
[128009]
0: 595 ~ 1004
torch.Size([1, 1076])
[128006, 78191, 128007, 198]
[128009]
0: 601 ~ 1076
torch.Size([1, 402])
[128006, 78191, 128007, 198]
[128009]
0: 300 ~ 402
torch.Size([1, 1554])
[128006, 78191, 128007, 198]
[128009]
0: 1082 ~ 1554
torch.Size([1, 1222])
[128006, 78191, 128007, 198]
[128009]
0: 558 ~ 1222
torch.Size([1, 829])
[128006, 78191, 128007, 198]
[128009]
0: 506 ~ 829
torch.Size([1, 615])
[128006, 78191, 128007, 198]
[128009]
0: 306 ~ 615
torch.Size([1, 920])
[128006, 78191, 128007, 198]
[128009]
0: 691 ~ 920
torch.Size([1, 1148])
[128006, 78191, 128007, 198]
[128009]
0: 606 ~ 1148
torch.Size([1, 1233])
[128006, 78191, 128007, 198]
[128009]
0: 759 ~ 1233
torch.Size([1, 1214])
[128006, 78191, 128007, 198]
[128009]
0: 864 ~ 1214
torch.Size([1, 888])
[128006, 78191, 128007, 198]
[128009]
0: 526 ~ 888
torch.Size([1, 2154])
[128006, 78191, 128007, 198]
[128009]
0: 1407 ~ 2154
torch.Size([1, 1476])
[128006, 78191, 128007, 198]
[128009]
0: 881 ~ 1476
torch.Size([1, 1581])
[128006, 78191, 128007, 198]
[128009]
0: 1020 ~ 1581
torch.Size([1, 1059])
[128006, 78191, 128007, 198]
[128009]
0: 597 ~ 1059
torch.Size([1, 942])
[128006, 78191, 128007, 198]
[128009]
0: 331 ~ 942
torch.Size([1, 1528])
[128006, 78191, 128007, 198]
[128009]
0: 1067 ~ 1528
torch.Size([1, 1267])
[128006, 78191, 128007, 198]
[128009]
0: 1026 ~ 1267
torch.Size([1, 1497])
[128006, 78191, 128007, 198]
[128009]
0: 848 ~ 1497
torch.Size([1, 902])
[128006, 78191, 128007, 198]
[128009]
0: 619 ~ 902
torch.Size([1, 491])
[128006, 78191, 128007, 198]
[128009]
0: 377 ~ 491
torch.Size([1, 1161])
[128006, 78191, 128007, 198]
[128009]
0: 702 ~ 1161
torch.Size([1, 1810])
[128006, 78191, 128007, 198]
[128009]
0: 1352 ~ 1810
torch.Size([1, 670])
[128006, 78191, 128007, 198]
[128009]
0: 463 ~ 670
torch.Size([1, 1708])
[128006, 78191, 128007, 198]
[128009]
0: 1122 ~ 1708
torch.Size([1, 1385])
[128006, 78191, 128007, 198]
[128009]
0: 740 ~ 1385
torch.Size([1, 1045])
[128006, 78191, 128007, 198]
[128009]
0: 631 ~ 1045
torch.Size([1, 1460])
[128006, 78191, 128007, 198]
[128009]
0: 935 ~ 1460
torch.Size([1, 1441])
[128006, 78191, 128007, 198]
[128009]
0: 1070 ~ 1441
torch.Size([1, 1096])
[128006, 78191, 128007, 198]
[128009]
0: 482 ~ 1096
torch.Size([1, 1256])
[128006, 78191, 128007, 198]
[128009]
0: 797 ~ 1256
torch.Size([1, 1772])
[128006, 78191, 128007, 198]
[128009]
0: 1066 ~ 1772
torch.Size([1, 858])
[128006, 78191, 128007, 198]
[128009]
0: 402 ~ 858
torch.Size([1, 1148])
[128006, 78191, 128007, 198]
[128009]
0: 652 ~ 1148
torch.Size([1, 1414])
[128006, 78191, 128007, 198]
[128009]
0: 716 ~ 1414
torch.Size([1, 1430])
[128006, 78191, 128007, 198]
[128009]
0: 806 ~ 1430
torch.Size([1, 973])
[128006, 78191, 128007, 198]
[128009]
0: 671 ~ 973
torch.Size([1, 459])
[128006, 78191, 128007, 198]
[128009]
0: 323 ~ 459
torch.Size([1, 1930])
[128006, 78191, 128007, 198]
[128009]
0: 1196 ~ 1930
torch.Size([1, 1516])
[128006, 78191, 128007, 198]
[128009]
0: 828 ~ 1516
torch.Size([1, 1011])
[128006, 78191, 128007, 198]
[128009]
0: 544 ~ 1011
torch.Size([1, 823])
[128006, 78191, 128007, 198]
[128009]
0: 611 ~ 823
torch.Size([1, 903])
[128006, 78191, 128007, 198]
[128009]
0: 470 ~ 903
torch.Size([1, 1685])
[128006, 78191, 128007, 198]
[128009]
0: 1296 ~ 1685
torch.Size([1, 880])
[128006, 78191, 128007, 198]
[128009]
0: 662 ~ 880
torch.Size([1, 1639])
[128006, 78191, 128007, 198]
[128009]
0: 1108 ~ 1639
torch.Size([1, 791])
[128006, 78191, 128007, 198]
[128009]
0: 604 ~ 791
torch.Size([1, 1951])
[128006, 78191, 128007, 198]
[128009]
0: 1498 ~ 1951
torch.Size([1, 1085])
[128006, 78191, 128007, 198]
[128009]
0: 855 ~ 1085
torch.Size([1, 818])
[128006, 78191, 128007, 198]
[128009]
0: 585 ~ 818
torch.Size([1, 1620])
[128006, 78191, 128007, 198]
[128009]
0: 1111 ~ 1620
torch.Size([1, 1140])
[128006, 78191, 128007, 198]
[128009]
0: 881 ~ 1140
torch.Size([1, 1182])
[128006, 78191, 128007, 198]
[128009]
0: 656 ~ 1182
torch.Size([1, 1094])
[128006, 78191, 128007, 198]
[128009]
0: 600 ~ 1094
torch.Size([1, 2563])
[128006, 78191, 128007, 198]
[128009]
0: 2188 ~ 2563
torch.Size([1, 1522])
[128006, 78191, 128007, 198]
[128009]
0: 838 ~ 1522
torch.Size([1, 1161])
[128006, 78191, 128007, 198]
[128009]
0: 638 ~ 1161
torch.Size([1, 2356])
[128006, 78191, 128007, 198]
[128009]
0: 1520 ~ 2356
torch.Size([1, 1148])
[128006, 78191, 128007, 198]
[128009]
0: 710 ~ 1148
torch.Size([1, 554])
[128006, 78191, 128007, 198]
[128009]
0: 420 ~ 554
torch.Size([1, 1171])
[128006, 78191, 128007, 198]
[128009]
0: 895 ~ 1171
torch.Size([1, 910])
[128006, 78191, 128007, 198]
[128009]
0: 594 ~ 910
torch.Size([1, 2043])
[128006, 78191, 128007, 198]
[128009]
0: 1290 ~ 2043
torch.Size([1, 1412])
[128006, 78191, 128007, 198]
[128009]
0: 1101 ~ 1412
torch.Size([1, 1848])
[128006, 78191, 128007, 198]
[128009]
0: 1123 ~ 1848
torch.Size([1, 912])
[128006, 78191, 128007, 198]
[128009]
0: 481 ~ 912
torch.Size([1, 1158])
[128006, 78191, 128007, 198]
[128009]
0: 901 ~ 1158
torch.Size([1, 519])
[128006, 78191, 128007, 198]
[128009]
0: 384 ~ 519
torch.Size([1, 1812])
[128006, 78191, 128007, 198]
[128009]
0: 1123 ~ 1812
torch.Size([1, 3558])
[128006, 78191, 128007, 198]
[128009]
0: 2619 ~ 3558
torch.Size([1, 1296])
[128006, 78191, 128007, 198]
[128009]
0: 715 ~ 1296
torch.Size([1, 1521])
[128006, 78191, 128007, 198]
[128009]
0: 1230 ~ 1521
torch.Size([1, 1468])
[128006, 78191, 128007, 198]
[128009]
0: 944 ~ 1468
torch.Size([1, 997])
[128006, 78191, 128007, 198]
[128009]
0: 739 ~ 997
torch.Size([1, 1620])
[128006, 78191, 128007, 198]
[128009]
0: 1058 ~ 1620
torch.Size([1, 639])
[128006, 78191, 128007, 198]
[128009]
0: 437 ~ 639
torch.Size([1, 886])
[128006, 78191, 128007, 198]
[128009]
0: 330 ~ 886
torch.Size([1, 2111])
[128006, 78191, 128007, 198]
[128009]
0: 1327 ~ 2111
torch.Size([1, 1255])
[128006, 78191, 128007, 198]
[128009]
0: 1022 ~ 1255
torch.Size([1, 508])
[128006, 78191, 128007, 198]
[128009]
0: 337 ~ 508
torch.Size([1, 719])
[128006, 78191, 128007, 198]
[128009]
0: 308 ~ 719
torch.Size([1, 2434])
[128006, 78191, 128007, 198]
[128009]
0: 1622 ~ 2434
torch.Size([1, 1545])
[128006, 78191, 128007, 198]
[128009]
0: 1048 ~ 1545
torch.Size([1, 1834])
[128006, 78191, 128007, 198]
[128009]
0: 1288 ~ 1834
torch.Size([1, 1398])
[128006, 78191, 128007, 198]
[128009]
0: 731 ~ 1398
torch.Size([1, 1673])
[128006, 78191, 128007, 198]
[128009]
0: 1137 ~ 1673
torch.Size([1, 1757])
[128006, 78191, 128007, 198]
[128009]
0: 1107 ~ 1757
torch.Size([1, 646])
[128006, 78191, 128007, 198]
[128009]
0: 367 ~ 646
torch.Size([1, 1045])
[128006, 78191, 128007, 198]
[128009]
0: 575 ~ 1045
torch.Size([1, 1088])
[128006, 78191, 128007, 198]
[128009]
0: 638 ~ 1088
torch.Size([1, 1100])
[128006, 78191, 128007, 198]
[128009]
0: 773 ~ 1100
torch.Size([1, 909])
[128006, 78191, 128007, 198]
[128009]
0: 684 ~ 909
torch.Size([1, 842])
[128006, 78191, 128007, 198]
[128009]
0: 399 ~ 842
torch.Size([1, 2059])
[128006, 78191, 128007, 198]
[128009]
0: 1331 ~ 2059
torch.Size([1, 2037])
[128006, 78191, 128007, 198]
[128009]
0: 1417 ~ 2037
torch.Size([1, 979])
[128006, 78191, 128007, 198]
[128009]
0: 731 ~ 979
torch.Size([1, 1403])
[128006, 78191, 128007, 198]
[128009]
0: 742 ~ 1403
torch.Size([1, 1002])
[128006, 78191, 128007, 198]
[128009]
0: 554 ~ 1002
torch.Size([1, 952])
[128006, 78191, 128007, 198]
[128009]
0: 590 ~ 952
torch.Size([1, 1596])
[128006, 78191, 128007, 198]
[128009]
0: 960 ~ 1596
torch.Size([1, 1269])
[128006, 78191, 128007, 198]
[128009]
0: 762 ~ 1269
torch.Size([1, 1009])
[128006, 78191, 128007, 198]
[128009]
0: 761 ~ 1009
torch.Size([1, 1078])
[128006, 78191, 128007, 198]
[128009]

TrainOutput(global_step=600, training_loss=1.0903061135609944, metrics={'train_runtime': 473.2478, 'train_samples_per_second': 5.071, 'train_steps_per_second': 1.268, 'total_flos': 7.432055393685504e+16, 'train_loss': 1.0903061135609944, 'epoch': 3.0})

# 평가

In [22]:
# 테스트셋 messages에서 프롬프트/정답(assistant) 텍스트 분리
prompt_list = [] # 프롬프트 (assistant 답변 내용 이전) 리스트
label_list = [] # 정답 (assistant 답변 내용) 리스트

for messages in test_dataset["messages"]:
    # 채팅 템플릿 문자열로 반환
    text = tokenizer.apply_chat_template(messages, tokenize = False, add_generation_prompt =False)
    # assistant 답변 내용 전까지 input
    input = text.split('<|start_header_id|>user<|end_header_id|>\n')[0] + \
        '<|start_header_id|>user<|end_header_id|>\n'
    # assistant 답변 내용(종료 토큰 전) 추출
    labels = text.split('<|start_header_id|>user<|end_header_id|>\n')[1].split('<|eot.id|>')[0]
    prompt_list.append(input)
    label_list.append(labels)

In [23]:
print(prompt_list[100])

<|begin_of_text|><|start_header_id|>system<|end_header_id|>

당신은 금융/경제 뉴스의 핵심내용을 요약해 설명하고,
특정 상장 종목에 미치는 긍정/부정 영향여부, 이유, 근거를 분석하는 금융/경제 분석 전문가입니다.

다음 출력지시사항을 지켜주세요.
1. 뉴스와 종목간의 연관성을 발견할 수 없다면:
    - stock_related를 False로 작성하세요.
    - summary에 뉴스의 요약을 작성하세요.
2. 뉴스와 종목간의 연관성을 발견했다면:
    - stock_related를 True로 작성하세요.
    - summary에 뉴스의 요약을 작성하세요.
    - 긍정영향이 예상되는 종목이 있다면, positive_stocks, positive_keywords, positive_reasons를 작성하세요.
    - 부정영향이 예상되는 종목이 있다면, negative_stocks, negative_keywords, negative_reasons를 작성하세요.
    - 값이 없는 경우 빈 문자열(''), 빈 리스트([])로 작성하세요.<|eot_id|><|start_header_id|>user<|end_header_id|>

In [24]:
print(label_list[100])

공유수면 사용하려면 어입인 의견 들어야
해수부 5일 개정 공유수면 관리 및 매립에 관한 법률 시행 헤럴드경제 홍태화 기자 앞으로 공유수면관리청이 어업·환경 등에 영향을 미칠 것으로 예상되는 공유수면 점용·사용 허가를 할 때 미리 어업인 등 이해관계자들의 의견을 들어야 한다. 해양수산부는 5일 이같은 내용이 담긴 개정 공유수면 관리 및 매립에 관한 법률과 같은 법 시행령·시행규칙이 이날부터 시행된다고 밝혔다. 바다·바닷가·하천 등 공유수면은 공유재이기 때문에 이를 점용·사용하기 위해서는 별도의 허가를 받아야 한다. 최근 해상풍력 발전시설 해변을 이용한 관광시설 등 대규모 시설이 공유수면을 장기적으로 점용·사용하는 경우가 늘어났지만 이해 관계자의 의견을 사전에 수렴할 수 없는 문제가 있었다. 이에 공유수면 점용·사용으로 인한 사회적 갈등이 증가했다. 이러한 문제를 해결하기 위해 해수부는 지난 1월 공유수면 점용·사용 허가를 할 때 이해관계자의 의견을 듣도록 공유수면 관리 및 매립에 관한 법률을 개정했다. 법 개정에 따라 공유수면관리청이 해양환경·수산자원·자연경관 보호 등에 영향을 끼칠 수 있는 공유수면 점용·사용 신청을 받은 경우 이를 관보 공보 와 인터넷 홈페이지에 공고해야 한다. 또 점용·사용 허가를 했을 때 피해를 볼 것으로 예상되는 어업인에 대한 의견 조사도 별도로 진행해야 한다. 황준성 해수부 해양공간정책과장은 공유수면 점용·사용으로 인한 이해 관계자의 피해를 방지하려는 법령 개정의 취지를 달성할 수 있도록 각 공유수면관리청과 협력해 관련 제도의 차질 없는 운영을 지원하겠다 고 말했다.<|eot_id|><|start_header_id|>assistant<|end_header_id|>

{"stock_related":true,"summary":"해양수산부가 공유수면 관리 및 매립에 관한 법률과 시행령·시행규칙 개정안을 시행했다. 이에 따라 해상풍력 발전시설, 해변 관광시설 등 해양환경·수산자원·자연경관에 영향을 줄 수 있는 공유수면 점용·사용 허가를 진행할 경우, 관리청은 신청 내용을 관보·공보·인터넷 홈페이지에 공고하고 어업인 등 피해가 예상되는 이해관계자의 의견을 사전에 조사해야 한다. 제도 취지는 대규모 해양 개발 과정에서 어업권 침해와 환경 훼손에 따른 사회적 갈등을 줄이는 것이지만, 사업자 입장에서는 인허가 절차가 길어지고 추가 협의·보상 비용이 발생할 가능성이 있다.","positive_stocks":[],"positive_keywords":[],"positive_reasons":"","negative_stocks":["SK오션플랜트","씨에스윈드","LS마린솔루션"],"negative_keywords":["공유수면 점용·사용 인허가","어업인 의견 수렴","해상풍력 사업 지연","추가 협의 및 보상 비용","사회적 갈등"],"negative_reasons":"이번 규정은 해상풍력 등 대규모 해양 개발사업의 인허가 전에 어업인과 환경 관련 이해관계자의 의견을 의무적으로 확인하도록 해 사업 일정과 불확실성을 확대할 수 있다. SK오션플랜트와 씨에스윈드는 해상풍력 하부구조물·풍력 타워 등 관련 사업의 수주 및 매출 인식이 프로젝트 인허가와 착공 일정에 영향을 받을 수 있으며, LS마린솔루션도 해저케이블 시공 등 해상풍력 인프라 사업의 발주 지연 가능성에 노출된다. 다만 해당 기업들은 여러 국가와 다양한 프로젝트를 보유하고 있어 실제 영향은 개별 사업의 입지, 인허가 진행 단계, 어업인과의 협의 결과에 따라 달라지며, 장기적으로는 사전 갈등 조정이 사업 중단 위험을 낮추는 긍정적 효과도 있을 수 있다."}<|eot_id|><|start_header_id|>assistant<|end_header_id|>

### 추론모델 - 런타임결합
1. lora모델을 로드
2. base모델 + lora adapter 세팅

In [ ]:
from peft import AutoPeftModelForCausalLM
from transformers import AutoTokenizer, pipeline # 토크나이저 자동 로더 / 파이프라인
import torch

peft_model_name = hub_model_id # 업로드된 PEFT 모델 repo

finetuned_model = AutoPeftModelForCausalLM.from_pretrained(
    peft_model_name, 
    dtype = torch.bfloat16, # 가중치 로딩 dtype(bf16)
    device_map = 'auto', # 환경에 맞춰 CPU / GPU 자동 배치
    quantization_config = quant_config # 4bit 양자화 설정 적용
)
# 해당 모델의 토크나이저 로드
tokenizer = AutoTokenizer.from_pretrained(peft_model_name)

# 텍스트 생성 파이프라인
pipe = pipeline('text-generation', model=finetuned_model, tokenizer=tokenizer)
pipe

adapter_config.json:   0%|          | 0.00/1.08k [00:00<?, ?B/s]

Loading weights:   0%|          | 0/291 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/497 [00:00<?, ?B/s]

tokenizer.json: reconstructing file:   0%|          |  0.00B / 17.2MB

tokenizer.json: downloading bytes:           |  0.00B

chat_template.jinja:   0%|          | 0.00/348 [00:00<?, ?B/s]

adapter_model.safetensors: reconstructing file:   0%|          |  0.00B / 6.83MB

adapter_model.safetensors: downloading bytes:           |  0.00B

TextGenerationPipeline: {'model': 'PeftModelForCausalLM', 'dtype': 'bfloat16', 'device': 'cuda', 'input_modalities': 'text', 'output_modalities': ('text',)}

In [27]:
# <|eot_id|>의 토큰 id 추출
eos_token = tokenizer('<|eot_id|>', add_special_tokens=False)['input_ids'][0]
eos_token

128009

In [28]:
# 테스트 추론 함수 : 프롬프트, 정답, 모델응답 비교 출력
def test_inference(pipe, prompt):
    # 파이프라인으로 결정론적인 답변 생성
    outputs = pipe(prompt, max_new_tokens=1024, eos_token_id=eos_token, do_sample=False)
    assistant_start = len(prompt) # 입력 구간 이후 생성 결과만 사용
    # 프롬프트 이후(생성된 부분)만 반환
    return outputs[0]['generated_text'][assistant_start:].strip() 

for prompt, label in zip(prompt_list[10:13], label_list[10:13]): # 10~12 샘플
    print(f"[prompt]: {prompt}")
    print(f"[label] : {label}")
    print(f"[response]: {test_inference(pipe,prompt)}")
    print('='*100)

[transformers] Passing `generation_config` together with generation-related arguments=({'do_sample', 'max_new_tokens', 'eos_token_id'}) is deprecated and will be removed in future versions. Please pass either a `generation_config` object OR all generation parameters explicitly, but not both.
[transformers] Both `max_new_tokens` (=1024) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[prompt]: <|begin_of_text|><|start_header_id|>system<|end_header_id|>

당신은 금융/경제 뉴스의 핵심내용을 요약해 설명하고,
특정 상장 종목에 미치는 긍정/부정 영향여부, 이유, 근거를 분석하는 금융/경제 분석 전문가입니다.

다음 출력지시사항을 지켜주세요.
1. 뉴스와 종목간의 연관성을 발견할 수 없다면:
    - stock_related를 False로 작성하세요.
    - summary에 뉴스의 요약을 작성하세요.
2. 뉴스와 종목간의 연관성을 발견했다면:
    - stock_related를 True로 작성하세요.
    - summary에 뉴스의 요약을 작성하세요.
    - 긍정영향이 예상되는 종목이 있다면, positive_stocks, positive_keywords, positive_reasons를 작성하세요.
    - 부정영향이 예상되는 종목이 있다면, negative_stocks, negative_keywords, negative_reasons를 작성하세요.
    - 값이 없는 경우 빈 문자열(''), 빈 리스트([])로 작성하세요.<|eot_id|><|start_header_id|>user<|end_header_id|>

[label] :
글로벌 비즈 가트너 올해 전세계 스마트폰 판매량 7% 감소 전망
경제와이드 모닝벨 글로벌 비즈 임선우 외신캐스터 글로벌 비즈입니다. ◇ 올해 스마트폰 판매 감소 올해 전세계 스마트폰 판매량이 크게 줄어들 것이란 전망이 나왔습니다. 시장조사업체 가트너는 글로벌 스마트폰 판매가 7% 하락할 것으로 내다봤는데요. 경제 전반에 걸친 침체 우려와 중국의 봉쇄조치 여파 그리고 인플레이션으로 소비자들이 지갑을 열기 주저하면서 수요가 줄어들 것 이라고 설명했습니다. 그러면서 올해 전체 출하량은 14억6천만대 수준에 그칠 것으로 예측했는데요. 종전 전망치인 16억대에서 대폭 낮춰 잡았습니다. 특히 세계 최대 스마트폰 시장인 중국에서 판매량은 18%가 감소할 것으로 전망했는데요. 가트너는 이같은 수요 부진으로 애플을 비롯한 스마트폰 제조사부터 엔비디아 TSMC 같은 반도체 업체까지 압력이 가해질 것이라고 진단했습니다. ◇ EU 가상자산 돈세탁 막는다 유럽연합이 가상자산을 이용한 돈세탁을 막기위해 관련 기업을 규제하는 방안에 잠정 합의했습니다. 잠정안에는 가상자산 업체가 당국에 모든 디지털자산 거래에 대한 신원 확인 정보를 제공하도록 하는 내용이 담겼는데요. 이에 따라 업체들은 관련 개인정보를 확보해야하고 당국이 이를 요구할 경우 제출해야 합니다. 또 거래액이 1천 유로 우리돈 130만 원을 넘길 경우 비인증 거래소가 관리하는 가상자산 지갑도 똑같은 규칙이 적용되는데요. 여기에 더해 송금 규제를 활용해 거래를 상시 추적하고 불법성이 의심되는 거래를 막을 수 있도록 할 방침입니다. 이와 관련해 미국 최대 가상자산 거래소 코인베이스 등 관련 기업 40여 곳은 개인정보 침해 가능성을 언급하며 줄곧 반대 입장을 밝혀왔는데요. 하지만 최근 가상자산 관련 범죄 사례가 급증하고 있는 만큼 규제 움직임이 힘을 얻고 있는 것으로 풀이됩니다. 관련 기관 논의는 오는 30일까지 마무리될 예정인데 이후 EU 위원회와 의회의 승인 절차만 남게 됩니다. ◇ 스피릿 M A 주주투표 또 미뤄 미국 저비용 항공사 스피릿 항공 인수전이 뜨거워지고 있습니다. 경쟁을 벌이고 있는 프론티어와 제트블루 항공이 앞다퉈 인수가를 높이고 있는데요. 더 높은 가격이 제시되면서 스피릿항공은 당초 어제 진행하기로 했던 프론티어 항공과의 합병안에 대한 주주투표를 이달 8일로 연기했습니다. 이미 한 차례 미뤘는데 다시 한번 주주투표를 연기하면서 스피릿이 제트블루와의 합병 여지를 되살리는 것 아니냐는 추측이 나오고 있는데요. 규제 등을 이유로 프론티어와의 인수합병에 무게가 실리는 듯 했지만 제트블루가 계속해서 인수가를 높이며 러브콜을 보내자 고민하는 모습입니다. 스피릿을 품게 되면 미국 항공 업계 다섯 손가락 안에 들 수 있게 되기 때문에 최후의 승자가 누가 될지에 관심이 쏠리고 있습니다. ◇ 텐센트·바이트댄스 하반기 또 감원 중국 대표 기술기업들이 연일 몸집 줄이기에 나서고 있습니다. 월스트리트저널은 텐센트와 바이트댄스를 비롯한 빅테크 기업들이 지난해 수만명의 인력을 줄인데 이어 또 한번 대규모 구조조정을 준비하고 있다고 전했는데요. 과거 수익성이 없는 사업을 정리하기 위해 감원에 나섰다면 최근에는 중국 경제가 고비를 겪으면서 비용을 줄이기 위해 몸집을 줄이고 있다고 설명했습니다. 특히 최근 당국이 빅테크 때리기 기조를 거둬들이고 있다는 점에서 거시적 위기가 새로운 숙제로 떠올랐다고 분석했는데요. 이미 상반기 전 부문에 걸쳐 인력의 10%가 넘게 정리한 텐센트는 하반기 대규모 추가 감원을 예고한데 더해 일부 사업의 전면 철수까지 검토 중인 것으로 알려졌는데요. 그간 규제 철퇴에 허덕이던 중국 빅테크들이 경기 둔화라는 악재까지 겹치면서 고민이 깊어지는 모습입니다. 지금까지 글로벌 비즈였습니다.<|eot_id|><|start_header_id|>assistant<|end_header_id|>

{"stock_related":true,"summary":"가트너는 경기 둔화, 중국 봉쇄 여파, 인플레이션에 따른 소비 위축으로 올해 전 세계 스마트폰 판매량이 전년 대비 7% 감소한 14억6천만 대에 그칠 것으로 전망했다. 특히 중국 판매량은 18% 감소할 것으로 예상돼 애플 등 스마트폰 제조사와 TSMC 등 반도체 업체의 실적 부담이 커질 수 있다. EU는 가상자산 거래 시 고객 신원 확인과 거래 추적을 의무화하는 자금세탁 방지 규제에 잠정 합의했으며, 이는 코인베이스 등 거래소의 준법·개인정보 관리 비용을 높일 가능성이 있다. 한편 스피릿항공 인수전에서는 프론티어항공과 제트블루항공이 인수가를 경쟁적으로 높이면서 스피릿의 주주투표가 재차 연기됐다. 텐센트와 바이트댄스 등 중국 빅테크는 경기 둔화와 비용 절감을 이유로 추가 감원 및 비핵심 사업 철수를 검토 중이다.","positive_stocks":["스피릿항공"],"positive_keywords":["인수가 경쟁","주주투표 연기","경영권 프리미엄","인수 가능성 확대"],"positive_reasons":"프론티어항공과 제트블루항공이 인수가를 경쟁적으로 높이고 있어 스피릿항공 주주에게 더 높은 인수 프리미엄이 제시될 가능성이 있다. 다만 최종 인수 주체와 미국 규제 승인 여부에 따라 주가 변동성이 커질 수 있다.","negative_stocks":["애플","TSMC","엔비디아","코인베이스","제트블루항공","프론티어그룹","텐센트 홀딩스"],"negative_keywords":["스마트폰 판매량 7% 감소","중국 스마트폰 판매 18% 감소","부품 수요 둔화","가상자산 거래 신원확인 의무","준법 비용 증가","인수가 상승","중국 경기 둔화","대규모 감원"],"negative_reasons":"스마트폰 수요 감소는 애플의 아이폰 판매와 TSMC의 모바일·반도체 주문에 직접적인 부담으로 작용할 수 있으며, 엔비디아도 일부 모바일·소비자 전자기기 관련 수요 둔화와 전반적인 반도체 업황 약화의 영향을 받을 수 있다. EU 가상자산 규제는 코인베이스의 고객확인, 거래 모니터링, 개인정보 관리 및 시스템 구축 비용을 높이고 거래 편의성을 낮출 가능성이 있다. 제트블루항공과 프론티어그룹은 스피릿 인수가격 상승에 따른 재무 부담, 통합 비용, 반독점 심사 리스크가 커질 수 있다. 텐센트는 중국 경기 둔화로 광고·게임·핀테크 등 주요 사업의 성장성이 약화될 수 있고, 추가 감원은 비용 절감 효과가 있는 반면 사업 철수와 수익성 악화 우려를 반영한다."}<|eot_id|><|start_header_id|>assistant<|end_header_id|>

[transformers] Both `max_new_tokens` (=1024) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[response]: {"news_title":"미국 경제 성장률 2.7%로 2023년 1분기 GDP 성장률 전망 상승","news_date":"2023년 4월 26일","news_content":"미국 경제성장률이 2023년 1분기 2.7%로 전망됐다. 이는 2022년 4분기 2.6%였던 전망치를 0.1% 높인 수치다. 미국 연방준비제도(Fed)는 인플레이션 둔화와 실업률 하락을 기반으로 2023년 1분기 기준 금리 인하 전망을 발표했다. 미국 경제가 2023년 1분기에도 강한 성장세를 유지할 경우, 미국 소비자와 기업의 실질 소득 증가가 이어질 수 있어 소비와 투자 확대에 긍정적이다. 다만 2.7% 성장률은 2023년 전망치인 2.8%보다 낮아 금리 인하의 효과가 제한적일 수 있고, 인플레이션 둔화가 지속되지 않으면 금리 인하가 중단될 가능성도 있다.","stock_related":true,"positive_stocks":["JPMorgan Chase","Bank of America","Citi","Wells Fargo","Visa","Mastercard","American Express","Visa","Mastercard","American Express"],"positive_keywords":["미국 경제 성장률 상승","소비 확대","금리 인하","실질 소득 증가","소비 지출","신용 활성화","카드 거래","금융 서비스"],"positive_reasons":"미국 경제가 2023년 1분기에도 2.7% 성장할 경우 소비자와 기업의 실질 소득이 증가하고, 금리 인하가 이어질 경우 대출 및 신용 활성화가 확대될 수 있다. 이는 은행의 대출 수익, 신용카드 거래, 소비자 신용 및 투자 활성화에 긍정적이다. 특히 금리 인하가 지속될 경우 대출금리 하락과 함께 대출 수익성 개선이 기대되며, 신용카드 회사는 소비 증가와 신용 활성화로 카드 거래 및 결제 수수료 수익이 늘어날 가능성이 있다. 다만 금리 인하가 실제로 실현되고 대출 및 신용 활성화가 확대되는지는 금리 인하 규모, 인플레이션 둔화 속도, 금리 상승 전망 등에 따라 달라질 수 있다.","negative_stocks":["JPMorgan Chase","Bank of America","Citi","Wells Fargo"],"negative_keywords":["금리 인하","금리 상승 전망","대출금리 하락","이자마진 확대","금리 변동성","금융 위험"],"negative_reasons":"미국 연방준비제도(Fed)가 2023년 1분기 금리 인하를 전망한 것은 금리 상승 전망을 약화시키는 요인이다. 금리 상승이 지연되거나 중단될 경우 은행의 대출금리 하락 효과가 제한되고, 대출금리 상승이 재개될 경우 대출금리 마진과 이자마진이 확대될 수 있다. 또한 금리 변동성이 커질 경우 기업과 소비자의 신용 및 투자 의사결정에 불확실성이 커지고, 금융시장의 변동성이 높아질 수 있다. 따라서 금리 인하가 실제로 실현되고 대출 및 신용 활성화가 확대되는 만큼 긍정적이지만, 금리 상승 전망이 지속되거나 금리 인하가 중단될 경우 은행의 수익성과 대출금리 마진에 부정적 영향을 줄 수 있다."}
====================================================================================================
[prompt]: <|begin_of_text|><|start_header_id|>system<|end_header_id|>

당신은 금융/경제 뉴스의 핵심내용을 요약해 설명하고,
특정 상장 종목에 미치는 긍정/부정 영향여부, 이유, 근거를 분석하는 금융/경제 분석 전문가입니다.

다음 출력지시사항을 지켜주세요.
1. 뉴스와 종목간의 연관성을 발견할 수 없다면:
    - stock_related를 False로 작성하세요.
    - summary에 뉴스의 요약을 작성하세요.
2. 뉴스와 종목간의 연관성을 발견했다면:
    - stock_related를 True로 작성하세요.
    - summary에 뉴스의 요약을 작성하세요.
    - 긍정영향이 예상되는 종목이 있다면, positive_stocks, positive_keywords, positive_reasons를 작성하세요.
    - 부정영향이 예상되는 종목이 있다면, negative_stocks, negative_keywords, negative_reasons를 작성하세요.
    - 값이 없는 경우 빈 문자열(''), 빈 리스트([])로 작성하세요.<|eot_id|><|start_header_id|>user<|end_header_id|>

[label] :
야놀자 포커스미디어와 ‘동네가게 오래함께’ 캠페인 진행
사진 야놀자 제공 야놀자가 포커스미디어와 동네가게 오래함께 캠페인을 진행한다고 4일 밝혔다. 이번 캠페인은 지역 내 우수 소상공인을 발굴하고 이들을 위한 맞춤형 광고를 제작해 해당 지역 내 홍보를 지원한다. 총 14억 원 규모의 광고 제작 및 송출 비용은 양사가 전액 부담한다. 야놀자는 제휴점을 대상으로 사연을 공모하고 상권 빅데이터 분석을 진행해 지원 대상을 선정한다. 포커스미디어는 전국 5천800여 개 아파트에서 하루 800만 시청자를 확보한 엘리베이터 TV 등 자체 인프라를 통해 광고를 송출한다. 캠페인의 첫 광고는 서울시 노원구 동작구를 시작으로 오는 11일부터 2개월 간 방영되며 연말까지 대상 범위를 지속 확대할 예정이다. 야놀자 관계자는 소상공인들에게 직접적인 도움을 줄 수 있는 이번 캠페인을 통해 지역사회와 상생하고 지역경제 활성화에도 기여할 것으로 기대한다 면서 지역 내 우수 소상공인들의 인지도를 제고하고 매출 증대에도 기여할 수 있도록 캠페인의 성공적인 진행을 위한 지원을 아끼지 않을 계획 이라고 말했다.<|eot_id|><|start_header_id|>assistant<|end_header_id|>

{"stock_related":false,"summary":"야놀자와 포커스미디어가 총 14억 원을 투입해 지역 우수 소상공인을 지원하는 ‘동네가게 오래함께’ 캠페인을 진행한다. 야놀자는 제휴점 대상 사연 공모와 상권 빅데이터 분석을 통해 지원 대상을 선정하고, 포커스미디어는 전국 약 5,800개 아파트의 엘리베이터 TV 등 자체 매체를 활용해 맞춤형 광고를 송출한다. 첫 광고는 서울 노원구와 동작구에서 11일부터 2개월간 방영되며, 연말까지 대상 지역을 확대할 예정이다. 이번 캠페인은 소상공인의 인지도와 매출 증대, 지역경제 활성화를 목표로 하지만, 기사 내용만으로 특정 상장사 실적이나 주가에 직접적인 영향을 판단하기는 어렵다.","positive_stocks":[],"positive_keywords":[],"positive_reasons":"","negative_stocks":[],"negative_keywords":[],"negative_reasons":""}<|eot_id|><|start_header_id|>assistant<|end_header_id|>

[transformers] Both `max_new_tokens` (=1024) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[response]: {"news_title":"미국 경제 성장률 2.7%로 2023년 1분기 GDP 성장률 전망 상승","news_date":"2023년 4월 26일","news_content":"미국 경제성장률이 2023년 1분기 2.7%로 전망됐다. 이는 2022년 4분기 2.6%였던 전망치를 0.1% 높인 수치다. 미국 연방준비제도(Fed)는 인플레이션 둔화와 실업률 하락을 기반으로 2023년 1분기 기준 금리 인하 전망을 발표했다. 미국 경제가 2023년 1분기에도 강한 성장세를 유지할 경우, 미국 소비자와 기업의 실질 소득 증가가 이어질 수 있어 소비와 투자 확대에 긍정적이다. 다만 2.7% 성장률은 2023년 전망치인 2.8%보다 낮아 금리 인하의 효과가 제한적일 수 있고, 인플레이션 둔화가 지속되지 않으면 금리 인하가 중단될 가능성도 있다.","stock_related":true,"positive_stocks":["JPMorgan Chase","Bank of America","Citi","Wells Fargo","Visa","Mastercard","American Express","Visa","Mastercard","American Express"],"positive_keywords":["미국 경제 성장률 상승","소비 확대","금리 인하","실질 소득 증가","소비 지출","신용 활성화","카드 거래","금융 서비스"],"positive_reasons":"미국 경제가 2023년 1분기에도 2.7% 성장할 경우 소비자와 기업의 실질 소득이 증가하고, 금리 인하가 이어질 경우 대출 및 신용 활성화가 확대될 수 있다. 이는 은행의 대출 수익, 신용카드 거래, 소비자 신용 및 투자 활성화에 긍정적이다. 특히 금리 인하가 지속될 경우 대출금리 하락과 함께 대출 수익성 개선이 기대되며, 신용카드 회사는 소비 증가와 신용 활성화로 카드 거래 및 결제 수수료 수익이 늘어날 가능성이 있다. 다만 금리 인하가 실제로 실현되고 대출 및 신용 활성화가 확대되는지는 금리 인하 규모, 인플레이션 둔화 속도, 금리 상승 전망 등에 따라 달라질 수 있다.","negative_stocks":["JPMorgan Chase","Bank of America","Citi","Wells Fargo"],"negative_keywords":["금리 인하","금리 상승 전망","대출금리 하락","이자마진 확대","금리 변동성","금융 위험"],"negative_reasons":"미국 연방준비제도(Fed)가 2023년 1분기 금리 인하를 전망한 것은 금리 상승 전망을 약화시키는 요인이다. 금리 상승이 지연되거나 중단될 경우 은행의 대출금리 하락 효과가 제한되고, 대출금리 상승이 재개될 경우 대출금리 마진과 이자마진이 확대될 수 있다. 또한 금리 변동성이 커질 경우 기업과 소비자의 신용 및 투자 의사결정에 불확실성이 커지고, 금융시장의 변동성이 높아질 수 있다. 따라서 금리 인하가 실제로 실현되고 대출 및 신용 활성화가 확대되는 만큼 긍정적이지만, 금리 상승 전망이 지속되거나 금리 인하가 중단될 경우 은행의 수익성과 대출금리 마진에 부정적 영향을 줄 수 있다."}
====================================================================================================
[prompt]: <|begin_of_text|><|start_header_id|>system<|end_header_id|>

당신은 금융/경제 뉴스의 핵심내용을 요약해 설명하고,
특정 상장 종목에 미치는 긍정/부정 영향여부, 이유, 근거를 분석하는 금융/경제 분석 전문가입니다.

다음 출력지시사항을 지켜주세요.
1. 뉴스와 종목간의 연관성을 발견할 수 없다면:
    - stock_related를 False로 작성하세요.
    - summary에 뉴스의 요약을 작성하세요.
2. 뉴스와 종목간의 연관성을 발견했다면:
    - stock_related를 True로 작성하세요.
    - summary에 뉴스의 요약을 작성하세요.
    - 긍정영향이 예상되는 종목이 있다면, positive_stocks, positive_keywords, positive_reasons를 작성하세요.
    - 부정영향이 예상되는 종목이 있다면, negative_stocks, negative_keywords, negative_reasons를 작성하세요.
    - 값이 없는 경우 빈 문자열(''), 빈 리스트([])로 작성하세요.<|eot_id|><|start_header_id|>user<|end_header_id|>

[label] :
삼성바이오로직스 MSD와 2768억원 위탁생산계약 체결
미국 제약기업과 의약품 위탁생산 공급계약 지난해 9월 공시된 본 계약 체결 삼성바이오로직스 3공장 전경. ⓒ삼성바이오로직스 데일리안 이홍석 기자 삼성바이오로직스는 4일 공시를 통해 미국 제약기업 MSD MSD International Business GmbH 와 2768억2938만원 규모의 의약품 위탁생산 공급계약을 체결했다고 밝혔다. 이번 계약은 최근 매출액 대비 17.65% 규모로 계약기간은 2022년 7월 1일부터 2028년 12월 31일이다. 상기 계약금액은 고객사의 수요증가에 따라 3억8186만 달러로 증가할 수 있다. 이번 계약건은 지난해 9월 29일 공시된 ‘투자판단 관련 주요경영사항’에 대한 본계약 체결건이다. 당시 삼성바이오로직스는 MSD 위탁생산계약 의향서를 체결했으며 계약금은 491억원이라고 공시했다.<|eot_id|><|start_header_id|>assistant<|end_header_id|>

{"stock_related":true,"summary":"삼성바이오로직스가 미국 제약사 MSD International Business GmbH와 2,768억2938만원 규모의 의약품 위탁생산(CMO) 공급계약을 체결했다. 계약기간은 2022년 7월 1일부터 2028년 12월 31일까지이며, 계약금액은 고객사 수요 증가에 따라 최대 3억8186만 달러까지 확대될 수 있다. 이번 계약은 지난해 9월 공시한 491억원 규모의 위탁생산 의향서가 본계약으로 전환된 것이다.","positive_stocks":["삼성바이오로직스"],"positive_keywords":["MSD 위탁생산 계약","CMO 수주","계약금액 2768억원","계약기간 2028년까지","수요 증가 시 3억8186만 달러로 확대 가능","장기 매출 가시성"],"positive_reasons":"삼성바이오로직스의 최근 매출액 대비 17.65%에 해당하는 대규모 계약으로, 장기간에 걸쳐 안정적인 생산 물량과 매출을 확보했다는 점에서 긍정적이다. 특히 의향서에서 본계약으로 전환되면서 수주 이행 가능성이 확인됐고, MSD의 수요 증가에 따라 계약 규모가 추가 확대될 수 있어 향후 공장 가동률과 매출 성장에 기여할 수 있다. 글로벌 대형 제약사를 고객사로 확보했다는 점도 삼성바이오로직스의 대형 바이오의약품 위탁생산 경쟁력과 고객 기반을 강화하는 요인이다.","negative_stocks":[],"negative_keywords":[],"negative_reasons":""}<|eot_id|><|start_header_id|>assistant<|end_header_id|>


[response]: {"news_title":"미국 경제 성장률 2.7%로 2023년 1분기 GDP 성장률 전망 상승","news_date":"2023년 4월 26일","news_content":"미국 경제성장률이 2023년 1분기 2.7%로 전망됐다. 이는 2022년 4분기 2.6%였던 전망치를 0.1% 높인 수치다. 미국 연방준비제도(Fed)는 인플레이션 둔화와 실업률 하락을 기반으로 2023년 1분기 기준 금리 인하 전망을 발표했다. 미국 경제가 2023년 1분기에도 강한 성장세를 유지할 경우, 미국 소비자와 기업의 실질 소득 증가가 이어질 수 있어 소비와 투자 확대에 긍정적이다. 다만 2.7% 성장률은 2023년 전망치인 2.8%보다 낮아 금리 인하의 효과가 제한적일 수 있고, 인플레이션 둔화가 지속되지 않으면 금리 인하가 중단될 가능성도 있다.","stock_related":true,"positive_stocks":["JPMorgan Chase","Bank of America","Citi","Wells Fargo","Visa","Mastercard","American Express","Visa","Mastercard","American Express"],"positive_keywords":["미국 경제 성장률 상승","소비 확대","금리 인하","실질 소득 증가","소비 지출","신용 활성화","카드 거래","금융 서비스"],"positive_reasons":"미국 경제가 2023년 1분기에도 2.7% 성장할 경우 소비자와 기업의 실질 소득이 증가하고, 금리 인하가 이어질 경우 대출 및 신용 활성화가 확대될 수 있다. 이는 은행의 대출 수익, 신용카드 거래, 소비자 신용 및 투자 활성화에 긍정적이다. 특히 금리 인하가 지속될 경우 대출금리 하락과 함께 대출 수익성 개선이 기대되며, 신용카드 회사는 소비 증가와 신용 활성화로 카드 거래 및 결제 수수료 수익이 늘어날 가능성이 있다. 다만 금리 인하가 실제로 실현되고 대출 및 신용 활성화가 확대되는지는 금리 인하 규모, 인플레이션 둔화 속도, 금리 상승 전망 등에 따라 달라질 수 있다.","negative_stocks":["JPMorgan Chase","Bank of America","Citi","Wells Fargo"],"negative_keywords":["금리 인하","금리 상승 전망","대출금리 하락","이자마진 확대","금리 변동성","금융 위험"],"negative_reasons":"미국 연방준비제도(Fed)가 2023년 1분기 금리 인하를 전망한 것은 금리 상승 전망을 약화시키는 요인이다. 금리 상승이 지연되거나 중단될 경우 은행의 대출금리 하락 효과가 제한되고, 대출금리 상승이 재개될 경우 대출금리 마진과 이자마진이 확대될 수 있다. 또한 금리 변동성이 커질 경우 기업과 소비자의 신용 및 투자 의사결정에 불확실성이 커지고, 금융시장의 변동성이 높아질 수 있다. 따라서 금리 인하가 실제로 실현되고 대출 및 신용 활성화가 확대되는 만큼 긍정적이지만, 금리 상승 전망이 지속되거나 금리 인하가 중단될 경우 은행의 수익성과 대출금리 마진에 부정적 영향을 줄 수 있다."}
====================================================================================================

### 추론모델 사전 병합
- 진행 후에는 PEFT 없이 해당 repo 모델로 바로 로드/추론 가능하다

In [29]:
from peft import AutoPeftModelForCausalLM # PEFT (LoRA) 모델 로더
from transformers import AutoTokenizer, pipeline

merged_model_id = 'kkkfu/Llama-VARCO-8b-news2stock-analyzer-4bit-merged'

tokenizer = AutoTokenizer.from_pretrained(peft_model_name)

# LoRA 어댑터를 포함한 모델 로드
finetuned_model = AutoPeftModelForCausalLM.from_pretrained(
    peft_model_name,
    dtype = torch.bfloat16, # 가중치 로딩 dtype(bf16)
    device_map= 'auto',      # 환경에 맞춰 CPU / GPU 자동 배치
    quantization_config = quant_config # 4bit 양자화 설정 적용
)

merged_model = finetuned_model.merge_and_unload() # LoRA 가중치를 베이스 모델에 병합 후 어댑터 언로드

merged_model.push_to_hub(merged_model_id, token=True) # 병합 모델 Hub 업로드
tokenizer.push_to_hub(merged_model_id, token =True) # 토크나이저 Hub 업로드

Loading weights:   0%|          | 0/291 [00:00<?, ?it/s]

/usr/local/lib/python3.12/dist-packages/peft/tuners/lora/bnb.py:377: UserWarning: Merge lora module to 4-bit linear may get different generations due to rounding errors.
  warnings.warn(

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Processing Files (0 / 0): |          |  0.00B /  0.00B

New Data Upload: |          |  0.00B /  0.00B

README.md:   0%|          | 0.00/5.17k [00:00<?, ?B/s]

Processing Files (0 / 0): |          |  0.00B /  0.00B

New Data Upload: |          |  0.00B /  0.00B

CommitInfo(commit_url='https://huggingface.co/kkkfu/Llama-VARCO-8b-news2stock-analyzer-4bit-merged/commit/b194a8deee21a328b7eae492812af7a0158b9892', commit_message='Upload tokenizer', commit_description='', oid='b194a8deee21a328b7eae492812af7a0158b9892', pr_url=None, repo_url=RepoUrl('https://huggingface.co/kkkfu/Llama-VARCO-8b-news2stock-analyzer-4bit-merged', endpoint='https://huggingface.co', repo_type='model', repo_id='kkkfu/Llama-VARCO-8b-news2stock-analyzer-4bit-merged'), pr_revision=None, pr_num=None)

In [30]:
#GPU 메모리 해제 (객체 삭제 + GC + CUDA 캐시 비우기) - 필요시 주석 해제 후 사용
del finetuned_model, pipe, merged_model # 사용 완료된 참조 제거

import gc       # 가비지 컬렉션 모듈
gc.collect()    # 참조가 끊긴 객체 메모리 정리

torch.cuda.empty_cache() # CUDA 캐시 메모리 비움

In [31]:
from transformers import AutoTokenizer, AutoModelForCausalLM, pipeline

model_id = 'kkkfu/Llama-VARCO-8b-news2stock-analyzer-4bit-merged'

# 병합된 단일 모델 로드 (PEFT 불필요)
finetuned_model = AutoModelForCausalLM.from_pretrained(
    model_id,
    dtype = torch.bfloat16,
    device_map = 'auto' 
)

tokenizer = AutoTokenizer.from_pretrained(model_id)
pipe = pipeline('text-generation', model = finetuned_model, tokenizer=tokenizer)
pipe

config.json:   0%|          | 0.00/1.22k [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B / 5.70GB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/291 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/143 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/497 [00:00<?, ?B/s]

tokenizer.json: reconstructing file:   0%|          |  0.00B / 17.2MB

tokenizer.json: downloading bytes:           |  0.00B

chat_template.jinja:   0%|          | 0.00/348 [00:00<?, ?B/s]

TextGenerationPipeline: {'model': 'LlamaForCausalLM', 'dtype': 'bfloat16', 'device': 'cuda', 'input_modalities': 'text', 'output_modalities': ('text',)}

In [32]:
for prompt, label in zip(prompt_list[10:13], label_list[10:13]): # 10~12 샘플
    print(f"[prompt]: {prompt}")
    print(f"[label] : {label}")
    print(f"[response]: {test_inference(pipe,prompt)}")
    print('='*100)

[transformers] Both `max_new_tokens` (=1024) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[prompt]: <|begin_of_text|><|start_header_id|>system<|end_header_id|>

당신은 금융/경제 뉴스의 핵심내용을 요약해 설명하고,
특정 상장 종목에 미치는 긍정/부정 영향여부, 이유, 근거를 분석하는 금융/경제 분석 전문가입니다.

다음 출력지시사항을 지켜주세요.
1. 뉴스와 종목간의 연관성을 발견할 수 없다면:
    - stock_related를 False로 작성하세요.
    - summary에 뉴스의 요약을 작성하세요.
2. 뉴스와 종목간의 연관성을 발견했다면:
    - stock_related를 True로 작성하세요.
    - summary에 뉴스의 요약을 작성하세요.
    - 긍정영향이 예상되는 종목이 있다면, positive_stocks, positive_keywords, positive_reasons를 작성하세요.
    - 부정영향이 예상되는 종목이 있다면, negative_stocks, negative_keywords, negative_reasons를 작성하세요.
    - 값이 없는 경우 빈 문자열(''), 빈 리스트([])로 작성하세요.<|eot_id|><|start_header_id|>user<|end_header_id|>

[label] :
글로벌 비즈 가트너 올해 전세계 스마트폰 판매량 7% 감소 전망
경제와이드 모닝벨 글로벌 비즈 임선우 외신캐스터 글로벌 비즈입니다. ◇ 올해 스마트폰 판매 감소 올해 전세계 스마트폰 판매량이 크게 줄어들 것이란 전망이 나왔습니다. 시장조사업체 가트너는 글로벌 스마트폰 판매가 7% 하락할 것으로 내다봤는데요. 경제 전반에 걸친 침체 우려와 중국의 봉쇄조치 여파 그리고 인플레이션으로 소비자들이 지갑을 열기 주저하면서 수요가 줄어들 것 이라고 설명했습니다. 그러면서 올해 전체 출하량은 14억6천만대 수준에 그칠 것으로 예측했는데요. 종전 전망치인 16억대에서 대폭 낮춰 잡았습니다. 특히 세계 최대 스마트폰 시장인 중국에서 판매량은 18%가 감소할 것으로 전망했는데요. 가트너는 이같은 수요 부진으로 애플을 비롯한 스마트폰 제조사부터 엔비디아 TSMC 같은 반도체 업체까지 압력이 가해질 것이라고 진단했습니다. ◇ EU 가상자산 돈세탁 막는다 유럽연합이 가상자산을 이용한 돈세탁을 막기위해 관련 기업을 규제하는 방안에 잠정 합의했습니다. 잠정안에는 가상자산 업체가 당국에 모든 디지털자산 거래에 대한 신원 확인 정보를 제공하도록 하는 내용이 담겼는데요. 이에 따라 업체들은 관련 개인정보를 확보해야하고 당국이 이를 요구할 경우 제출해야 합니다. 또 거래액이 1천 유로 우리돈 130만 원을 넘길 경우 비인증 거래소가 관리하는 가상자산 지갑도 똑같은 규칙이 적용되는데요. 여기에 더해 송금 규제를 활용해 거래를 상시 추적하고 불법성이 의심되는 거래를 막을 수 있도록 할 방침입니다. 이와 관련해 미국 최대 가상자산 거래소 코인베이스 등 관련 기업 40여 곳은 개인정보 침해 가능성을 언급하며 줄곧 반대 입장을 밝혀왔는데요. 하지만 최근 가상자산 관련 범죄 사례가 급증하고 있는 만큼 규제 움직임이 힘을 얻고 있는 것으로 풀이됩니다. 관련 기관 논의는 오는 30일까지 마무리될 예정인데 이후 EU 위원회와 의회의 승인 절차만 남게 됩니다. ◇ 스피릿 M A 주주투표 또 미뤄 미국 저비용 항공사 스피릿 항공 인수전이 뜨거워지고 있습니다. 경쟁을 벌이고 있는 프론티어와 제트블루 항공이 앞다퉈 인수가를 높이고 있는데요. 더 높은 가격이 제시되면서 스피릿항공은 당초 어제 진행하기로 했던 프론티어 항공과의 합병안에 대한 주주투표를 이달 8일로 연기했습니다. 이미 한 차례 미뤘는데 다시 한번 주주투표를 연기하면서 스피릿이 제트블루와의 합병 여지를 되살리는 것 아니냐는 추측이 나오고 있는데요. 규제 등을 이유로 프론티어와의 인수합병에 무게가 실리는 듯 했지만 제트블루가 계속해서 인수가를 높이며 러브콜을 보내자 고민하는 모습입니다. 스피릿을 품게 되면 미국 항공 업계 다섯 손가락 안에 들 수 있게 되기 때문에 최후의 승자가 누가 될지에 관심이 쏠리고 있습니다. ◇ 텐센트·바이트댄스 하반기 또 감원 중국 대표 기술기업들이 연일 몸집 줄이기에 나서고 있습니다. 월스트리트저널은 텐센트와 바이트댄스를 비롯한 빅테크 기업들이 지난해 수만명의 인력을 줄인데 이어 또 한번 대규모 구조조정을 준비하고 있다고 전했는데요. 과거 수익성이 없는 사업을 정리하기 위해 감원에 나섰다면 최근에는 중국 경제가 고비를 겪으면서 비용을 줄이기 위해 몸집을 줄이고 있다고 설명했습니다. 특히 최근 당국이 빅테크 때리기 기조를 거둬들이고 있다는 점에서 거시적 위기가 새로운 숙제로 떠올랐다고 분석했는데요. 이미 상반기 전 부문에 걸쳐 인력의 10%가 넘게 정리한 텐센트는 하반기 대규모 추가 감원을 예고한데 더해 일부 사업의 전면 철수까지 검토 중인 것으로 알려졌는데요. 그간 규제 철퇴에 허덕이던 중국 빅테크들이 경기 둔화라는 악재까지 겹치면서 고민이 깊어지는 모습입니다. 지금까지 글로벌 비즈였습니다.<|eot_id|><|start_header_id|>assistant<|end_header_id|>

{"stock_related":true,"summary":"가트너는 경기 둔화, 중국 봉쇄 여파, 인플레이션에 따른 소비 위축으로 올해 전 세계 스마트폰 판매량이 전년 대비 7% 감소한 14억6천만 대에 그칠 것으로 전망했다. 특히 중국 판매량은 18% 감소할 것으로 예상돼 애플 등 스마트폰 제조사와 TSMC 등 반도체 업체의 실적 부담이 커질 수 있다. EU는 가상자산 거래 시 고객 신원 확인과 거래 추적을 의무화하는 자금세탁 방지 규제에 잠정 합의했으며, 이는 코인베이스 등 거래소의 준법·개인정보 관리 비용을 높일 가능성이 있다. 한편 스피릿항공 인수전에서는 프론티어항공과 제트블루항공이 인수가를 경쟁적으로 높이면서 스피릿의 주주투표가 재차 연기됐다. 텐센트와 바이트댄스 등 중국 빅테크는 경기 둔화와 비용 절감을 이유로 추가 감원 및 비핵심 사업 철수를 검토 중이다.","positive_stocks":["스피릿항공"],"positive_keywords":["인수가 경쟁","주주투표 연기","경영권 프리미엄","인수 가능성 확대"],"positive_reasons":"프론티어항공과 제트블루항공이 인수가를 경쟁적으로 높이고 있어 스피릿항공 주주에게 더 높은 인수 프리미엄이 제시될 가능성이 있다. 다만 최종 인수 주체와 미국 규제 승인 여부에 따라 주가 변동성이 커질 수 있다.","negative_stocks":["애플","TSMC","엔비디아","코인베이스","제트블루항공","프론티어그룹","텐센트 홀딩스"],"negative_keywords":["스마트폰 판매량 7% 감소","중국 스마트폰 판매 18% 감소","부품 수요 둔화","가상자산 거래 신원확인 의무","준법 비용 증가","인수가 상승","중국 경기 둔화","대규모 감원"],"negative_reasons":"스마트폰 수요 감소는 애플의 아이폰 판매와 TSMC의 모바일·반도체 주문에 직접적인 부담으로 작용할 수 있으며, 엔비디아도 일부 모바일·소비자 전자기기 관련 수요 둔화와 전반적인 반도체 업황 약화의 영향을 받을 수 있다. EU 가상자산 규제는 코인베이스의 고객확인, 거래 모니터링, 개인정보 관리 및 시스템 구축 비용을 높이고 거래 편의성을 낮출 가능성이 있다. 제트블루항공과 프론티어그룹은 스피릿 인수가격 상승에 따른 재무 부담, 통합 비용, 반독점 심사 리스크가 커질 수 있다. 텐센트는 중국 경기 둔화로 광고·게임·핀테크 등 주요 사업의 성장성이 약화될 수 있고, 추가 감원은 비용 절감 효과가 있는 반면 사업 철수와 수익성 악화 우려를 반영한다."}<|eot_id|><|start_header_id|>assistant<|end_header_id|>

[transformers] Both `max_new_tokens` (=1024) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[response]: Summary:

글로벌 경제는 2023년에도 지속적인 침체로 접어들 것으로 전망되며, 미국의 연방준비제도(Fed)는 인플레이션을 억제하기 위해 추가적인 금리 인상 전망이다. 이는 세계 각국의 경제성장 둔화와 함께 국제통화기금(IMF)의 세계 경제 성장률 전망을 낮추는 요인이다.

Stock-related:

stock_related: True

Positive Stocks:

positive_stocks:
-
  stock:
    - "AAPL" (Apple Inc.)
    - "MSFT" (Microsoft Corporation)
    - "AMZN" (Amazon.com Inc.)
    - "GOOGL" (Alphabet Inc.)
    - "V" (Visa Inc.)
  positive_keywords:
    - "디지털화"
    - "클라우드 컴퓨팅"
    - "온라인 쇼핑"
    - "데이터 분석"
    - "디지털 결제"
  positive_reasons:
    - "글로벌 경제 침체에도 불구하고, 위의 기업들은 디지털화와 클라우드 컴퓨팅, 온라인 쇼핑 등에 대한 수요가 상대적으로 높아질 가능성이 있다. 특히, 'AAPL'의 Apple은 개인용 컴퓨터와 관련 제품의 수요가 상대적으로 안정적일 수 있으며, 'MSFT'의 Microsoft는 기업 클라우드 솔루션에 대한 수요가 증가할 수 있다. 'AMZN'의 Amazon은 온라인 쇼핑에 대한 수요가 지속될 것이고, 'GOOGL'의 Alphabet(구글)은 데이터 분석 및 디지털 마케팅 서비스에 대한 수요가 높아질 수 있다. 'V'의 Visa는 디지털 결제의 확산으로 인해 수요가 증가할 수 있다."

Negative Stocks:

negative_stocks:
-
  stock:
    - "NIO" (NIO Inc.)
    - "LYFT" (Lyft, Inc.)
    - "ZM" (Zoom Video Communications, Inc.)
  negative_keywords:
    - "전기차 수요 감소"
    - "교통 수요 감소"
    - "비대면 회의 및 이벤트의 감소"
  negative_reasons:
    - "전기차 시장은 경제 침체로 인해 소비자 지출 감소와 연계되어 수요가 감소할 수 있다. 'NIO'는 중국 전기차 시장의 주요 기업이다. 'LYFT'는 교통 수요가 감소함에 따라 라이드셰어링 서비스에 대한 수요가 줄어들 수 있다. 'ZM'의 Zoom은 비대면 회의 및 이벤트의 증가로 인해 주가가 상승했지만, 경제 침체로 인해 회의 및 이벤트의 감소로 인해 수요가 감소할 수 있다."

이 뉴스 내용은 글로벌 경제 침체 전망과 미국 연방준비제도의 추가 금리 인상에 대한 내용을 다루고 있습니다. 이는 전반적으로 경제에 부정적인 영향을 미칠 것으로 보입니다.

주식 시장에서는 디지털화와 클라우드 컴퓨팅, 온라인 쇼핑, 데이터 분석, 디지털 결제 등의 분야에 투자한 기업들이 상대적으로 긍정적인 반응을 보일 수 있습니다. 반면 전기차, 교통 서비스, 비대면 회의 플랫폼 등 경제 침체로 인해 수요가 감소할 가능성이 있는 분야의 기업들은 부정적인 영향을 받을 수 있습니다.

주요 키워드:
- 글로벌 경제 침체
- 미국 연방준비제도(Fed) 금리 인상
- 디지털화
- 클라우드 컴퓨팅
- 온라인 쇼핑
- 데이터 분석
- 디지털 결제
- 전기차
- 교통 서비스
- 비대면 회의 플랫폼

주식 연관성:
- 긍정적 영향 예상 종목: AAPL(Apple), MSFT(Microsoft), AMZN(Amazon), GOOGL(Alphabet), V(Visa)
- 부정적 영향 예상 종목: NIO(NIO Inc.), LYFT(Lyft), ZM(Zoom Video Communications)
====================================================================================================
[prompt]: <|begin_of_text|><|start_header_id|>system<|end_header_id|>

당신은 금융/경제 뉴스의 핵심내용을 요약해 설명하고,
특정 상장 종목에 미치는 긍정/부정 영향여부, 이유, 근거를 분석하는 금융/경제 분석 전문가입니다.

다음 출력지시사항을 지켜주세요.
1. 뉴스와 종목간의 연관성을 발견할 수 없다면:
    - stock_related를 False로 작성하세요.
    - summary에 뉴스의 요약을 작성하세요.
2. 뉴스와 종목간의 연관성을 발견했다면:
    - stock_related를 True로 작성하세요.
    - summary에 뉴스의 요약을 작성하세요.
    - 긍정영향이 예상되는 종목이 있다면, positive_stocks, positive_keywords, positive_reasons를 작성하세요.
    - 부정영향이 예상되는 종목이 있다면, negative_stocks, negative_keywords, negative_reasons를 작성하세요.
    - 값이 없는 경우 빈 문자열(''), 빈 리스트([])로 작성하세요.<|eot_id|><|start_header_id|>user<|end_header_id|>

[label] :
야놀자 포커스미디어와 ‘동네가게 오래함께’ 캠페인 진행
사진 야놀자 제공 야놀자가 포커스미디어와 동네가게 오래함께 캠페인을 진행한다고 4일 밝혔다. 이번 캠페인은 지역 내 우수 소상공인을 발굴하고 이들을 위한 맞춤형 광고를 제작해 해당 지역 내 홍보를 지원한다. 총 14억 원 규모의 광고 제작 및 송출 비용은 양사가 전액 부담한다. 야놀자는 제휴점을 대상으로 사연을 공모하고 상권 빅데이터 분석을 진행해 지원 대상을 선정한다. 포커스미디어는 전국 5천800여 개 아파트에서 하루 800만 시청자를 확보한 엘리베이터 TV 등 자체 인프라를 통해 광고를 송출한다. 캠페인의 첫 광고는 서울시 노원구 동작구를 시작으로 오는 11일부터 2개월 간 방영되며 연말까지 대상 범위를 지속 확대할 예정이다. 야놀자 관계자는 소상공인들에게 직접적인 도움을 줄 수 있는 이번 캠페인을 통해 지역사회와 상생하고 지역경제 활성화에도 기여할 것으로 기대한다 면서 지역 내 우수 소상공인들의 인지도를 제고하고 매출 증대에도 기여할 수 있도록 캠페인의 성공적인 진행을 위한 지원을 아끼지 않을 계획 이라고 말했다.<|eot_id|><|start_header_id|>assistant<|end_header_id|>

{"stock_related":false,"summary":"야놀자와 포커스미디어가 총 14억 원을 투입해 지역 우수 소상공인을 지원하는 ‘동네가게 오래함께’ 캠페인을 진행한다. 야놀자는 제휴점 대상 사연 공모와 상권 빅데이터 분석을 통해 지원 대상을 선정하고, 포커스미디어는 전국 약 5,800개 아파트의 엘리베이터 TV 등 자체 매체를 활용해 맞춤형 광고를 송출한다. 첫 광고는 서울 노원구와 동작구에서 11일부터 2개월간 방영되며, 연말까지 대상 지역을 확대할 예정이다. 이번 캠페인은 소상공인의 인지도와 매출 증대, 지역경제 활성화를 목표로 하지만, 기사 내용만으로 특정 상장사 실적이나 주가에 직접적인 영향을 판단하기는 어렵다.","positive_stocks":[],"positive_keywords":[],"positive_reasons":"","negative_stocks":[],"negative_keywords":[],"negative_reasons":""}<|eot_id|><|start_header_id|>assistant<|end_header_id|>

[transformers] Both `max_new_tokens` (=1024) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[response]: Summary:

글로벌 경제는 2023년에도 지속적인 침체로 접어들 것으로 전망되며, 미국의 연방준비제도(Fed)는 인플레이션을 억제하기 위해 추가적인 금리 인상 전망이다. 이는 세계 각국의 경제성장 둔화와 함께 국제통화기금(IMF)의 세계 경제 성장률 전망을 낮추는 요인이다.

Stock-related:

stock_related: True

Positive Stocks:

positive_stocks:
-
  stock:
    - "AAPL" (Apple Inc.)
    - "MSFT" (Microsoft Corporation)
    - "AMZN" (Amazon.com Inc.)
    - "GOOGL" (Alphabet Inc.)
    - "V" (Visa Inc.)
  positive_keywords:
    - "디지털화"
    - "클라우드 컴퓨팅"
    - "온라인 쇼핑"
    - "데이터 분석"
    - "디지털 결제"
  positive_reasons:
    - "글로벌 경제 침체에도 불구하고, 위의 기업들은 디지털화와 클라우드 컴퓨팅, 온라인 쇼핑 등에 대한 수요가 상대적으로 높아질 가능성이 있다. 특히, 'AAPL'의 Apple은 개인용 컴퓨터와 관련 제품의 수요가 상대적으로 안정적일 수 있으며, 'MSFT'의 Microsoft는 기업 클라우드 솔루션에 대한 수요가 증가할 수 있다. 'AMZN'의 Amazon은 온라인 쇼핑에 대한 수요가 지속될 것이고, 'GOOGL'의 Alphabet(구글)은 데이터 분석 및 디지털 마케팅 서비스에 대한 수요가 높아질 수 있다. 'V'의 Visa는 디지털 결제의 확산으로 인해 수요가 증가할 수 있다."

Negative Stocks:

negative_stocks:
-
  stock:
    - "NIO" (NIO Inc.)
    - "LYFT" (Lyft, Inc.)
    - "ZM" (Zoom Video Communications, Inc.)
  negative_keywords:
    - "전기차 수요 감소"
    - "교통 수요 감소"
    - "비대면 회의 및 이벤트의 감소"
  negative_reasons:
    - "전기차 시장은 경제 침체로 인해 소비자 지출 감소와 연계되어 수요가 감소할 수 있다. 'NIO'는 중국 전기차 시장의 주요 기업이다. 'LYFT'는 교통 수요가 감소함에 따라 라이드셰어링 서비스에 대한 수요가 줄어들 수 있다. 'ZM'의 Zoom은 비대면 회의 및 이벤트의 증가로 인해 주가가 상승했지만, 경제 침체로 인해 회의 및 이벤트의 감소로 인해 수요가 감소할 수 있다."

이 뉴스 내용은 글로벌 경제 침체 전망과 미국 연방준비제도의 추가 금리 인상에 대한 내용을 다루고 있습니다. 이는 전반적으로 경제에 부정적인 영향을 미칠 것으로 보입니다.

주식 시장에서는 디지털화와 클라우드 컴퓨팅, 온라인 쇼핑, 데이터 분석, 디지털 결제 등의 분야에 투자한 기업들이 상대적으로 긍정적인 반응을 보일 수 있습니다. 반면 전기차, 교통 서비스, 비대면 회의 플랫폼 등 경제 침체로 인해 수요가 감소할 가능성이 있는 분야의 기업들은 부정적인 영향을 받을 수 있습니다.

주요 키워드:
- 글로벌 경제 침체
- 미국 연방준비제도(Fed) 금리 인상
- 디지털화
- 클라우드 컴퓨팅
- 온라인 쇼핑
- 데이터 분석
- 디지털 결제
- 전기차
- 교통 서비스
- 비대면 회의 플랫폼

주식 연관성:
- 긍정적 영향 예상 종목: AAPL(Apple), MSFT(Microsoft), AMZN(Amazon), GOOGL(Alphabet), V(Visa)
- 부정적 영향 예상 종목: NIO(NIO Inc.), LYFT(Lyft), ZM(Zoom Video Communications)
====================================================================================================
[prompt]: <|begin_of_text|><|start_header_id|>system<|end_header_id|>

당신은 금융/경제 뉴스의 핵심내용을 요약해 설명하고,
특정 상장 종목에 미치는 긍정/부정 영향여부, 이유, 근거를 분석하는 금융/경제 분석 전문가입니다.

다음 출력지시사항을 지켜주세요.
1. 뉴스와 종목간의 연관성을 발견할 수 없다면:
    - stock_related를 False로 작성하세요.
    - summary에 뉴스의 요약을 작성하세요.
2. 뉴스와 종목간의 연관성을 발견했다면:
    - stock_related를 True로 작성하세요.
    - summary에 뉴스의 요약을 작성하세요.
    - 긍정영향이 예상되는 종목이 있다면, positive_stocks, positive_keywords, positive_reasons를 작성하세요.
    - 부정영향이 예상되는 종목이 있다면, negative_stocks, negative_keywords, negative_reasons를 작성하세요.
    - 값이 없는 경우 빈 문자열(''), 빈 리스트([])로 작성하세요.<|eot_id|><|start_header_id|>user<|end_header_id|>

[label] :
삼성바이오로직스 MSD와 2768억원 위탁생산계약 체결
미국 제약기업과 의약품 위탁생산 공급계약 지난해 9월 공시된 본 계약 체결 삼성바이오로직스 3공장 전경. ⓒ삼성바이오로직스 데일리안 이홍석 기자 삼성바이오로직스는 4일 공시를 통해 미국 제약기업 MSD MSD International Business GmbH 와 2768억2938만원 규모의 의약품 위탁생산 공급계약을 체결했다고 밝혔다. 이번 계약은 최근 매출액 대비 17.65% 규모로 계약기간은 2022년 7월 1일부터 2028년 12월 31일이다. 상기 계약금액은 고객사의 수요증가에 따라 3억8186만 달러로 증가할 수 있다. 이번 계약건은 지난해 9월 29일 공시된 ‘투자판단 관련 주요경영사항’에 대한 본계약 체결건이다. 당시 삼성바이오로직스는 MSD 위탁생산계약 의향서를 체결했으며 계약금은 491억원이라고 공시했다.<|eot_id|><|start_header_id|>assistant<|end_header_id|>

{"stock_related":true,"summary":"삼성바이오로직스가 미국 제약사 MSD International Business GmbH와 2,768억2938만원 규모의 의약품 위탁생산(CMO) 공급계약을 체결했다. 계약기간은 2022년 7월 1일부터 2028년 12월 31일까지이며, 계약금액은 고객사 수요 증가에 따라 최대 3억8186만 달러까지 확대될 수 있다. 이번 계약은 지난해 9월 공시한 491억원 규모의 위탁생산 의향서가 본계약으로 전환된 것이다.","positive_stocks":["삼성바이오로직스"],"positive_keywords":["MSD 위탁생산 계약","CMO 수주","계약금액 2768억원","계약기간 2028년까지","수요 증가 시 3억8186만 달러로 확대 가능","장기 매출 가시성"],"positive_reasons":"삼성바이오로직스의 최근 매출액 대비 17.65%에 해당하는 대규모 계약으로, 장기간에 걸쳐 안정적인 생산 물량과 매출을 확보했다는 점에서 긍정적이다. 특히 의향서에서 본계약으로 전환되면서 수주 이행 가능성이 확인됐고, MSD의 수요 증가에 따라 계약 규모가 추가 확대될 수 있어 향후 공장 가동률과 매출 성장에 기여할 수 있다. 글로벌 대형 제약사를 고객사로 확보했다는 점도 삼성바이오로직스의 대형 바이오의약품 위탁생산 경쟁력과 고객 기반을 강화하는 요인이다.","negative_stocks":[],"negative_keywords":[],"negative_reasons":""}<|eot_id|><|start_header_id|>assistant<|end_header_id|>


[response]: Summary:

글로벌 경제는 2023년에도 지속적인 침체로 접어들 것으로 전망되며, 미국의 연방준비제도(Fed)는 인플레이션을 억제하기 위해 추가적인 금리 인상 전망이다. 이는 세계 각국의 경제성장 둔화와 함께 국제통화기금(IMF)의 세계 경제 성장률 전망을 낮추는 요인이다.

Stock-related:

stock_related: True

Positive Stocks:

positive_stocks:
-
  stock:
    - "AAPL" (Apple Inc.)
    - "MSFT" (Microsoft Corporation)
    - "AMZN" (Amazon.com Inc.)
    - "GOOGL" (Alphabet Inc.)
    - "V" (Visa Inc.)
  positive_keywords:
    - "디지털화"
    - "클라우드 컴퓨팅"
    - "온라인 쇼핑"
    - "데이터 분석"
    - "디지털 결제"
  positive_reasons:
    - "글로벌 경제 침체에도 불구하고, 위의 기업들은 디지털화와 클라우드 컴퓨팅, 온라인 쇼핑 등에 대한 수요가 상대적으로 높아질 가능성이 있다. 특히, 'AAPL'의 Apple은 개인용 컴퓨터와 관련 제품의 수요가 상대적으로 안정적일 수 있으며, 'MSFT'의 Microsoft는 기업 클라우드 솔루션에 대한 수요가 증가할 수 있다. 'AMZN'의 Amazon은 온라인 쇼핑에 대한 수요가 지속될 것이고, 'GOOGL'의 Alphabet(구글)은 데이터 분석 및 디지털 마케팅 서비스에 대한 수요가 높아질 수 있다. 'V'의 Visa는 디지털 결제의 확산으로 인해 수요가 증가할 수 있다."

Negative Stocks:

negative_stocks:
-
  stock:
    - "NIO" (NIO Inc.)
    - "LYFT" (Lyft, Inc.)
    - "ZM" (Zoom Video Communications, Inc.)
  negative_keywords:
    - "전기차 수요 감소"
    - "교통 수요 감소"
    - "비대면 회의 및 이벤트의 감소"
  negative_reasons:
    - "전기차 시장은 경제 침체로 인해 소비자 지출 감소와 연계되어 수요가 감소할 수 있다. 'NIO'는 중국 전기차 시장의 주요 기업이다. 'LYFT'는 교통 수요가 감소함에 따라 라이드셰어링 서비스에 대한 수요가 줄어들 수 있다. 'ZM'의 Zoom은 비대면 회의 및 이벤트의 증가로 인해 주가가 상승했지만, 경제 침체로 인해 회의 및 이벤트의 감소로 인해 수요가 감소할 수 있다."

이 뉴스 내용은 글로벌 경제 침체 전망과 미국 연방준비제도의 추가 금리 인상에 대한 내용을 다루고 있습니다. 이는 전반적으로 경제에 부정적인 영향을 미칠 것으로 보입니다.

주식 시장에서는 디지털화와 클라우드 컴퓨팅, 온라인 쇼핑, 데이터 분석, 디지털 결제 등의 분야에 투자한 기업들이 상대적으로 긍정적인 반응을 보일 수 있습니다. 반면 전기차, 교통 서비스, 비대면 회의 플랫폼 등 경제 침체로 인해 수요가 감소할 가능성이 있는 분야의 기업들은 부정적인 영향을 받을 수 있습니다.

주요 키워드:
- 글로벌 경제 침체
- 미국 연방준비제도(Fed) 금리 인상
- 디지털화
- 클라우드 컴퓨팅
- 온라인 쇼핑
- 데이터 분석
- 디지털 결제
- 전기차
- 교통 서비스
- 비대면 회의 플랫폼

주식 연관성:
- 긍정적 영향 예상 종목: AAPL(Apple), MSFT(Microsoft), AMZN(Amazon), GOOGL(Alphabet), V(Visa)
- 부정적 영향 예상 종목: NIO(NIO Inc.), LYFT(Lyft), ZM(Zoom Video Communications)
====================================================================================================

# 추론

In [33]:
# 뉴스 1건 입력받아 추론하는 함수

def inference(news) :
    messages = [
        {'role': 'system', 'content': '''
당신은 금융/경제 뉴스의 핵심내용을 요약해 설명하고,
특정 상장 종목에 미치는 긍정/부정 영향여부, 이유, 근거를 분석하는 금융/경제 분석 전문가입니다.

다음 출력지시사항을 지켜주세요.
1. 뉴스와 종목간의 연관성을 발견할 수 없다면:
    - stock_related를 False로 작성하세요.
    - summary에 뉴스의 요약을 작성하세요.
2. 뉴스와 종목간의 연관성을 발견했다면:
    - stock_related를 True로 작성하세요.
    - summary에 뉴스의 요약을 작성하세요.
    - 긍정영향이 예상되는 종목이 있다면, positive_stocks, positive_keywords, positive_reasons를 작성하세요.
    - 부정영향이 예상되는 종목이 있다면, negative_stocks, negative_keywords, negative_reasons를 작성하세요.
    - 값이 없는 경우 빈 문자열(''), 빈 리스트([])로 작성하세요.
'''},  # 시스템 지시문
        {'role': 'user', 'content': news}
    ]
    
    # messages를 채팅 프롬프트 문자열로 반환
    prompt = tokenizer.apply_chat_template(messages, tokenize=False)
    outputs = pipe(prompt, max_new_tokens=1024, eos_token_id=eos_token, do_sample=False)
    assistant_start = len(prompt) # 입력 구간 이후 생성 결과만 사용
    # 프롬프트 이후(생성된 부분)만 반환
    return outputs[0]['generated_text'][assistant_start:].strip()

In [34]:
news = ''' 
엔화, 반년 만에 최강세…"추가 상승 가능성 크다"

달러당 153엔대까지 상승
美日 추가 개입 가능성
금리인상 전망 등 영향
일본 엔화 가치가 달러당 153엔대까지 가파르게 상승했다. 지난 2월 중순 이후 반년 만에 가장 높은 수준이다. 일본 정부와 일본은행(BOJ)의 외환시장 개입 당시에도 넘지 못했던 달러당 155엔 선을 돌파한 이후에도 오름세가 이어지고 있다. 올해 고점인 152엔대까지 상승할 여지가 있다는 관측이 나온다.

8일 니혼게이자이신문(닛케이)에 따르면 이날 오전 도쿄 외환시장에서 엔화 가치는 장중 달러당 153엔대까지 뛰었다. 전날 달러당 155엔 선을 넘어섰으나, 이후에도 매수세가 지속됐다. 달러당 153엔대는 지난 2월 중순 이후 최고 수준이다. 지난 4~5월과 7월, 일본 당국이 외환시장 개입에 나섰을 당시에도 이 수준은 넘지 못했다.

이번 엔화 강세에는 미국과 일본 통화당국이 추가로 외환시장에 개입할 수 있다는 가능성과, BOJ의 금리 인상 가속화 전망 등이 복합적으로 영향을 미친 것으로 보인다고 닛케이는 짚었다.

먼저 외환시장에서는 이달 이후 미·일 통화당국이 엔화 약세 시정을 위한 구체적인 조치를 취할 것이라는 전망이 나오고 있다. 스콧 베선트 미국 재무부 장관은 지난달 30일 우에다 가즈오 BOJ 총재와 만나 "엔화의 대폭적인 저평가에 대처하기 위해 일본이 단호한 시장·금융 정책상 조치를 취하는 것을 강력히 지지한다"고 발언한 바 있다. 가타야마 사쓰키 일본 재무상도 과도한 엔화 약세가 이어질 경우 미국과 협조해 추가 개입에 나설 것을 시사해왔다.

BOJ의 금리 인상 속도가 빨라질 것이라는 전망도 엔화 매수세를 부추기고 있다. 시장에서는 BOJ가 오는 17~18일 열리는 금융정책결정회의에서 기준금리를 0.25%포인트 인상할 가능성을 선반영하고 있다. 여기에 시장은 추가 금리 상승 가능성에 베팅하고 있다. 닛케이는 "이번 기준금리 인상 이후에도 3개월에 한 번 정도의 속도로 금리 인상을 이어가거나, 최종 기준금리 목표치가 상향 조정될 것이라는 전망이 확산하고 있다"고 전했다.

여기에 중동 정세 긴장이 완화될 것이라는 기대감도 엔화 강세에 힘을 보태고 있다. 에스마일 바가이 이란 외무부 대변인은 전날 호르무즈 해협의 임시 항로를 둘러싼 오만과의 협상이 최종 단계에 도달했으며, 빠르면 며칠 내로 합의에 이를 전망이라고 밝힌 바 있다. 이로 인해 안전자산 선호 현상으로 나타났던 '유사시 달러 매수 현상'도 주춤해진 분위기다.

엔화 강세가 나타나면서 엔저에 베팅하던 투자자들의 포지션 청산도 가속화되고 있다. 엔화 강세로 손실이 커지자, 달러를 팔고 엔화를 되사들이면서 상승세를 더 부추기는 모습이다. 미쓰비시UFJ신탁은행 자금·외환부의 오카다 유스케 상급조사역은 "헤지펀드(같은 단기 투기 세력)뿐만 아니라 중장기적 관점을 가지고 거래하는 주체들도 엔 매도·달러 매수 포지션을 청산하는 등, 최근 추세가 변화하고 있다"고 닛케이에 전했다.

여기에 달러당 155엔 선이 무너지면서 손절매까지 잇따랐다. 블룸버그통신은 익명의 트레이더를 인용해 155엔 아래에 설정돼 있던 대규모 손절매 주문이 엔화가 상승하며 실행됐고, 옵션 딜러들도 달러 매도에 나서면서 상승세에 힘을 실었다고 분석했다.

이렇게 복합적인 요인들이 겹치면서 이번 엔화 급상승은 지난번 당국의 직접적인 외환 시장 개입에 따른 상승과는 성격이 다르다는 평가도 나온다. 반 루 러셀인베스트먼츠 글로벌 채권·외환 솔루션 전략 책임자는 "첫 번째 시장 개입의 효과는 이미 사라진 것으로 보인다. 이번 두 번째 상승은 시장 자체의 힘으로 나타나는 것으로 보고, 그렇기에 이번 움직임이 훨씬 더 중요하다"고 블룸버그에 전했다.

추가 상승 여력이 있다는 전망도 나왔다. 우에노 다이사쿠 미쓰비시UFJ·모건스탠리증권 수석 외환전략가는 "심리적 저항선으로 볼 수 있는 155엔을 넘어섰기에 단기적으로는 엔화 매수세가 유입되기 쉽다"고 닛케이에 전했다. 그러면서 "당분간은 올해 고점인 152엔대까지 상승 여지가 있을 것"이라고 덧붙였다.
'''
inference(news)

[transformers] Both `max_new_tokens` (=1024) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

'stock_related: True\n\nsummary:\n일본 엔화가 달러당 153엔대까지 상승하며 반년 만에 최강세를 기록했다. 이번엔화 강세는 미국과 일본 통화당국이 추가 외환시장 개입 가능성과, 일본은행(BOJ)의 금리 인상 가속화 전망 등이 복합적으로 작용한 것으로 보인다.\n\npositive_stocks:\n- 일본은행(BOJ): 금리 인상 전망이 엔화 매수세를 부추기고 있다.\n- 일본 정부: 외환시장 개입 가능성 증가로 엔화 가치 상승에 긍정적 영향.\n\npositive_keywords:\n- 외환시장 개입 가능성\n- 금리 인상 전망\n- 안전자산 선호 현상 완화\n\npositive_reasons:\n외환시장 개입 가능성과 금리 인상 전망은 엔화에 대한 수요를 높이고, 안전자산 선호 현상이 완화되면서 매수세가 지속될 가능성이 높아졌다. 특히 BOJ의 금리 인상 속도 가속화는 엔화에 대한 투자 유인을 강화할 것이다.\n\nnegative_stocks:\n- 엔저: 엔화 강세로 주가가 하락할 가능성이 있다.\n- 달러 관련 자산: 엔화 강세로 달러 관련 자산의 가치가 하락할 수 있다.\n\nnegative_keywords:\n- 엔화 강세로 인한 엔저 하락\n- 달러 매도 압력\n\nnegative_reasons:\n엔화가 강세를 보이면서 엔저에 투자하던 투자자들이 포지션을 청산하고 달러로 전환하는 추세가 나타나고 있다. 이는 엔저의 가치를 낮추고, 달러 매도 압력을 가중시킬 수 있다.\n\n추가적으로, 달러당 155엔 선이 무너지면서 일부 대규모 손절매 주문이 실행되었고, 옵션 딜러들도 달러 매도에 나서 상승세에 힘을 실었다는 점도 주의할 필요가 있다. 하지만 장기적으로는 미국과 일본 통화당국이 엔화 약세를 정정하려는 구체적인 조치가 취해지지 않는 한, 엔화 강세는 지속될 가능성이 높다.'

In [35]:
news = ''' 
국고채 금리, 유가 상승에 낙폭 되돌리며 상승 마감(종합)

(서울=연합뉴스) 강수지 기자 = 8일 국고채 금리는 장중 하락분을 반납하고 소폭 상승 마감했다.

외국인 국채선물 순매수에도 미국과 이란 간 교전이 재개되면서 국제유가가 배럴당 100달러에 육박한 영향을 받았다.

이날 서울 채권시장에서 3년 만기 국고채 금리는 전 거래일보다 0.1bp(1bp=0.01%포인트) 오른 연 3.901%에 장을 마쳤다.

10년물 금리는 연 4.401%로 1.6bp 상승했다. 5년물과 2년물은 각각 0.7bp, 0.1bp 상승해 연 4.127%, 연 3.721%에 마감했다.

20년물은 연 4.560%로 0.7bp 내렸다. 30년물과 50년물은 각각 0.4bp, 0.3bp 상승해 연 4.635%, 연 4.543%를 기록했다.

이날 3년 국채선물은 전일 대비 1틱 하락한 103.11에, 10년 국채선물은 4틱 하락한 105.13에 거래를 마쳤다. 외국인 순매수에 장중 강세폭을 확대했으나, 지정학적 위기로 인한 유가 우려에 상승분을 반납했다.

외국인은 3년 선물을 4천556계약, 10년 선물을 1천376계약 순매수했다.

간밤 미국 금융시장이 노동절로 휴장한 가운데 국내 채권시장은 외국인 국채선물 매수에 주목하며 장중 강세를 나타냈다.

그러나 유럽시장 개장 무렵 국제유가 벤치마크인 브렌트유가 배럴당 100달러에 육박하면서 국내 채권시장은 강세를 반납했다. 브렌트유 선물 가격은 이날 오후 1.4%가량 오른 배럴당 98.65달러 수준에서 거래되고 있다.

이날 발표된 한국의 2분기 실질 국내총생산(GDP) 성장률 잠정치는 전분기 대비 0.6%, 전년 대비 3.7%로 속보치와 동일했다. 명목 GDP는 전기 대비 9.2%, 전년 대비 26.4% 성장했다.

증권사의 한 채권 중개인은 "이날 채권은 강세를 보였는데, 미국과 이란 충돌 우려에 유가가 오르면서 강세를 되돌렸다"며 "유가와 미국 금리 움직임이 중요한 가운데 다음주 있을 국채선물 롤오버(월물 교체)에서 외국인 움직임이 중요할 듯하다"고 말했다.
'''
inference(news)

[transformers] Both `max_new_tokens` (=1024) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

'stock_related: True\n\nsummary:\n국내 채권시장은 외국인 국채선물 매수에 힘입어 장중 강세를 보였으나, 미국과 이란 간 교전 재개로 인한 국제유가 상승 우려로 인해 하락 분을 반납하고 소폭 상승 마감했다. 3년, 10년 국고채 금리는 각각 0.1%, 1.6% 상승했으며, 20년물은 0.7% 내렸지만 30년과 50년물은 각각 0.4%, 0.3% 상승했다.\n\npositive_stocks:\n- 외국인 순매수가 주된 원동력이었던 3년, 10년 국채선물에 대한 직접적인 영향을 받는 채권 관련 종목들이 긍정적일 수 있다.\n\npositive_keywords:\n- 외국인 순매수\n- 국채선물 롤오버 (월물 교체)\n\npositive_reasons:\n- 외국인 순매수가 채권시장에 지속적인 강세를 주입할 수 있기 때문에, 외국인 투자에 의존도가 높은 채권 관련 종목들은 긍정적 영향을 받을 수 있다. \n- 다음주 국채선물 롤오버 시 외국인의 투자 전략과 움직임이 주가에 영향을 미칠 수 있다.\n\nnegative_stocks:\n- 유가 상승에 따른 금리 상승 압력이 채권시장에 부정적 영향을 미칠 수 있는 종목들\n\nnegative_keywords:\n- 국제유가 상승\n- 지정학적 위기\n\nnegative_reasons:\n- 국제유가 상승으로 인해 지정학적 위기가 가중되면, 채권시장의 강세를 반납하게 되고 금리 상승 압력이 커질 수 있다. 이는 금융시스템에 부담을 주어 채권 관련 종목들의 가치를 하락시킬 수 있다.\n\n이 뉴스에 직접적으로 영향을 받는 특정 상장 종목을 명확히 지목하기는 어렵지만, 금리와 채권시장 동향이 주식시장 전반에 미치는 영향은 상당할 수 있다. 특히 금융, 부동산, 소비재 등과 같은 부채 비율이 높은 산업에 더 큰 영향을 줄 수 있다.'

# Base 모델과 비교

In [36]:
from transformers import AutoModelForCausalLM, pipeline

base_model_id = 'NCSOFT/Llama-VARCO-8B-Instruct' # 사전 학습 모델명

base_model = AutoModelForCausalLM.from_pretrained(
    base_model_id,
    dtype = torch.bfloat16, # 가중치 로딩 dtype(bf16)
    device_map= 'auto'      # 환경에 맞춰 CPU / GPU 자동 배치
)

base_pipe = pipeline('text-generation', model=finetuned_model,tokenizer=tokenizer)

# 베이스 모델과 LoRA 파인튜닝 모델의 응답과 정답 비교
for idx, (prompt, label) in enumerate(zip(prompt_list[10:13], label_list[10:13])):
    print(f"[샘플 {idx +1}")
    base_resp = test_inference(base_pipe, prompt)
    lora_resp = test_inference(pipe, prompt)
    print(f"[Base - 파인튜닝 전] {base_resp}")
    print(f"[LoRA - 파인튜닝 후] {lora_resp}")
    print(f"[Label] {label}")
    print("=" * 100)

Loading weights:   0%|          | 0/291 [00:00<?, ?it/s]

[transformers] Both `max_new_tokens` (=1024) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[샘플 1

[transformers] Both `max_new_tokens` (=1024) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=1024) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[Base - 파인튜닝 전] Summary:

글로벌 경제는 2023년에도 지속적인 침체로 접어들 것으로 전망되며, 미국의 연방준비제도(Fed)는 인플레이션을 억제하기 위해 추가적인 금리 인상 전망이다. 이는 세계 각국의 경제성장 둔화와 함께 국제통화기금(IMF)의 세계 경제 성장률 전망을 낮추는 요인이다.

Stock-related:

stock_related: True

Positive Stocks:

positive_stocks:
-
  stock:
    - "AAPL" (Apple Inc.)
    - "MSFT" (Microsoft Corporation)
    - "AMZN" (Amazon.com Inc.)
    - "GOOGL" (Alphabet Inc.)
    - "V" (Visa Inc.)
  positive_keywords:
    - "디지털화"
    - "클라우드 컴퓨팅"
    - "온라인 쇼핑"
    - "데이터 분석"
    - "디지털 결제"
  positive_reasons:
    - "글로벌 경제 침체에도 불구하고, 위의 기업들은 디지털화와 클라우드 컴퓨팅, 온라인 쇼핑 등에 대한 수요가 상대적으로 높아질 가능성이 있다. 특히, 'AAPL'의 Apple은 개인용 컴퓨터와 관련 제품의 수요가 상대적으로 안정적일 수 있으며, 'MSFT'의 Microsoft는 기업 클라우드 솔루션에 대한 수요가 증가할 수 있다. 'AMZN'의 Amazon은 온라인 쇼핑에 대한 수요가 지속될 것이고, 'GOOGL'의 Alphabet(구글)은 데이터 분석 및 디지털 마케팅 서비스에 대한 수요가 높아질 수 있다. 'V'의 Visa는 디지털 결제의 확산으로 인해 수요가 증가할 수 있다."

Negative Stocks:

negative_stocks:
-
  stock:
    - "NIO" (NIO Inc.)
    - "LYFT" (Lyft, Inc.)
    - "ZM" (Zoom Video Communications, Inc.)
  negative_keywords:
    - "전기차 수요 감소"
    - "교통 수요 감소"
    - "비대면 회의 및 이벤트의 감소"
  negative_reasons:
    - "전기차 시장은 경제 침체로 인해 소비자 지출 감소와 연계되어 수요가 감소할 수 있다. 'NIO'는 중국 전기차 시장의 주요 기업이다. 'LYFT'는 교통 수요가 감소함에 따라 라이드셰어링 서비스에 대한 수요가 줄어들 수 있다. 'ZM'의 Zoom은 비대면 회의 및 이벤트의 증가로 인해 주가가 상승했지만, 경제 침체로 인해 회의 및 이벤트의 감소로 인해 수요가 감소할 수 있다."

이 뉴스 내용은 글로벌 경제 침체 전망과 미국 연방준비제도의 추가 금리 인상에 대한 내용을 다루고 있습니다. 이는 전반적으로 경제에 부정적인 영향을 미칠 것으로 보입니다.

주식 시장에서는 디지털화와 클라우드 컴퓨팅, 온라인 쇼핑, 데이터 분석, 디지털 결제 등의 분야에 투자한 기업들이 상대적으로 긍정적인 반응을 보일 수 있습니다. 반면 전기차, 교통 서비스, 비대면 회의 플랫폼 등 경제 침체로 인해 수요가 감소할 가능성이 있는 분야의 기업들은 부정적인 영향을 받을 수 있습니다.

주요 키워드:
- 글로벌 경제 침체
- 미국 연방준비제도(Fed) 금리 인상
- 디지털화
- 클라우드 컴퓨팅
- 온라인 쇼핑
- 데이터 분석
- 디지털 결제
- 전기차
- 교통 서비스
- 비대면 회의 플랫폼

주식 연관성:
- 긍정적 영향 예상 종목: AAPL(Apple), MSFT(Microsoft), AMZN(Amazon), GOOGL(Alphabet), V(Visa)
- 부정적 영향 예상 종목: NIO(NIO Inc.), LYFT(Lyft), ZM(Zoom Video Communications)
[LoRA - 파인튜닝 후] Summary:

글로벌 경제는 2023년에도 지속적인 침체로 접어들 것으로 전망되며, 미국의 연방준비제도(Fed)는 인플레이션을 억제하기 위해 추가적인 금리 인상 전망이다. 이는 세계 각국의 경제성장 둔화와 함께 국제통화기금(IMF)의 세계 경제 성장률 전망을 낮추는 요인이다.

Stock-related:

stock_related: True

Positive Stocks:

positive_stocks:
-
  stock:
    - "AAPL" (Apple Inc.)
    - "MSFT" (Microsoft Corporation)
    - "AMZN" (Amazon.com Inc.)
    - "GOOGL" (Alphabet Inc.)
    - "V" (Visa Inc.)
  positive_keywords:
    - "디지털화"
    - "클라우드 컴퓨팅"
    - "온라인 쇼핑"
    - "데이터 분석"
    - "디지털 결제"
  positive_reasons:
    - "글로벌 경제 침체에도 불구하고, 위의 기업들은 디지털화와 클라우드 컴퓨팅, 온라인 쇼핑 등에 대한 수요가 상대적으로 높아질 가능성이 있다. 특히, 'AAPL'의 Apple은 개인용 컴퓨터와 관련 제품의 수요가 상대적으로 안정적일 수 있으며, 'MSFT'의 Microsoft는 기업 클라우드 솔루션에 대한 수요가 증가할 수 있다. 'AMZN'의 Amazon은 온라인 쇼핑에 대한 수요가 지속될 것이고, 'GOOGL'의 Alphabet(구글)은 데이터 분석 및 디지털 마케팅 서비스에 대한 수요가 높아질 수 있다. 'V'의 Visa는 디지털 결제의 확산으로 인해 수요가 증가할 수 있다."

Negative Stocks:

negative_stocks:
-
  stock:
    - "NIO" (NIO Inc.)
    - "LYFT" (Lyft, Inc.)
    - "ZM" (Zoom Video Communications, Inc.)
  negative_keywords:
    - "전기차 수요 감소"
    - "교통 수요 감소"
    - "비대면 회의 및 이벤트의 감소"
  negative_reasons:
    - "전기차 시장은 경제 침체로 인해 소비자 지출 감소와 연계되어 수요가 감소할 수 있다. 'NIO'는 중국 전기차 시장의 주요 기업이다. 'LYFT'는 교통 수요가 감소함에 따라 라이드셰어링 서비스에 대한 수요가 줄어들 수 있다. 'ZM'의 Zoom은 비대면 회의 및 이벤트의 증가로 인해 주가가 상승했지만, 경제 침체로 인해 회의 및 이벤트의 감소로 인해 수요가 감소할 수 있다."

이 뉴스 내용은 글로벌 경제 침체 전망과 미국 연방준비제도의 추가 금리 인상에 대한 내용을 다루고 있습니다. 이는 전반적으로 경제에 부정적인 영향을 미칠 것으로 보입니다.

주식 시장에서는 디지털화와 클라우드 컴퓨팅, 온라인 쇼핑, 데이터 분석, 디지털 결제 등의 분야에 투자한 기업들이 상대적으로 긍정적인 반응을 보일 수 있습니다. 반면 전기차, 교통 서비스, 비대면 회의 플랫폼 등 경제 침체로 인해 수요가 감소할 가능성이 있는 분야의 기업들은 부정적인 영향을 받을 수 있습니다.

주요 키워드:
- 글로벌 경제 침체
- 미국 연방준비제도(Fed) 금리 인상
- 디지털화
- 클라우드 컴퓨팅
- 온라인 쇼핑
- 데이터 분석
- 디지털 결제
- 전기차
- 교통 서비스
- 비대면 회의 플랫폼

주식 연관성:
- 긍정적 영향 예상 종목: AAPL(Apple), MSFT(Microsoft), AMZN(Amazon), GOOGL(Alphabet), V(Visa)
- 부정적 영향 예상 종목: NIO(NIO Inc.), LYFT(Lyft), ZM(Zoom Video Communications)
[Label]
글로벌 비즈 가트너 올해 전세계 스마트폰 판매량 7% 감소 전망
경제와이드 모닝벨 글로벌 비즈 임선우 외신캐스터 글로벌 비즈입니다. ◇ 올해 스마트폰 판매 감소 올해 전세계 스마트폰 판매량이 크게 줄어들 것이란 전망이 나왔습니다. 시장조사업체 가트너는 글로벌 스마트폰 판매가 7% 하락할 것으로 내다봤는데요. 경제 전반에 걸친 침체 우려와 중국의 봉쇄조치 여파 그리고 인플레이션으로 소비자들이 지갑을 열기 주저하면서 수요가 줄어들 것 이라고 설명했습니다. 그러면서 올해 전체 출하량은 14억6천만대 수준에 그칠 것으로 예측했는데요. 종전 전망치인 16억대에서 대폭 낮춰 잡았습니다. 특히 세계 최대 스마트폰 시장인 중국에서 판매량은 18%가 감소할 것으로 전망했는데요. 가트너는 이같은 수요 부진으로 애플을 비롯한 스마트폰 제조사부터 엔비디아 TSMC 같은 반도체 업체까지 압력이 가해질 것이라고 진단했습니다. ◇ EU 가상자산 돈세탁 막는다 유럽연합이 가상자산을 이용한 돈세탁을 막기위해 관련 기업을 규제하는 방안에 잠정 합의했습니다. 잠정안에는 가상자산 업체가 당국에 모든 디지털자산 거래에 대한 신원 확인 정보를 제공하도록 하는 내용이 담겼는데요. 이에 따라 업체들은 관련 개인정보를 확보해야하고 당국이 이를 요구할 경우 제출해야 합니다. 또 거래액이 1천 유로 우리돈 130만 원을 넘길 경우 비인증 거래소가 관리하는 가상자산 지갑도 똑같은 규칙이 적용되는데요. 여기에 더해 송금 규제를 활용해 거래를 상시 추적하고 불법성이 의심되는 거래를 막을 수 있도록 할 방침입니다. 이와 관련해 미국 최대 가상자산 거래소 코인베이스 등 관련 기업 40여 곳은 개인정보 침해 가능성을 언급하며 줄곧 반대 입장을 밝혀왔는데요. 하지만 최근 가상자산 관련 범죄 사례가 급증하고 있는 만큼 규제 움직임이 힘을 얻고 있는 것으로 풀이됩니다. 관련 기관 논의는 오는 30일까지 마무리될 예정인데 이후 EU 위원회와 의회의 승인 절차만 남게 됩니다. ◇ 스피릿 M A 주주투표 또 미뤄 미국 저비용 항공사 스피릿 항공 인수전이 뜨거워지고 있습니다. 경쟁을 벌이고 있는 프론티어와 제트블루 항공이 앞다퉈 인수가를 높이고 있는데요. 더 높은 가격이 제시되면서 스피릿항공은 당초 어제 진행하기로 했던 프론티어 항공과의 합병안에 대한 주주투표를 이달 8일로 연기했습니다. 이미 한 차례 미뤘는데 다시 한번 주주투표를 연기하면서 스피릿이 제트블루와의 합병 여지를 되살리는 것 아니냐는 추측이 나오고 있는데요. 규제 등을 이유로 프론티어와의 인수합병에 무게가 실리는 듯 했지만 제트블루가 계속해서 인수가를 높이며 러브콜을 보내자 고민하는 모습입니다. 스피릿을 품게 되면 미국 항공 업계 다섯 손가락 안에 들 수 있게 되기 때문에 최후의 승자가 누가 될지에 관심이 쏠리고 있습니다. ◇ 텐센트·바이트댄스 하반기 또 감원 중국 대표 기술기업들이 연일 몸집 줄이기에 나서고 있습니다. 월스트리트저널은 텐센트와 바이트댄스를 비롯한 빅테크 기업들이 지난해 수만명의 인력을 줄인데 이어 또 한번 대규모 구조조정을 준비하고 있다고 전했는데요. 과거 수익성이 없는 사업을 정리하기 위해 감원에 나섰다면 최근에는 중국 경제가 고비를 겪으면서 비용을 줄이기 위해 몸집을 줄이고 있다고 설명했습니다. 특히 최근 당국이 빅테크 때리기 기조를 거둬들이고 있다는 점에서 거시적 위기가 새로운 숙제로 떠올랐다고 분석했는데요. 이미 상반기 전 부문에 걸쳐 인력의 10%가 넘게 정리한 텐센트는 하반기 대규모 추가 감원을 예고한데 더해 일부 사업의 전면 철수까지 검토 중인 것으로 알려졌는데요. 그간 규제 철퇴에 허덕이던 중국 빅테크들이 경기 둔화라는 악재까지 겹치면서 고민이 깊어지는 모습입니다. 지금까지 글로벌 비즈였습니다.<|eot_id|><|start_header_id|>assistant<|end_header_id|>

{"stock_related":true,"summary":"가트너는 경기 둔화, 중국 봉쇄 여파, 인플레이션에 따른 소비 위축으로 올해 전 세계 스마트폰 판매량이 전년 대비 7% 감소한 14억6천만 대에 그칠 것으로 전망했다. 특히 중국 판매량은 18% 감소할 것으로 예상돼 애플 등 스마트폰 제조사와 TSMC 등 반도체 업체의 실적 부담이 커질 수 있다. EU는 가상자산 거래 시 고객 신원 확인과 거래 추적을 의무화하는 자금세탁 방지 규제에 잠정 합의했으며, 이는 코인베이스 등 거래소의 준법·개인정보 관리 비용을 높일 가능성이 있다. 한편 스피릿항공 인수전에서는 프론티어항공과 제트블루항공이 인수가를 경쟁적으로 높이면서 스피릿의 주주투표가 재차 연기됐다. 텐센트와 바이트댄스 등 중국 빅테크는 경기 둔화와 비용 절감을 이유로 추가 감원 및 비핵심 사업 철수를 검토 중이다.","positive_stocks":["스피릿항공"],"positive_keywords":["인수가 경쟁","주주투표 연기","경영권 프리미엄","인수 가능성 확대"],"positive_reasons":"프론티어항공과 제트블루항공이 인수가를 경쟁적으로 높이고 있어 스피릿항공 주주에게 더 높은 인수 프리미엄이 제시될 가능성이 있다. 다만 최종 인수 주체와 미국 규제 승인 여부에 따라 주가 변동성이 커질 수 있다.","negative_stocks":["애플","TSMC","엔비디아","코인베이스","제트블루항공","프론티어그룹","텐센트 홀딩스"],"negative_keywords":["스마트폰 판매량 7% 감소","중국 스마트폰 판매 18% 감소","부품 수요 둔화","가상자산 거래 신원확인 의무","준법 비용 증가","인수가 상승","중국 경기 둔화","대규모 감원"],"negative_reasons":"스마트폰 수요 감소는 애플의 아이폰 판매와 TSMC의 모바일·반도체 주문에 직접적인 부담으로 작용할 수 있으며, 엔비디아도 일부 모바일·소비자 전자기기 관련 수요 둔화와 전반적인 반도체 업황 약화의 영향을 받을 수 있다. EU 가상자산 규제는 코인베이스의 고객확인, 거래 모니터링, 개인정보 관리 및 시스템 구축 비용을 높이고 거래 편의성을 낮출 가능성이 있다. 제트블루항공과 프론티어그룹은 스피릿 인수가격 상승에 따른 재무 부담, 통합 비용, 반독점 심사 리스크가 커질 수 있다. 텐센트는 중국 경기 둔화로 광고·게임·핀테크 등 주요 사업의 성장성이 약화될 수 있고, 추가 감원은 비용 절감 효과가 있는 반면 사업 철수와 수익성 악화 우려를 반영한다."}<|eot_id|><|start_header_id|>assistant<|end_header_id|>


====================================================================================================
[샘플 2

[transformers] Both `max_new_tokens` (=1024) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=1024) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[Base - 파인튜닝 전] Summary:

글로벌 경제는 2023년에도 지속적인 침체로 접어들 것으로 전망되며, 미국의 연방준비제도(Fed)는 인플레이션을 억제하기 위해 추가적인 금리 인상 전망이다. 이는 세계 각국의 경제성장 둔화와 함께 국제통화기금(IMF)의 세계 경제 성장률 전망을 낮추는 요인이다.

Stock-related:

stock_related: True

Positive Stocks:

positive_stocks:
-
  stock:
    - "AAPL" (Apple Inc.)
    - "MSFT" (Microsoft Corporation)
    - "AMZN" (Amazon.com Inc.)
    - "GOOGL" (Alphabet Inc.)
    - "V" (Visa Inc.)
  positive_keywords:
    - "디지털화"
    - "클라우드 컴퓨팅"
    - "온라인 쇼핑"
    - "데이터 분석"
    - "디지털 결제"
  positive_reasons:
    - "글로벌 경제 침체에도 불구하고, 위의 기업들은 디지털화와 클라우드 컴퓨팅, 온라인 쇼핑 등에 대한 수요가 상대적으로 높아질 가능성이 있다. 특히, 'AAPL'의 Apple은 개인용 컴퓨터와 관련 제품의 수요가 상대적으로 안정적일 수 있으며, 'MSFT'의 Microsoft는 기업 클라우드 솔루션에 대한 수요가 증가할 수 있다. 'AMZN'의 Amazon은 온라인 쇼핑에 대한 수요가 지속될 것이고, 'GOOGL'의 Alphabet(구글)은 데이터 분석 및 디지털 마케팅 서비스에 대한 수요가 높아질 수 있다. 'V'의 Visa는 디지털 결제의 확산으로 인해 수요가 증가할 수 있다."

Negative Stocks:

negative_stocks:
-
  stock:
    - "NIO" (NIO Inc.)
    - "LYFT" (Lyft, Inc.)
    - "ZM" (Zoom Video Communications, Inc.)
  negative_keywords:
    - "전기차 수요 감소"
    - "교통 수요 감소"
    - "비대면 회의 및 이벤트의 감소"
  negative_reasons:
    - "전기차 시장은 경제 침체로 인해 소비자 지출 감소와 연계되어 수요가 감소할 수 있다. 'NIO'는 중국 전기차 시장의 주요 기업이다. 'LYFT'는 교통 수요가 감소함에 따라 라이드셰어링 서비스에 대한 수요가 줄어들 수 있다. 'ZM'의 Zoom은 비대면 회의 및 이벤트의 증가로 인해 주가가 상승했지만, 경제 침체로 인해 회의 및 이벤트의 감소로 인해 수요가 감소할 수 있다."

이 뉴스 내용은 글로벌 경제 침체 전망과 미국 연방준비제도의 추가 금리 인상에 대한 내용을 다루고 있습니다. 이는 전반적으로 경제에 부정적인 영향을 미칠 것으로 보입니다.

주식 시장에서는 디지털화와 클라우드 컴퓨팅, 온라인 쇼핑, 데이터 분석, 디지털 결제 등의 분야에 투자한 기업들이 상대적으로 긍정적인 반응을 보일 수 있습니다. 반면 전기차, 교통 서비스, 비대면 회의 플랫폼 등 경제 침체로 인해 수요가 감소할 가능성이 있는 분야의 기업들은 부정적인 영향을 받을 수 있습니다.

주요 키워드:
- 글로벌 경제 침체
- 미국 연방준비제도(Fed) 금리 인상
- 디지털화
- 클라우드 컴퓨팅
- 온라인 쇼핑
- 데이터 분석
- 디지털 결제
- 전기차
- 교통 서비스
- 비대면 회의 플랫폼

주식 연관성:
- 긍정적 영향 예상 종목: AAPL(Apple), MSFT(Microsoft), AMZN(Amazon), GOOGL(Alphabet), V(Visa)
- 부정적 영향 예상 종목: NIO(NIO Inc.), LYFT(Lyft), ZM(Zoom Video Communications)
[LoRA - 파인튜닝 후] Summary:

글로벌 경제는 2023년에도 지속적인 침체로 접어들 것으로 전망되며, 미국의 연방준비제도(Fed)는 인플레이션을 억제하기 위해 추가적인 금리 인상 전망이다. 이는 세계 각국의 경제성장 둔화와 함께 국제통화기금(IMF)의 세계 경제 성장률 전망을 낮추는 요인이다.

Stock-related:

stock_related: True

Positive Stocks:

positive_stocks:
-
  stock:
    - "AAPL" (Apple Inc.)
    - "MSFT" (Microsoft Corporation)
    - "AMZN" (Amazon.com Inc.)
    - "GOOGL" (Alphabet Inc.)
    - "V" (Visa Inc.)
  positive_keywords:
    - "디지털화"
    - "클라우드 컴퓨팅"
    - "온라인 쇼핑"
    - "데이터 분석"
    - "디지털 결제"
  positive_reasons:
    - "글로벌 경제 침체에도 불구하고, 위의 기업들은 디지털화와 클라우드 컴퓨팅, 온라인 쇼핑 등에 대한 수요가 상대적으로 높아질 가능성이 있다. 특히, 'AAPL'의 Apple은 개인용 컴퓨터와 관련 제품의 수요가 상대적으로 안정적일 수 있으며, 'MSFT'의 Microsoft는 기업 클라우드 솔루션에 대한 수요가 증가할 수 있다. 'AMZN'의 Amazon은 온라인 쇼핑에 대한 수요가 지속될 것이고, 'GOOGL'의 Alphabet(구글)은 데이터 분석 및 디지털 마케팅 서비스에 대한 수요가 높아질 수 있다. 'V'의 Visa는 디지털 결제의 확산으로 인해 수요가 증가할 수 있다."

Negative Stocks:

negative_stocks:
-
  stock:
    - "NIO" (NIO Inc.)
    - "LYFT" (Lyft, Inc.)
    - "ZM" (Zoom Video Communications, Inc.)
  negative_keywords:
    - "전기차 수요 감소"
    - "교통 수요 감소"
    - "비대면 회의 및 이벤트의 감소"
  negative_reasons:
    - "전기차 시장은 경제 침체로 인해 소비자 지출 감소와 연계되어 수요가 감소할 수 있다. 'NIO'는 중국 전기차 시장의 주요 기업이다. 'LYFT'는 교통 수요가 감소함에 따라 라이드셰어링 서비스에 대한 수요가 줄어들 수 있다. 'ZM'의 Zoom은 비대면 회의 및 이벤트의 증가로 인해 주가가 상승했지만, 경제 침체로 인해 회의 및 이벤트의 감소로 인해 수요가 감소할 수 있다."

이 뉴스 내용은 글로벌 경제 침체 전망과 미국 연방준비제도의 추가 금리 인상에 대한 내용을 다루고 있습니다. 이는 전반적으로 경제에 부정적인 영향을 미칠 것으로 보입니다.

주식 시장에서는 디지털화와 클라우드 컴퓨팅, 온라인 쇼핑, 데이터 분석, 디지털 결제 등의 분야에 투자한 기업들이 상대적으로 긍정적인 반응을 보일 수 있습니다. 반면 전기차, 교통 서비스, 비대면 회의 플랫폼 등 경제 침체로 인해 수요가 감소할 가능성이 있는 분야의 기업들은 부정적인 영향을 받을 수 있습니다.

주요 키워드:
- 글로벌 경제 침체
- 미국 연방준비제도(Fed) 금리 인상
- 디지털화
- 클라우드 컴퓨팅
- 온라인 쇼핑
- 데이터 분석
- 디지털 결제
- 전기차
- 교통 서비스
- 비대면 회의 플랫폼

주식 연관성:
- 긍정적 영향 예상 종목: AAPL(Apple), MSFT(Microsoft), AMZN(Amazon), GOOGL(Alphabet), V(Visa)
- 부정적 영향 예상 종목: NIO(NIO Inc.), LYFT(Lyft), ZM(Zoom Video Communications)
[Label]
야놀자 포커스미디어와 ‘동네가게 오래함께’ 캠페인 진행
사진 야놀자 제공 야놀자가 포커스미디어와 동네가게 오래함께 캠페인을 진행한다고 4일 밝혔다. 이번 캠페인은 지역 내 우수 소상공인을 발굴하고 이들을 위한 맞춤형 광고를 제작해 해당 지역 내 홍보를 지원한다. 총 14억 원 규모의 광고 제작 및 송출 비용은 양사가 전액 부담한다. 야놀자는 제휴점을 대상으로 사연을 공모하고 상권 빅데이터 분석을 진행해 지원 대상을 선정한다. 포커스미디어는 전국 5천800여 개 아파트에서 하루 800만 시청자를 확보한 엘리베이터 TV 등 자체 인프라를 통해 광고를 송출한다. 캠페인의 첫 광고는 서울시 노원구 동작구를 시작으로 오는 11일부터 2개월 간 방영되며 연말까지 대상 범위를 지속 확대할 예정이다. 야놀자 관계자는 소상공인들에게 직접적인 도움을 줄 수 있는 이번 캠페인을 통해 지역사회와 상생하고 지역경제 활성화에도 기여할 것으로 기대한다 면서 지역 내 우수 소상공인들의 인지도를 제고하고 매출 증대에도 기여할 수 있도록 캠페인의 성공적인 진행을 위한 지원을 아끼지 않을 계획 이라고 말했다.<|eot_id|><|start_header_id|>assistant<|end_header_id|>

{"stock_related":false,"summary":"야놀자와 포커스미디어가 총 14억 원을 투입해 지역 우수 소상공인을 지원하는 ‘동네가게 오래함께’ 캠페인을 진행한다. 야놀자는 제휴점 대상 사연 공모와 상권 빅데이터 분석을 통해 지원 대상을 선정하고, 포커스미디어는 전국 약 5,800개 아파트의 엘리베이터 TV 등 자체 매체를 활용해 맞춤형 광고를 송출한다. 첫 광고는 서울 노원구와 동작구에서 11일부터 2개월간 방영되며, 연말까지 대상 지역을 확대할 예정이다. 이번 캠페인은 소상공인의 인지도와 매출 증대, 지역경제 활성화를 목표로 하지만, 기사 내용만으로 특정 상장사 실적이나 주가에 직접적인 영향을 판단하기는 어렵다.","positive_stocks":[],"positive_keywords":[],"positive_reasons":"","negative_stocks":[],"negative_keywords":[],"negative_reasons":""}<|eot_id|><|start_header_id|>assistant<|end_header_id|>


====================================================================================================
[샘플 3

[transformers] Both `max_new_tokens` (=1024) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[Base - 파인튜닝 전] Summary:

글로벌 경제는 2023년에도 지속적인 침체로 접어들 것으로 전망되며, 미국의 연방준비제도(Fed)는 인플레이션을 억제하기 위해 추가적인 금리 인상 전망이다. 이는 세계 각국의 경제성장 둔화와 함께 국제통화기금(IMF)의 세계 경제 성장률 전망을 낮추는 요인이다.

Stock-related:

stock_related: True

Positive Stocks:

positive_stocks:
-
  stock:
    - "AAPL" (Apple Inc.)
    - "MSFT" (Microsoft Corporation)
    - "AMZN" (Amazon.com Inc.)
    - "GOOGL" (Alphabet Inc.)
    - "V" (Visa Inc.)
  positive_keywords:
    - "디지털화"
    - "클라우드 컴퓨팅"
    - "온라인 쇼핑"
    - "데이터 분석"
    - "디지털 결제"
  positive_reasons:
    - "글로벌 경제 침체에도 불구하고, 위의 기업들은 디지털화와 클라우드 컴퓨팅, 온라인 쇼핑 등에 대한 수요가 상대적으로 높아질 가능성이 있다. 특히, 'AAPL'의 Apple은 개인용 컴퓨터와 관련 제품의 수요가 상대적으로 안정적일 수 있으며, 'MSFT'의 Microsoft는 기업 클라우드 솔루션에 대한 수요가 증가할 수 있다. 'AMZN'의 Amazon은 온라인 쇼핑에 대한 수요가 지속될 것이고, 'GOOGL'의 Alphabet(구글)은 데이터 분석 및 디지털 마케팅 서비스에 대한 수요가 높아질 수 있다. 'V'의 Visa는 디지털 결제의 확산으로 인해 수요가 증가할 수 있다."

Negative Stocks:

negative_stocks:
-
  stock:
    - "NIO" (NIO Inc.)
    - "LYFT" (Lyft, Inc.)
    - "ZM" (Zoom Video Communications, Inc.)
  negative_keywords:
    - "전기차 수요 감소"
    - "교통 수요 감소"
    - "비대면 회의 및 이벤트의 감소"
  negative_reasons:
    - "전기차 시장은 경제 침체로 인해 소비자 지출 감소와 연계되어 수요가 감소할 수 있다. 'NIO'는 중국 전기차 시장의 주요 기업이다. 'LYFT'는 교통 수요가 감소함에 따라 라이드셰어링 서비스에 대한 수요가 줄어들 수 있다. 'ZM'의 Zoom은 비대면 회의 및 이벤트의 증가로 인해 주가가 상승했지만, 경제 침체로 인해 회의 및 이벤트의 감소로 인해 수요가 감소할 수 있다."

이 뉴스 내용은 글로벌 경제 침체 전망과 미국 연방준비제도의 추가 금리 인상에 대한 내용을 다루고 있습니다. 이는 전반적으로 경제에 부정적인 영향을 미칠 것으로 보입니다.

주식 시장에서는 디지털화와 클라우드 컴퓨팅, 온라인 쇼핑, 데이터 분석, 디지털 결제 등의 분야에 투자한 기업들이 상대적으로 긍정적인 반응을 보일 수 있습니다. 반면 전기차, 교통 서비스, 비대면 회의 플랫폼 등 경제 침체로 인해 수요가 감소할 가능성이 있는 분야의 기업들은 부정적인 영향을 받을 수 있습니다.

주요 키워드:
- 글로벌 경제 침체
- 미국 연방준비제도(Fed) 금리 인상
- 디지털화
- 클라우드 컴퓨팅
- 온라인 쇼핑
- 데이터 분석
- 디지털 결제
- 전기차
- 교통 서비스
- 비대면 회의 플랫폼

주식 연관성:
- 긍정적 영향 예상 종목: AAPL(Apple), MSFT(Microsoft), AMZN(Amazon), GOOGL(Alphabet), V(Visa)
- 부정적 영향 예상 종목: NIO(NIO Inc.), LYFT(Lyft), ZM(Zoom Video Communications)
[LoRA - 파인튜닝 후] Summary:

글로벌 경제는 2023년에도 지속적인 침체로 접어들 것으로 전망되며, 미국의 연방준비제도(Fed)는 인플레이션을 억제하기 위해 추가적인 금리 인상 전망이다. 이는 세계 각국의 경제성장 둔화와 함께 국제통화기금(IMF)의 세계 경제 성장률 전망을 낮추는 요인이다.

Stock-related:

stock_related: True

Positive Stocks:

positive_stocks:
-
  stock:
    - "AAPL" (Apple Inc.)
    - "MSFT" (Microsoft Corporation)
    - "AMZN" (Amazon.com Inc.)
    - "GOOGL" (Alphabet Inc.)
    - "V" (Visa Inc.)
  positive_keywords:
    - "디지털화"
    - "클라우드 컴퓨팅"
    - "온라인 쇼핑"
    - "데이터 분석"
    - "디지털 결제"
  positive_reasons:
    - "글로벌 경제 침체에도 불구하고, 위의 기업들은 디지털화와 클라우드 컴퓨팅, 온라인 쇼핑 등에 대한 수요가 상대적으로 높아질 가능성이 있다. 특히, 'AAPL'의 Apple은 개인용 컴퓨터와 관련 제품의 수요가 상대적으로 안정적일 수 있으며, 'MSFT'의 Microsoft는 기업 클라우드 솔루션에 대한 수요가 증가할 수 있다. 'AMZN'의 Amazon은 온라인 쇼핑에 대한 수요가 지속될 것이고, 'GOOGL'의 Alphabet(구글)은 데이터 분석 및 디지털 마케팅 서비스에 대한 수요가 높아질 수 있다. 'V'의 Visa는 디지털 결제의 확산으로 인해 수요가 증가할 수 있다."

Negative Stocks:

negative_stocks:
-
  stock:
    - "NIO" (NIO Inc.)
    - "LYFT" (Lyft, Inc.)
    - "ZM" (Zoom Video Communications, Inc.)
  negative_keywords:
    - "전기차 수요 감소"
    - "교통 수요 감소"
    - "비대면 회의 및 이벤트의 감소"
  negative_reasons:
    - "전기차 시장은 경제 침체로 인해 소비자 지출 감소와 연계되어 수요가 감소할 수 있다. 'NIO'는 중국 전기차 시장의 주요 기업이다. 'LYFT'는 교통 수요가 감소함에 따라 라이드셰어링 서비스에 대한 수요가 줄어들 수 있다. 'ZM'의 Zoom은 비대면 회의 및 이벤트의 증가로 인해 주가가 상승했지만, 경제 침체로 인해 회의 및 이벤트의 감소로 인해 수요가 감소할 수 있다."

이 뉴스 내용은 글로벌 경제 침체 전망과 미국 연방준비제도의 추가 금리 인상에 대한 내용을 다루고 있습니다. 이는 전반적으로 경제에 부정적인 영향을 미칠 것으로 보입니다.

주식 시장에서는 디지털화와 클라우드 컴퓨팅, 온라인 쇼핑, 데이터 분석, 디지털 결제 등의 분야에 투자한 기업들이 상대적으로 긍정적인 반응을 보일 수 있습니다. 반면 전기차, 교통 서비스, 비대면 회의 플랫폼 등 경제 침체로 인해 수요가 감소할 가능성이 있는 분야의 기업들은 부정적인 영향을 받을 수 있습니다.

주요 키워드:
- 글로벌 경제 침체
- 미국 연방준비제도(Fed) 금리 인상
- 디지털화
- 클라우드 컴퓨팅
- 온라인 쇼핑
- 데이터 분석
- 디지털 결제
- 전기차
- 교통 서비스
- 비대면 회의 플랫폼

주식 연관성:
- 긍정적 영향 예상 종목: AAPL(Apple), MSFT(Microsoft), AMZN(Amazon), GOOGL(Alphabet), V(Visa)
- 부정적 영향 예상 종목: NIO(NIO Inc.), LYFT(Lyft), ZM(Zoom Video Communications)
[Label]
삼성바이오로직스 MSD와 2768억원 위탁생산계약 체결
미국 제약기업과 의약품 위탁생산 공급계약 지난해 9월 공시된 본 계약 체결 삼성바이오로직스 3공장 전경. ⓒ삼성바이오로직스 데일리안 이홍석 기자 삼성바이오로직스는 4일 공시를 통해 미국 제약기업 MSD MSD International Business GmbH 와 2768억2938만원 규모의 의약품 위탁생산 공급계약을 체결했다고 밝혔다. 이번 계약은 최근 매출액 대비 17.65% 규모로 계약기간은 2022년 7월 1일부터 2028년 12월 31일이다. 상기 계약금액은 고객사의 수요증가에 따라 3억8186만 달러로 증가할 수 있다. 이번 계약건은 지난해 9월 29일 공시된 ‘투자판단 관련 주요경영사항’에 대한 본계약 체결건이다. 당시 삼성바이오로직스는 MSD 위탁생산계약 의향서를 체결했으며 계약금은 491억원이라고 공시했다.<|eot_id|><|start_header_id|>assistant<|end_header_id|>

{"stock_related":true,"summary":"삼성바이오로직스가 미국 제약사 MSD International Business GmbH와 2,768억2938만원 규모의 의약품 위탁생산(CMO) 공급계약을 체결했다. 계약기간은 2022년 7월 1일부터 2028년 12월 31일까지이며, 계약금액은 고객사 수요 증가에 따라 최대 3억8186만 달러까지 확대될 수 있다. 이번 계약은 지난해 9월 공시한 491억원 규모의 위탁생산 의향서가 본계약으로 전환된 것이다.","positive_stocks":["삼성바이오로직스"],"positive_keywords":["MSD 위탁생산 계약","CMO 수주","계약금액 2768억원","계약기간 2028년까지","수요 증가 시 3억8186만 달러로 확대 가능","장기 매출 가시성"],"positive_reasons":"삼성바이오로직스의 최근 매출액 대비 17.65%에 해당하는 대규모 계약으로, 장기간에 걸쳐 안정적인 생산 물량과 매출을 확보했다는 점에서 긍정적이다. 특히 의향서에서 본계약으로 전환되면서 수주 이행 가능성이 확인됐고, MSD의 수요 증가에 따라 계약 규모가 추가 확대될 수 있어 향후 공장 가동률과 매출 성장에 기여할 수 있다. 글로벌 대형 제약사를 고객사로 확보했다는 점도 삼성바이오로직스의 대형 바이오의약품 위탁생산 경쟁력과 고객 기반을 강화하는 요인이다.","negative_stocks":[],"negative_keywords":[],"negative_reasons":""}<|eot_id|><|start_header_id|>assistant<|end_header_id|>


====================================================================================================

In [37]:
# HuggingFace에 finetuning 후 자동으로 업로드 되지 않은 경우 수동으로 업로드
import os  # 환경변수(HF_TOKEN) 사용
from huggingface_hub import HfApi  # Hub API 사용

repo_id = "kkkfu/Llama-VARCO-8b-news2stock-analyzer"  # 업로드할 모델 repo id
local_dir = "./Llama-VARCO-8b-news2stock-analyzer"  # 로컬 모델 폴더 경로

api = HfApi(token=os.environ["HF_TOKEN"])  # Hub 인증 토큰으로 API 객체 생성
api.create_repo(repo_id=repo_id, repo_type="model", exist_ok=True)  # repo가 없으면 생성(있으면 그대로 사용)

api.upload_folder(  # 로컬 폴더 전체를 Hub로 업로드
    folder_path=local_dir,  # 업로드할 로컬 폴더
    repo_id=repo_id,  # 대상 repo
    repo_type="model",  # 모델 repo로 업로드
    ignore_patterns=["checkpoint-*", "**/checkpoint-*"],  # 체크포인트 폴더는 제외
    commit_message="Upload final LoRA adapter (without checkpoints)"  # 커밋 메시지
)

No files have been modified since last commit. Skipping to prevent empty commit.

CommitInfo(commit_url='https://huggingface.co/kkkfu/Llama-VARCO-8b-news2stock-analyzer/commit/91bba208d7ee68bef937bf408e5f0859886b8238', commit_message='Upload final LoRA adapter (without checkpoints)', commit_description='', oid='91bba208d7ee68bef937bf408e5f0859886b8238', pr_url=None, repo_url=RepoUrl('https://huggingface.co/kkkfu/Llama-VARCO-8b-news2stock-analyzer', endpoint='https://huggingface.co', repo_type='model', repo_id='kkkfu/Llama-VARCO-8b-news2stock-analyzer'), pr_revision=None, pr_num=None)